import type { Locale } from '../../LocaleProvider';

export type TeacherUi = ReturnType<typeof teacherUi>;

export function teacherUi(locale: Locale) {
  if (locale === 'de') return {
    na:'k. A.', singleLive:'Einzelne Live-Frage', customActivity:'Eigene Aktivität', creating:'Klassenraum wird erstellt…', createFailed:'Der Klassenraum konnte nicht erstellt werden. Firebase ist in dieser Umgebung möglicherweise nicht verfügbar.', created:'Klassenraum erstellt. Teile nur den Raumcode oder Beitrittslink und behalte den Lehrkraft-Schlüssel für dich.', loadFailed:'Klassenraum konnte nicht geladen werden. Prüfe Raumcode und Lehrkraft-Schlüssel.', refreshed:'Klassenraum aktualisiert.', actionFailed:'Aktion konnte nicht ausgeführt werden.', activityLoaded:'Aktivität geladen. Bereits vorhandene anonyme Klassenergebnisse bleiben in der Raumhistorie erhalten.', joinCopied:'Beitrittslink kopiert.', accessRemoved:'Lehrkraft-Zugang aus dieser Browser-Sitzung entfernt.',
    choose:'Was willst du unterrichten?', roomLabel:'Bezeichnung des Raums', roomPlaceholder:'Politik · Jahrgang 10', ageBand:'Altersgruppe', ages:(range:string)=>`${range} Jahre`, activity:'Aktivität', literacyQuiz:'Politisches Wissensquiz', guided:'Geführte Unterrichtseinheit', custom:'Eigene Auswahl / einzelne Frage', lesson:'Unterrichtseinheit', pacing:'Tempo', teacherPaced:'Von dir gesteuert', studentPaced:'Eigenes Tempo der Schüler:innen', projectorDistribution:'Anzeige am Projektor', revealChoice:'Erst zeigen, wenn du freigibst', liveChoice:'Live zeigen, während Antworten eingehen', selectApproved:(count:number)=>`Freigegebene Fragen auswählen (${count} gewählt)`, startClass:'Klassenraum starten', loadActivity:'Diese Aktivität laden', openExisting:'Vorhandenen Klassenraum öffnen', roomCode:'Raumcode', teacherKey:'Lehrkraft-Schlüssel', openClass:'Klassenraum öffnen',
    classWord:'Klasse', joined:(n:number)=>`${n} beigetreten`, active:'aktiv', closed:'geschlossen', onboarding:'Klasse einrichten', roomCodeCaps:'RAUMCODE', studentJoin:'Beitritt für Schüler:innen:', projector:'Projektor:', copyStudent:'Schülerlink kopieren', openProjector:'Projektor öffnen', endClass:'Klassenraum beenden', reopenClass:'Klassenraum wieder öffnen', forgetKey:'Schlüssel vergessen', privacyIntro:'Schüler:innen treten ohne Namen oder Konten bei. Das Lehrkraft-Dashboard zeigt nur aggregierte Verteilungen und speichert keine Zuordnung von Person zu Antwort.',
    lessonGuide:(duration:string,age:string)=>`Unterrichtsleitfaden · ${duration} · ${age} Jahre`, lessonNotice:'Die geführten Unterrichtseinheiten selbst liegen derzeit nur in der geprüften englischen Fassung vor. Die Steuerung ist auf Deutsch; Unterrichtstexte werden erst nach einer eigenen sprachlichen Prüfung lokalisiert.', timeline:'Ablauf & Leitfaden', teacher:'Lehrkraft', students:'Schüler:innen', prompts:'Diskussionsfragen',
    liveClass:'Live-Klasse', chooseQuestion:'Wähle eine Frage für die Diskussion', responses:'Antworten', ofJoined:(n:number)=>`von ${n} Teilnehmenden`, correct:'richtig', closeResponses:'Antworten schließen', hideProjector:'Am Projektor ausblenden', revealProjector:'Am Projektor zeigen', nextQuestion:'Nächste Frage',
    launcher:'Fragen starten', launcherHelp:'Starte jede freigegebene Frage aus der gewählten Aktivität. Du kannst jederzeit pausieren, diskutieren, die Aktivität wechseln oder die Richtung ändern.', notAnswered:'noch nicht beantwortet', responseCount:(n:number)=>`${n} Antworten`,
    classroomSummary:'Politangle · Klassenübersicht', questionsWithResponses:(answered:number,total:number)=>`${answered}/${total} Fragen mit Antworten`, print:'Drucken / als PDF speichern', joinedMetric:'beigetreten', responsesMetric:'Antworten', questionsAnswered:'beantwortete Fragen', literacyCorrect:'Wissen richtig',
    axisKicker:'Aggregierte 8-Achsen-Klassenkarte', axisTitle:'So verteilt sich die Klasse auf die politischen Dimensionen', axisHelp:'Das sind aggregierte Antwortverteilungen – kein individuelles Profil und kein Etikett für die Klasse.',
    familyKicker:'Aggregierte Nähe zu politischen Traditionen', familyTitle:'Mehrere politische Traditionen können gleichzeitig zur Klasse passen', coverage:'Abdeckung', familyHelp:'Die Werte werden aus aggregierten Antwortverteilungen mit denselben fachlich geprüften Familien-Prioren berechnet. Sie sind weder Wahlprognose noch die Behauptung, die Klasse „sei“ eine bestimmte Ideologie.',
    mostDivided:'Am stärksten geteilt', dividedTitle:'Wo die Klasse auseinandergeht', consensus:'Stärkster Konsens', consensusTitle:'Wo sich Antworten bündeln',
    tensionTitle:'Größte aggregierte Unterschiede zwischen THINK, FEEL und ACT', construct:'Thema', tension:'Abstand', tensionHelp:'ACT bedeutet angegebene Handlungsabsicht, nicht beobachtetes Verhalten. Ein Abstand ist ein Gesprächsimpuls – kein Vorwurf von Widersprüchlichkeit.',
    literacy:'Politisches Wissen', aggregateCorrect:(percent:number)=>`${percent}% im Klassendurchschnitt richtig`, literacyHelp:'Nutze die schwächsten Konzepte als Ausgangspunkt für die nächste Erklärung oder Diskussion. Die Lehrkraft erhält keine individuellen Punktzahlen.',
    distributions:'Antwortverteilungen', distributionTitle:'Die Verteilung ist wichtiger als ein Durchschnitt.',
    privacyBoundary:'Datenschutzgrenze', seeAggregate:'Lehrkraft kann aggregierte politische Verteilungen sehen', seeWho:'Lehrkraft kann sehen, wer eine Antwort gewählt hat', roster:'Schülerliste erforderlich', mapping:'Zuordnung zwischen Teilnehmer und Antwort im Klassenaggregat gespeichert', yes:'Ja', no:'Nein', legal:'QUALIFIZIERTE RECHTLICHE PRÜFUNG ERFORDERLICH, bevor Politangle mit echten Schüler:innen bzw. Minderjährigen eingesetzt wird.',
    literacyNotice:'CLASSIFY/UNDERSTAND-Inhalte in der Klassenansicht verwenden nur dort Deutsch, wo eine geprüfte deutsche Fassung vorhanden ist.',
  };
  if (locale === 'es') return {
    na:'n/d', singleLive:'Una pregunta en directo', customActivity:'Actividad personalizada', creating:'Creando el aula…', createFailed:'No se pudo crear el aula. Puede que Firebase no esté disponible en este entorno.', created:'Aula creada. Comparte solo el código de sala o el enlace de entrada y guarda para ti la clave docente.', loadFailed:'No se pudo abrir el aula. Comprueba el código y la clave docente.', refreshed:'Aula actualizada.', actionFailed:'No se pudo completar la acción docente.', activityLoaded:'Actividad cargada. Los resultados anónimos que ya existen siguen en el historial de la sala.', joinCopied:'Enlace de entrada copiado.', accessRemoved:'Acceso docente eliminado de esta sesión del navegador.',
    choose:'¿Qué quieres trabajar en clase?', roomLabel:'Nombre de la sala', roomPlaceholder:'Política · 4.º ESO', ageBand:'Edad', ages:(range:string)=>`${range} años`, activity:'Actividad', literacyQuiz:'Quiz de cultura política', guided:'Sesión guiada', custom:'Mi selección / una sola pregunta', lesson:'Sesión', pacing:'Ritmo', teacherPaced:'Lo marcas tú', studentPaced:'Cada alumno a su ritmo', projectorDistribution:'Resultados en el proyector', revealChoice:'Mostrar cuando tú decidas', liveChoice:'Mostrar en directo mientras llegan respuestas', selectApproved:(count:number)=>`Elegir preguntas aprobadas (${count} seleccionadas)`, startClass:'Crear aula', loadActivity:'Cargar esta actividad', openExisting:'Abrir un aula existente', roomCode:'Código de sala', teacherKey:'Clave docente', openClass:'Abrir aula',
    classWord:'Clase', joined:(n:number)=>`${n} dentro`, active:'activa', closed:'cerrada', onboarding:'Preparar el aula', roomCodeCaps:'CÓDIGO DE SALA', studentJoin:'Entrada del alumnado:', projector:'Proyector:', copyStudent:'Copiar enlace del alumnado', openProjector:'Abrir proyector', endClass:'Cerrar aula', reopenClass:'Reabrir aula', forgetKey:'Olvidar clave', privacyIntro:'El alumnado entra sin nombres ni cuentas. El panel docente recibe distribuciones agregadas, no registros que relacionen a una persona con su respuesta.',
    lessonGuide:(duration:string,age:string)=>`Guía de la sesión · ${duration} · ${age} años`, lessonNotice:'Las sesiones guiadas todavía conservan su contenido pedagógico revisado en inglés. La interfaz está en español; los textos didácticos se localizarán solo después de una revisión específica.', timeline:'Secuencia y guía docente', teacher:'Docente', students:'Alumnado', prompts:'Preguntas para debatir',
    liveClass:'Aula en directo', chooseQuestion:'Elige una pregunta para centrar el debate', responses:'respuestas', ofJoined:(n:number)=>`de ${n} participantes`, correct:'correcto', closeResponses:'Cerrar respuestas', hideProjector:'Ocultar en el proyector', revealProjector:'Mostrar en el proyector', nextQuestion:'Siguiente pregunta',
    launcher:'Lanzar preguntas', launcherHelp:'Puedes lanzar cualquier pregunta aprobada de la actividad elegida. Pausa, debate, cambia de actividad o de rumbo cuando lo necesites.', notAnswered:'todavía sin respuesta', responseCount:(n:number)=>`${n} respuestas`,
    classroomSummary:'Politangle · Resumen de la clase', questionsWithResponses:(answered:number,total:number)=>`${answered}/${total} preguntas con respuestas`, print:'Imprimir / guardar como PDF', joinedMetric:'participantes', responsesMetric:'respuestas', questionsAnswered:'preguntas respondidas', literacyCorrect:'conocimientos correctos',
    axisKicker:'Mapa agregado de 8 ejes', axisTitle:'Cómo se sitúa el grupo en las distintas dimensiones políticas', axisHelp:'Son distribuciones agregadas de respuestas, no un perfil individual ni una etiqueta para la clase.',
    familyKicker:'Afinidad política agregada del grupo', familyTitle:'Varias tradiciones pueden encajar a la vez', coverage:'cobertura', familyHelp:'Se calcula a partir de distribuciones agregadas con los mismos criterios de familias revisados académicamente. No predice el voto ni afirma que la clase “sea” una ideología.',
    mostDivided:'Mayor división', dividedTitle:'Dónde se divide el grupo', consensus:'Mayor consenso', consensusTitle:'Dónde se concentran las respuestas',
    tensionTitle:'Mayores diferencias agregadas entre THINK, FEEL y ACT', construct:'Tema', tension:'Diferencia', tensionHelp:'ACT describe una elección declarada, no una conducta observada. La diferencia sirve para conversar; no es una acusación de incoherencia.',
    literacy:'Cultura política', aggregateCorrect:(percent:number)=>`${percent}% de aciertos agregados`, literacyHelp:'Usa los conceptos con peor resultado como punto de partida para explicar o debatir. El profesor no recibe notas individuales.',
    distributions:'Distribución de respuestas', distributionTitle:'La distribución cuenta más que una media.',
    privacyBoundary:'Límite de privacidad', seeAggregate:'El profesor puede ver distribuciones políticas agregadas', seeWho:'El profesor puede ver quién eligió una respuesta', roster:'Hace falta una lista de alumnos', mapping:'El registro agregado conserva una relación participante-respuesta', yes:'Sí', no:'No', legal:'REQUIERE REVISIÓN JURÍDICA CUALIFICADA antes de utilizar Politangle con alumnado real o menores.',
    literacyNotice:'Las actividades CLASSIFY/UNDERSTAND siguen mostrando su contenido validado en inglés mientras se revisa una versión española.',
  };
  if (locale === 'fr') return {
    na:'n.d.', singleLive:'Une question en direct', customActivity:'Activité personnalisée', creating:'Création de la classe…', createFailed:'Impossible de créer la classe. Firebase est peut-être indisponible dans cet environnement.', created:'Classe créée. Partage uniquement le code ou le lien d’accès et garde la clé enseignant privée.', loadFailed:'Impossible d’ouvrir la classe. Vérifie le code et la clé enseignant.', refreshed:'Classe actualisée.', actionFailed:'Impossible d’effectuer cette action enseignant.', activityLoaded:'Activité chargée. Les résultats anonymes déjà recueillis restent dans l’historique de la salle.', joinCopied:'Lien élève copié.', accessRemoved:'Accès enseignant retiré de cette session du navigateur.',
    choose:'Que veux-tu travailler en classe ?', roomLabel:'Nom de la salle', roomPlaceholder:'Politique · classe de seconde', ageBand:'Tranche d’âge', ages:(range:string)=>`${range} ans`, activity:'Activité', literacyQuiz:'Quiz de culture politique', guided:'Séance guidée', custom:'Ma sélection / une seule question', lesson:'Séance', pacing:'Rythme', teacherPaced:'Tu pilotes', studentPaced:'Chaque élève à son rythme', projectorDistribution:'Résultats au projecteur', revealChoice:'Afficher quand tu le décides', liveChoice:'Afficher en direct pendant les réponses', selectApproved:(count:number)=>`Choisir les questions validées (${count} sélectionnées)`, startClass:'Créer la classe', loadActivity:'Charger cette activité', openExisting:'Ouvrir une classe existante', roomCode:'Code de salle', teacherKey:'Clé enseignant', openClass:'Ouvrir la classe',
    classWord:'Classe', joined:(n:number)=>`${n} présents`, active:'active', closed:'fermée', onboarding:'Préparer la classe', roomCodeCaps:'CODE DE SALLE', studentJoin:'Accès élèves :', projector:'Projecteur :', copyStudent:'Copier le lien élève', openProjector:'Ouvrir le projecteur', endClass:'Fermer la classe', reopenClass:'Rouvrir la classe', forgetKey:'Oublier la clé', privacyIntro:'Les élèves rejoignent sans nom ni compte. Le tableau de bord enseignant reçoit des répartitions agrégées, jamais un lien entre une personne et sa réponse.',
    lessonGuide:(duration:string,age:string)=>`Guide de séance · ${duration} · ${age} ans`, lessonNotice:'Les séances guidées conservent pour l’instant leur contenu pédagogique relu en anglais. L’interface est en français ; les textes de cours ne seront localisés qu’après une révision dédiée.', timeline:'Déroulé et guide enseignant', teacher:'Enseignant', students:'Élèves', prompts:'Questions de discussion',
    liveClass:'Classe en direct', chooseQuestion:'Choisis une question pour lancer la discussion', responses:'réponses', ofJoined:(n:number)=>`sur ${n} participants`, correct:'correct', closeResponses:'Fermer les réponses', hideProjector:'Masquer au projecteur', revealProjector:'Afficher au projecteur', nextQuestion:'Question suivante',
    launcher:'Lancer une question', launcherHelp:'Lance n’importe quelle question validée de l’activité choisie. Tu peux faire une pause, discuter, changer d’activité ou de direction à tout moment.', notAnswered:'pas encore répondu', responseCount:(n:number)=>`${n} réponses`,
    classroomSummary:'Politangle · Synthèse de la classe', questionsWithResponses:(answered:number,total:number)=>`${answered}/${total} questions avec réponses`, print:'Imprimer / enregistrer en PDF', joinedMetric:'participants', responsesMetric:'réponses', questionsAnswered:'questions répondues', literacyCorrect:'culture politique correcte',
    axisKicker:'Carte agrégée de la classe sur 8 axes', axisTitle:'Comment le groupe se répartit sur les dimensions politiques', axisHelp:'Il s’agit de répartitions agrégées, pas d’un profil individuel ni d’une étiquette pour la classe.',
    familyKicker:'Affinités politiques agrégées', familyTitle:'Plusieurs traditions peuvent correspondre au groupe en même temps', coverage:'couverture', familyHelp:'Le calcul part des répartitions agrégées avec les mêmes critères de familles revus académiquement. Ce n’est ni une prédiction de vote ni l’affirmation que la classe « est » une idéologie.',
    mostDivided:'Plus forte division', dividedTitle:'Là où le groupe se partage', consensus:'Plus fort consensus', consensusTitle:'Là où les réponses se regroupent',
    tensionTitle:'Plus grands écarts agrégés entre THINK, FEEL et ACT', construct:'Thème', tension:'Écart', tensionHelp:'ACT décrit un choix déclaré, pas un comportement observé. L’écart sert à ouvrir la discussion ; ce n’est pas un reproche d’incohérence.',
    literacy:'Culture politique', aggregateCorrect:(percent:number)=>`${percent}% de bonnes réponses agrégées`, literacyHelp:'Utilise les notions les moins bien réussies comme points de départ pour expliquer ou discuter. L’enseignant ne reçoit pas de notes individuelles.',
    distributions:'Répartition des réponses', distributionTitle:'La répartition compte davantage qu’une moyenne.',
    privacyBoundary:'Limite de confidentialité', seeAggregate:'L’enseignant peut voir les répartitions politiques agrégées', seeWho:'L’enseignant peut voir qui a choisi une réponse', roster:'Une liste d’élèves est nécessaire', mapping:'Le registre agrégé conserve un lien participant-réponse', yes:'Oui', no:'Non', legal:'REVUE JURIDIQUE QUALIFIÉE REQUISE avant toute utilisation avec de vrais élèves ou des mineurs.',
    literacyNotice:'Les activités CLASSIFY/UNDERSTAND conservent leur contenu validé en anglais pendant la révision d’une version française.',
  };
  return {
    na:'n.a.', singleLive:'Single live question', customActivity:'Custom activity', creating:'Creating classroom…', createFailed:'Classroom could not be created. Firebase may be unavailable in this environment.', created:'Classroom created. Share only the room code or join link; keep the teacher key private.', loadFailed:'Could not load classroom. Check code and teacher key.', refreshed:'Classroom refreshed.', actionFailed:'Teacher action failed.', activityLoaded:'Activity loaded. Existing anonymous aggregates remain in the room history.', joinCopied:'Student join link copied.', accessRemoved:'Teacher access removed from this browser session.',
    choose:'Choose what to teach', roomLabel:'Room label', roomPlaceholder:'Politics Year 10', ageBand:'Age band', ages:(range:string)=>`Ages ${range}`, activity:'Activity', literacyQuiz:'Political Literacy Quiz', guided:'Guided Lesson', custom:'Build my own / single question', lesson:'Lesson', pacing:'Pacing', teacherPaced:'Teacher-paced', studentPaced:'Student-paced', projectorDistribution:'Projector distribution', revealChoice:'Reveal when teacher chooses', liveChoice:'Show live while answers arrive', selectApproved:(count:number)=>`Select approved questions (${count} selected)`, startClass:'Start classroom', loadActivity:'Load this activity', openExisting:'Open existing classroom', roomCode:'Room code', teacherKey:'Teacher key', openClass:'Open classroom',
    classWord:'Class', joined:(n:number)=>`${n} joined`, active:'active', closed:'closed', onboarding:'Classroom onboarding', roomCodeCaps:'ROOM CODE', studentJoin:'Student join:', projector:'Projector:', copyStudent:'Copy student link', openProjector:'Open projector', endClass:'End classroom', reopenClass:'Reopen classroom', forgetKey:'Forget key', privacyIntro:'Students join without names or accounts. The teacher dashboard receives aggregate room distributions, not participant-to-answer records.',
    lessonGuide:(duration:string,age:string)=>`Lesson guide · ${duration} · ages ${age}`, lessonNotice:null as string | null, timeline:'Timeline and teacher guide', teacher:'Teacher', students:'Students', prompts:'Discussion prompts',
    liveClass:'Live classroom', chooseQuestion:'Choose a question to focus the room', responses:'responses', ofJoined:(n:number)=>`of ${n} joined`, correct:'correct', closeResponses:'Close responses', hideProjector:'Hide from projector', revealProjector:'Reveal to projector', nextQuestion:'Next question',
    launcher:'Question launcher', launcherHelp:'Launch any approved question in the selected activity. You can pause, discuss, switch activity or change direction at any time.', notAnswered:'not answered yet', responseCount:(n:number)=>`${n} responses`,
    classroomSummary:'Politangle Classroom Summary', questionsWithResponses:(answered:number,total:number)=>`${answered}/${total} questions with responses`, print:'Print / Save PDF', joinedMetric:'joined', responsesMetric:'responses', questionsAnswered:'questions answered', literacyCorrect:'literacy correct',
    axisKicker:'Aggregate 8-axis class map', axisTitle:'Where the room sits across political dimensions', axisHelp:'These are aggregate question distributions, not an individual profile and not a label for the class.',
    familyKicker:'Aggregate political-family compatibility', familyTitle:'Several families can fit the room at once', coverage:'coverage', familyHelp:'This is calculated from aggregate response distributions using the same academically reviewed family priors. It is not a vote prediction or a claim that the class “is” one ideology.',
    mostDivided:'Most divided', dividedTitle:'Where the room splits', consensus:'Strongest consensus', consensusTitle:'Where answers cluster',
    tensionTitle:'Largest aggregate mode tensions', construct:'Construct', tension:'Tension', tensionHelp:'ACT is stated intended choice, not observed behavior. Tension is a discussion signal, not hypocrisy.',
    literacy:'Political literacy', aggregateCorrect:(percent:number)=>`${percent}% aggregate correctness`, literacyHelp:'Use the lowest-performing concepts as follow-up teaching prompts. The teacher does not receive an individual score.',
    distributions:'Question distributions', distributionTitle:'The distribution matters more than the average.',
    privacyBoundary:'Privacy boundary', seeAggregate:'Teacher can see aggregate political distributions', seeWho:'Teacher can see who selected an answer', roster:'Student roster required', mapping:'Participant-to-answer mapping retained by classroom aggregate record', yes:'Yes', no:'No', legal:'REQUIRES QUALIFIED LEGAL REVIEW before real school/minor deployment.',
    literacyNotice:null as string | null,
  };
}
