'use client';

import Link from 'next/link';
import { InfoSection, InfoShell } from './InfoShell';
import { useLocale, type Locale } from './LocaleProvider';

export type InfoPageId = 'method' | 'validation' | 'privacy' | 'terms' | 'about' | 'contact' | 'imprint' | 'question-banks' | 'school-pilot';

type TableRow = readonly [string, string];
type SectionCopy = {
  title: string;
  paragraphs?: readonly string[];
  bullets?: readonly string[];
  callout?: string;
  status?: string;
  table?: readonly TableRow[];
  link?: { href: string; label: string };
};

type PageCopy = {
  eyebrow: string;
  title: string;
  intro: string;
  sections: readonly SectionCopy[];
};

const en: Record<InfoPageId, PageCopy> = {
  method: {
    eyebrow: 'METHOD',
    title: 'A map of patterns—not a verdict.',
    intro: 'Politangle separates political questions into distinct dimensions, then shows how your answers combine without forcing every position onto one left–right line.',
    sections: [
      { title: 'What Quick measures', paragraphs: ['Quick uses 26 statements selected across the assessment constructs. Each screen presents one statement and a five-point agreement scale from −2 to +2, plus “Not sure”. Not-sure answers are excluded rather than treated as neutral.'] },
      { title: 'The eight axes', bullets: ['Economic role', 'Ownership', 'Social values', 'Authority', 'Pluralism', 'World cooperation', 'Nationhood', 'Ecology'], paragraphs: ['Each axis stays visible so one position does not erase a different position elsewhere.'] },
      { title: 'Quick and Full', paragraphs: ['Quick 26 gives a first reading. Full brings the adult assessment to 42 questions in total by adding 16 more. Youth and Junior forms are separately versioned and must be validated for their intended age groups.'] },
      { title: 'Interpretation', paragraphs: ['Family matches describe resemblance to broad political traditions. They are not party recommendations, diagnoses or claims about identity. Read the detailed axes before any family label.'], callout: 'Politangle is an educational and exploratory tool. It does not tell you what to believe or how to vote.' },
    ],
  },
  validation: {
    eyebrow: 'VALIDATION & LIMITATIONS',
    title: 'Clear about what is proven—and what is not.',
    intro: 'The software and scoring logic are technically tested. Scientific, cognitive and classroom validation are separate gates and are not implied by a successful build.',
    sections: [
      { title: 'Current status', status: 'CANDIDATE ASSESSMENT', paragraphs: ['Automated tests cover scoring, question counts, result generation and classroom privacy boundaries. That shows implementation consistency, not psychometric validity.'] },
      { title: 'Not yet established', bullets: ['Representative population norms', 'Test–retest reliability', 'Construct equivalence across languages and age bands', 'Cognitive comprehension with intended Junior and Youth users', 'Predictive validity for voting or political behaviour'] },
      { title: 'Do not overread the result', paragraphs: ['Scores are indicators generated by the current model. A number such as 61/100 is not a scientific probability that somebody “is” an ideology. Historical reference figures illustrate traditions; they do not imply endorsement or equivalence.'] },
      { title: 'School release gate', callout: 'Real-school use with minors is not yet authorized. It requires qualified legal review, accessibility testing and age-appropriate content validation.' },
    ],
  },
  privacy: {
    eyebrow: 'PRIVACY',
    title: 'Collect less. Explain clearly. Protect political opinions.',
    intro: 'This page describes the current privacy design. Formal controller details and a legally reviewed notice still have to be completed before commercial or real-school release.',
    sections: [
      { title: 'Release status', callout: 'Preview notice: this is not the final legally reviewed privacy notice. Do not use the School pilot with real students until the release gate is complete.' },
      { title: 'Public assessment', paragraphs: ['No account is required. The public assessment currently keeps answers in the browser session to create the result. Restarting the assessment should remove that local assessment state.'] },
      { title: 'Classroom design', paragraphs: ['Students join with temporary identifiers and without a name, email address, username or roster. Teachers receive class totals and distributions—not a student-to-answer map and not individual political profiles.'] },
      { title: 'Required before launch', bullets: ['Controller identity and contact', 'Purposes and lawful bases', 'Hosting, recipients and international transfers', 'Retention and deletion periods', 'Data-subject rights and supervisory authority', 'School controller/processor roles and a DPIA decision'] },
    ],
  },
  terms: {
    eyebrow: 'TERMS',
    title: 'Pilot terms are not final yet.',
    intro: 'The public Quick assessment is currently offered for evaluation. School licensing and real-student use remain outside the authorized release scope.',
    sections: [
      { title: 'Current scope', paragraphs: ['Politangle is an educational self-exploration tool, not voting advice, professional advice or a guarantee of political classification accuracy.'] },
      { title: 'Before commercial release', callout: 'Final terms must identify the operator and accurately cover availability, permitted use, school responsibilities, pricing, cancellation, liability, intellectual property and governing law.' },
    ],
  },
  about: {
    eyebrow: 'ABOUT POLITANGLE',
    title: 'Political understanding without a single box.',
    intro: 'Politangle helps people explore political trade-offs, separate beliefs from knowledge and discuss disagreement without exposing individual classroom profiles.',
    sections: [
      { title: 'The problem', paragraphs: ['Political language often compresses complicated combinations of views into one label. That hides meaningful differences and can make disagreement more tribal than informative.'] },
      { title: 'The approach', paragraphs: ['Politangle keeps several dimensions visible, separates BELIEVE from CLASSIFY and UNDERSTAND, and treats uncertainty as a legitimate response rather than a scoring failure.'] },
      { title: 'Our standard', paragraphs: ['Neutrality is not established merely by displaying several viewpoints. Wording, scoring, language versions and classroom use must remain open to criticism, testing and revision.'] },
    ],
  },
  contact: {
    eyebrow: 'CONTACT',
    title: 'A verified contact channel is still a release dependency.',
    intro: 'Politangle.org is registered. A monitored project email address must be configured before this preview becomes a public launch.',
    sections: [
      { title: 'School pilots', paragraphs: ['Controlled school pilots will open only after privacy, legal and educational validation gates are satisfied. The current pilot route records interest; it does not authorize real-student use.'] },
      { title: 'Required setup', callout: 'Configure and verify a monitored Politangle address, then add the responsible operator and realistic response expectations here.' },
    ],
  },
  imprint: {
    eyebrow: 'IMPRINT',
    title: 'Provider information must be completed before release.',
    intro: 'Politangle.org is registered, but the legally responsible operator details were not supplied for this build preview.',
    sections: [
      { title: 'Release blocker', callout: 'Operator name, legal form, service address, email address, authorized representative and applicable registration/tax details must be inserted and legally reviewed before public commercial release.' },
    ],
  },
  'question-banks': {
    eyebrow: 'QUESTION-BANK VERSIONS',
    title: 'Different audiences. Separate, traceable forms.',
    intro: 'Changing language does not silently change country context, scoring constructs or the adult assessment. Material revisions receive their own version.',
    sections: [
      { title: 'Adult', table: [['Quick', '26 questions'], ['Full', '42 questions in total'], ['Status', 'Adult assessment remains its own form']] },
      { title: 'Youth 14–18', paragraphs: ['A candidate plain-language form covers the same underlying constructs. Its age suitability and construct equivalence still require validation.'] },
      { title: 'Junior 10–13', paragraphs: ['A separately versioned candidate bank uses shorter, simpler classroom prompts. It must be tested with intended users before real-school release.'] },
      { title: 'Languages', paragraphs: ['English, German, Spanish and French are language layers—not country profiles. Country-specific examples, elections, parties or campaign content would require separate future versions.'] },
    ],
  },
  'school-pilot': {
    eyebrow: 'CONTROLLED SCHOOL PILOT',
    title: 'Interested in testing Politangle with educators?',
    intro: 'This is an interest and design-partner pathway—not authorization to use the current candidate assessment with real students.',
    sections: [
      { title: 'Who it is for', paragraphs: ['Secondary-school educators, political-education specialists and researchers interested in anonymous classroom discussion, age-appropriate political literacy and aggregate-only insights.'] },
      { title: 'Current gate', callout: 'Real-student pilots require qualified legal review, safeguarding and accessibility checks, an approved school agreement and age-band content validation.' },
      { title: 'Preview the system', paragraphs: ['Educators may inspect the non-production interface and teacher materials without entering real student information.'], link: { href: '/school', label: 'Explore School mode →' } },
    ],
  },
};

const de: Record<InfoPageId, PageCopy> = {
  method: {
    eyebrow: 'METHODE', title: 'Mehrere Achsen statt einer politischen Schublade.',
    intro: 'Politangle betrachtet politische Einstellungen getrennt voneinander. So bleibt sichtbar, wo deine Ansichten zusammenpassen – und wo eben nicht.',
    sections: [
      { title: 'Was Quick erfasst', paragraphs: ['Quick besteht aus 26 Aussagen zu unterschiedlichen politischen Themen. Pro Bildschirm siehst du genau eine Aussage. Du antwortest auf einer Skala von −2 bis +2 oder wählst „Unsicher“. Unsichere Antworten fließen nicht einfach als Mitte in die Wertung ein.'] },
      { title: 'Die acht Achsen', bullets: ['Rolle des Staates', 'Eigentum', 'Gesellschaftliche Werte', 'Autorität', 'Pluralismus', 'Internationale Ordnung', 'Zugehörigkeit', 'Ökologie'], paragraphs: ['Jede Achse bleibt für sich sichtbar. Eine Position auf einem Thema soll deine Haltung zu einem anderen Thema nicht überdecken.'] },
      { title: 'Quick und Full', paragraphs: ['Quick 26 gibt dir einen ersten Überblick. Full ergänzt 16 weitere Fragen und kommt damit auf insgesamt 42. Youth und Junior sind eigene Fassungen und müssen für ihre Altersgruppen separat geprüft werden.'] },
      { title: 'So liest du das Ergebnis', paragraphs: ['Die Nähe zu politischen Traditionen beschreibt Ähnlichkeiten im Gesamtmuster. Sie ist keine Parteempfehlung, keine Diagnose und kein Etikett für deine Identität. Schau zuerst auf die einzelnen Achsen.'], callout: 'Politangle ist ein Bildungs- und Orientierungstool. Es sagt dir weder, was du glauben sollst, noch wen du wählen sollst.' },
    ],
  },
  validation: {
    eyebrow: 'VALIDIERUNG & GRENZEN', title: 'Klar benennen, was schon belegt ist – und was noch nicht.',
    intro: 'Software und Rechenlogik sind technisch getestet. Wissenschaftliche Validität, Verständlichkeit und Einsatz im Unterricht sind davon getrennte Prüfungen.',
    sections: [
      { title: 'Aktueller Stand', status: 'KANDIDATENFASSUNG', paragraphs: ['Automatisierte Tests prüfen unter anderem Wertung, Fragenanzahl, Ergebnislogik und Datenschutzgrenzen im Klassenraum. Das zeigt, dass die Implementierung konsistent arbeitet – nicht, dass das Instrument schon psychometrisch validiert ist.'] },
      { title: 'Noch nicht nachgewiesen', bullets: ['Repräsentative Vergleichswerte', 'Test-Retest-Zuverlässigkeit', 'Vergleichbarkeit der Konstrukte zwischen Sprachen und Altersgruppen', 'Verständlichkeit für die vorgesehenen Junior- und Youth-Gruppen', 'Vorhersagekraft für Wahlverhalten oder anderes politisches Verhalten'] },
      { title: 'Zahlen nicht überinterpretieren', paragraphs: ['Ein Wert wie 61/100 ist ein Modellwert. Er bedeutet nicht, dass jemand mit 61-prozentiger Wahrscheinlichkeit einer Ideologie „ist“. Historische Personen dienen nur als Orientierung für politische Traditionen.'] },
      { title: 'Freigabe für Schulen', callout: 'Der Einsatz mit echten Minderjährigen ist noch nicht freigegeben. Dafür braucht es qualifizierte Rechtsprüfung, Barrierefreiheitstests und eine altersgerechte inhaltliche Validierung.' },
    ],
  },
  privacy: {
    eyebrow: 'DATENSCHUTZ', title: 'Weniger sammeln. Klar erklären. Politische Ansichten besonders schützen.',
    intro: 'Hier steht, wie der aktuelle Produktentwurf mit Daten umgeht. Vor einem öffentlichen oder echten Schuleinsatz fehlen noch die endgültigen Verantwortlichenangaben und eine rechtlich geprüfte Datenschutzerklärung.',
    sections: [
      { title: 'Status dieser Seite', callout: 'Hinweis zur Vorschau: Das ist noch nicht die endgültige, rechtlich geprüfte Datenschutzerklärung. Nutze den Schulpilot nicht mit echten Schüler:innen, bevor die Freigaben abgeschlossen sind.' },
      { title: 'Öffentlicher Test', paragraphs: ['Für Quick brauchst du kein Konto. Deine Antworten bleiben derzeit in der Browser-Sitzung, damit das Ergebnis berechnet werden kann. Bei einem Neustart soll dieser lokale Teststand entfernt werden.'] },
      { title: 'Klassenraum', paragraphs: ['Schüler:innen treten mit temporären Kennungen bei – ohne Namen, E-Mail-Adresse, Benutzerkonto oder Klassenliste. Die Lehrkraft sieht Summen und Verteilungen der Klasse, aber keine Zuordnung von Person zu Antwort und kein individuelles politisches Profil.'] },
      { title: 'Vor dem Start noch erforderlich', bullets: ['Verantwortliche Stelle und Kontakt', 'Zwecke und Rechtsgrundlagen', 'Hosting, Empfänger und internationale Übermittlungen', 'Speicher- und Löschfristen', 'Betroffenenrechte und Aufsichtsbehörde', 'Rollen von Schule und Anbieter sowie Entscheidung zur Datenschutz-Folgenabschätzung'] },
    ],
  },
  terms: {
    eyebrow: 'NUTZUNGSBEDINGUNGEN', title: 'Die Bedingungen für den Pilot sind noch nicht final.',
    intro: 'Quick steht derzeit zur Erprobung bereit. Schullizenzen und der Einsatz mit echten Schüler:innen gehören noch nicht zum freigegebenen Umfang.',
    sections: [
      { title: 'Aktueller Rahmen', paragraphs: ['Politangle dient der politischen Bildung und Selbstreflexion. Es ist keine Wahlempfehlung, keine professionelle Beratung und keine Garantie für eine „richtige“ politische Einordnung.'] },
      { title: 'Vor einem kommerziellen Start', callout: 'Die finalen Bedingungen müssen den Betreiber eindeutig nennen und unter anderem Verfügbarkeit, erlaubte Nutzung, Pflichten von Schulen, Preise, Kündigung, Haftung, geistiges Eigentum und anwendbares Recht korrekt regeln.' },
    ],
  },
  about: {
    eyebrow: 'ÜBER POLITANGLE', title: 'Politik verstehen, ohne Menschen in eine Schublade zu stecken.',
    intro: 'Politangle macht politische Zielkonflikte sichtbar, trennt persönliche Überzeugungen von Wissen und ermöglicht Diskussionen, ohne individuelle Schülerprofile offenzulegen.',
    sections: [
      { title: 'Das Problem', paragraphs: ['Politische Begriffe pressen komplexe Kombinationen von Ansichten oft in ein einziges Etikett. Dabei verschwinden Unterschiede, die für ein echtes Verständnis wichtig wären.'] },
      { title: 'Unser Ansatz', paragraphs: ['Politangle zeigt mehrere Dimensionen nebeneinander. BELIEVE, CLASSIFY und UNDERSTAND bleiben getrennt. Auch Unsicherheit ist eine legitime Antwort und kein Fehler.'] },
      { title: 'Unser Anspruch', paragraphs: ['Neutralität entsteht nicht allein dadurch, dass mehrere Sichtweisen vorkommen. Fragen, Auswertung, Sprachfassungen und Unterrichtseinsatz müssen kritisierbar, testbar und veränderbar bleiben.'] },
    ],
  },
  contact: {
    eyebrow: 'KONTAKT', title: 'Ein verifizierter Kontaktkanal fehlt noch für den öffentlichen Start.',
    intro: 'Die Domain politangle.org ist registriert. Vor dem Launch muss noch eine betreute Projektadresse eingerichtet und geprüft werden.',
    sections: [
      { title: 'Schulpiloten', paragraphs: ['Kontrollierte Piloten mit Schulen starten erst, wenn Datenschutz, Recht und pädagogische Validierung freigegeben sind. Die aktuelle Pilotseite sammelt Interesse; sie erlaubt noch keinen Einsatz mit echten Schüler:innen.'] },
      { title: 'Noch einzurichten', callout: 'Eine betreute Politangle-E-Mail-Adresse verifizieren und anschließend den verantwortlichen Betreiber sowie realistische Antwortzeiten hier eintragen.' },
    ],
  },
  imprint: {
    eyebrow: 'IMPRESSUM', title: 'Die Anbieterangaben müssen vor dem Start vollständig sein.',
    intro: 'Politangle.org ist registriert. Für diese Vorschau liegen die rechtlich verantwortlichen Betreiberangaben jedoch noch nicht vollständig vor.',
    sections: [
      { title: 'Release-Blocker', callout: 'Name des Betreibers, Rechtsform, ladungsfähige Anschrift, E-Mail-Adresse, vertretungsberechtigte Person sowie gegebenenfalls Register- und Steuerangaben müssen ergänzt und rechtlich geprüft werden.' },
    ],
  },
  'question-banks': {
    eyebrow: 'FRAGENKATALOGE', title: 'Unterschiedliche Zielgruppen brauchen klar getrennte Fassungen.',
    intro: 'Eine andere Sprache ändert nicht heimlich Landeskontext, Messkonstrukte oder die Erwachsenenfassung. Größere Änderungen bekommen eine eigene Version.',
    sections: [
      { title: 'Erwachsene', table: [['Quick', '26 Fragen'], ['Full', '42 Fragen insgesamt'], ['Status', 'Eigenständige Erwachsenenfassung']] },
      { title: 'Youth 14–18', paragraphs: ['Eine Kandidatenfassung in zugänglicherer Sprache deckt dieselben Grundkonstrukte ab. Altersangemessenheit und Vergleichbarkeit müssen noch validiert werden.'] },
      { title: 'Junior 10–13', paragraphs: ['Eine separat versionierte Kandidatenfassung arbeitet mit kürzeren und einfacheren Unterrichtsimpulsen. Vor dem echten Schuleinsatz muss sie mit der Zielgruppe getestet werden.'] },
      { title: 'Sprachen', paragraphs: ['Englisch, Deutsch, Spanisch und Französisch sind Sprachfassungen – keine Länderprofile. Beispiele zu Parteien, Wahlen oder nationalem Kontext wären eigene spätere Ebenen.'] },
    ],
  },
  'school-pilot': {
    eyebrow: 'KONTROLLIERTER SCHULPILOT', title: 'Du willst Politangle mit Lehrkräften testen?',
    intro: 'Hier geht es um Interesse und Design-Partnerschaften. Die aktuelle Kandidatenfassung ist noch nicht für den Einsatz mit echten Schüler:innen freigegeben.',
    sections: [
      { title: 'Für wen gedacht', paragraphs: ['Für Lehrkräfte an weiterführenden Schulen, Fachleute der politischen Bildung und Forschungsteams, die an anonymen Klassendiskussionen, altersgerechter politischer Bildung und rein aggregierten Erkenntnissen interessiert sind.'] },
      { title: 'Aktuelle Freigabegrenze', callout: 'Ein Pilot mit echten Schüler:innen braucht qualifizierte Rechtsprüfung, Schutz- und Barrierefreiheitschecks, eine freigegebene Schulvereinbarung und validierte Inhalte für die jeweilige Altersgruppe.' },
      { title: 'System ansehen', paragraphs: ['Lehrkräfte können die nicht-produktive Oberfläche und Materialien prüfen, ohne echte Schülerdaten einzugeben.'], link: { href: '/school', label: 'School-Modus ansehen →' } },
    ],
  },
};

const es: Record<InfoPageId, PageCopy> = {
  method: {
    eyebrow: 'MÉTODO', title: 'Un mapa de matices, no una etiqueta.',
    intro: 'Politangle separa temas políticos distintos para que puedas ver tu combinación real de posiciones sin reducirla a una sola línea izquierda-derecha.',
    sections: [
      { title: 'Qué mide Quick', paragraphs: ['Quick plantea 26 afirmaciones sobre temas políticos diferentes. Ves una por pantalla y respondes de −2 a +2, con una opción aparte para “No estoy seguro”. La duda no se convierte automáticamente en una respuesta neutral.'] },
      { title: 'Los ocho ejes', bullets: ['Papel del Estado', 'Propiedad', 'Valores sociales', 'Autoridad', 'Pluralismo', 'Ámbito internacional', 'Pertenencia nacional', 'Ecología'], paragraphs: ['Cada eje se mantiene separado para que una postura no borre otra que tengas en un tema distinto.'] },
      { title: 'Quick y Full', paragraphs: ['Quick 26 te da una primera lectura. Full añade 16 preguntas y lleva el total a 42. Youth y Junior son versiones independientes que todavía deben validarse para sus edades.'] },
      { title: 'Cómo leer el resultado', paragraphs: ['La cercanía a una tradición política describe parecidos en el conjunto de tus respuestas. No es una recomendación de partido, un diagnóstico ni una identidad asignada. Mira primero los ejes.'], callout: 'Politangle es una herramienta educativa y de exploración. No te dice qué pensar ni a quién votar.' },
    ],
  },
  validation: {
    eyebrow: 'VALIDACIÓN & LÍMITES', title: 'Decir con claridad qué sabemos y qué todavía no.',
    intro: 'El software y la lógica de puntuación están probados técnicamente. La validación científica, cognitiva y escolar son pasos distintos.',
    sections: [
      { title: 'Situación actual', status: 'VERSIÓN CANDIDATA', paragraphs: ['Las pruebas automáticas cubren puntuación, número de preguntas, generación de resultados y límites de privacidad en el aula. Eso demuestra consistencia técnica, no validez psicométrica.'] },
      { title: 'Aún no establecido', bullets: ['Normas representativas de población', 'Fiabilidad test-retest', 'Equivalencia de constructos entre idiomas y edades', 'Comprensión cognitiva con usuarios Junior y Youth', 'Validez predictiva sobre voto o conducta política'] },
      { title: 'No conviertas el resultado en una certeza', paragraphs: ['Una puntuación como 61/100 es un indicador del modelo actual. No significa que alguien “sea” una ideología con una probabilidad del 61 %. Las figuras históricas sirven como puntos de referencia, no como equivalencias personales.'] },
      { title: 'Puerta de salida para escuelas', callout: 'El uso con menores reales todavía no está autorizado. Hace falta revisión jurídica cualificada, pruebas de accesibilidad y validación de contenidos por edad.' },
    ],
  },
  privacy: {
    eyebrow: 'PRIVACIDAD', title: 'Recoger menos. Explicar mejor. Proteger las opiniones políticas.',
    intro: 'Esta página resume cómo está diseñado ahora el producto. Antes de un lanzamiento comercial o escolar faltan los datos formales del responsable y un aviso de privacidad revisado jurídicamente.',
    sections: [
      { title: 'Estado de esta página', callout: 'Aviso de preview: todavía no es la política de privacidad definitiva. No uses el piloto escolar con alumnado real hasta que se cierre la revisión.' },
      { title: 'Test público', paragraphs: ['No necesitas una cuenta. Las respuestas se guardan actualmente en la sesión del navegador para poder calcular el resultado. Al reiniciar, ese estado local debería eliminarse.'] },
      { title: 'Diseño para el aula', paragraphs: ['El alumnado entra con identificadores temporales, sin nombre, correo, usuario ni lista de clase. El profesor ve totales y distribuciones del grupo, no quién respondió qué ni perfiles políticos individuales.'] },
      { title: 'Pendiente antes del lanzamiento', bullets: ['Identidad y contacto del responsable', 'Finalidades y bases jurídicas', 'Hosting, destinatarios y transferencias internacionales', 'Plazos de conservación y borrado', 'Derechos y autoridad de control', 'Roles escuela/proveedor y decisión sobre evaluación de impacto'] },
    ],
  },
  terms: {
    eyebrow: 'CONDICIONES', title: 'Las condiciones del piloto aún no son definitivas.',
    intro: 'Quick está disponible para evaluación. Las licencias escolares y el uso con alumnado real siguen fuera del alcance autorizado.',
    sections: [
      { title: 'Alcance actual', paragraphs: ['Politangle es una herramienta educativa de autoexploración. No ofrece consejo de voto, asesoramiento profesional ni garantiza una clasificación política exacta.'] },
      { title: 'Antes de un lanzamiento comercial', callout: 'Las condiciones finales deben identificar al operador y cubrir de forma correcta disponibilidad, usos permitidos, responsabilidades de los centros, precios, cancelación, responsabilidad, propiedad intelectual y ley aplicable.' },
    ],
  },
  about: {
    eyebrow: 'SOBRE POLITANGLE', title: 'Entender la política sin meter a nadie en una caja.',
    intro: 'Politangle ayuda a explorar dilemas políticos, separar creencias de conocimientos y hablar del desacuerdo sin exponer perfiles individuales en el aula.',
    sections: [
      { title: 'El problema', paragraphs: ['El lenguaje político suele reducir combinaciones complejas de ideas a una sola etiqueta. Así desaparecen diferencias importantes y el debate se vuelve más tribal que útil.'] },
      { title: 'El enfoque', paragraphs: ['Politangle mantiene varias dimensiones visibles, separa BELIEVE de CLASSIFY y UNDERSTAND y trata la incertidumbre como una respuesta válida, no como un fallo.'] },
      { title: 'Nuestro criterio', paragraphs: ['No basta con mostrar varios puntos de vista para afirmar neutralidad. Preguntas, puntuación, versiones lingüísticas y uso escolar deben seguir abiertos a crítica, pruebas y revisión.'] },
    ],
  },
  contact: {
    eyebrow: 'CONTACTO', title: 'Todavía falta un canal de contacto verificado para el lanzamiento.',
    intro: 'politangle.org ya está registrado. Antes de publicar el proyecto debe existir una dirección de correo supervisada y comprobada.',
    sections: [
      { title: 'Pilotos escolares', paragraphs: ['Los pilotos controlados empezarán solo cuando se cierren las revisiones de privacidad, legal y educativa. La ruta actual registra interés; no autoriza el uso con alumnado real.'] },
      { title: 'Configuración pendiente', callout: 'Crear y verificar una dirección de Politangle supervisada y después añadir aquí el operador responsable y expectativas realistas de respuesta.' },
    ],
  },
  imprint: {
    eyebrow: 'AVISO LEGAL', title: 'Los datos del proveedor deben estar completos antes del lanzamiento.',
    intro: 'politangle.org está registrado, pero los datos del operador legalmente responsable todavía no se han facilitado para esta preview.',
    sections: [
      { title: 'Bloqueo de lanzamiento', callout: 'Nombre del operador, forma jurídica, domicilio de notificaciones, correo, representante autorizado y, cuando corresponda, datos registrales y fiscales deben añadirse y revisarse jurídicamente antes de un lanzamiento comercial.' },
    ],
  },
  'question-banks': {
    eyebrow: 'VERSIONES DE PREGUNTAS', title: 'Públicos distintos. Versiones separadas y trazables.',
    intro: 'Cambiar de idioma no cambia a escondidas el contexto nacional, los constructos de puntuación ni la evaluación para adultos. Los cambios importantes reciben una versión propia.',
    sections: [
      { title: 'Adultos', table: [['Quick', '26 preguntas'], ['Full', '42 preguntas en total'], ['Estado', 'La evaluación adulta sigue siendo una versión propia']] },
      { title: 'Youth 14–18', paragraphs: ['Una versión candidata en lenguaje más accesible cubre los mismos constructos de fondo. La adecuación por edad y la equivalencia todavía deben validarse.'] },
      { title: 'Junior 10–13', paragraphs: ['Una versión candidata independiente utiliza preguntas más breves y sencillas para el aula. Debe probarse con su público antes de utilizarse en centros reales.'] },
      { title: 'Idiomas', paragraphs: ['Inglés, alemán, español y francés son capas lingüísticas, no perfiles nacionales. Ejemplos sobre partidos, elecciones o contexto local necesitarían versiones futuras separadas.'] },
    ],
  },
  'school-pilot': {
    eyebrow: 'PILOTO ESCOLAR CONTROLADO', title: '¿Te interesa probar Politangle con docentes?',
    intro: 'Esta vía sirve para mostrar interés y colaborar en el diseño. No autoriza a usar la evaluación candidata actual con alumnado real.',
    sections: [
      { title: 'A quién va dirigido', paragraphs: ['A docentes de secundaria, especialistas en educación política y equipos de investigación interesados en debate anónimo, alfabetización política por edades y datos exclusivamente agregados.'] },
      { title: 'Límite actual', callout: 'Un piloto con alumnado real exige revisión jurídica cualificada, salvaguarda y accesibilidad, un acuerdo escolar aprobado y validación de contenidos por edad.' },
      { title: 'Ver el sistema', paragraphs: ['Los docentes pueden revisar la interfaz no productiva y los materiales sin introducir datos de alumnado real.'], link: { href: '/school', label: 'Ver el modo School →' } },
    ],
  },
};

const fr: Record<InfoPageId, PageCopy> = {
  method: {
    eyebrow: 'MÉTHODE', title: 'Plusieurs axes pour garder les nuances.',
    intro: 'Politangle sépare les grands sujets politiques afin de montrer ta combinaison réelle de positions sans tout ramener à un seul axe gauche-droite.',
    sections: [
      { title: 'Ce que mesure Quick', paragraphs: ['Quick te propose 26 affirmations sur des sujets politiques différents. Une seule apparaît à l’écran. Tu réponds de −2 à +2, avec une option « Je ne sais pas » à part. Le doute n’est pas transformé artificiellement en réponse neutre.'] },
      { title: 'Les huit axes', bullets: ['Rôle de l’État', 'Propriété', 'Valeurs sociales', 'Autorité', 'Pluralisme', 'Rapport à l’international', 'Appartenance nationale', 'Écologie'], paragraphs: ['Chaque axe reste visible séparément, pour qu’une position n’efface pas ce que tu penses sur un autre sujet.'] },
      { title: 'Quick et Full', paragraphs: ['Quick 26 donne une première lecture. Full ajoute 16 questions, soit 42 au total. Youth et Junior sont des versions distinctes qui doivent encore être validées pour leurs tranches d’âge.'] },
      { title: 'Lire ton résultat', paragraphs: ['La proximité avec une tradition politique décrit des ressemblances dans l’ensemble de tes réponses. Ce n’est ni une recommandation de parti, ni un diagnostic, ni une identité qu’on te colle. Commence par regarder les axes.'], callout: 'Politangle est un outil éducatif et exploratoire. Il ne te dit ni quoi penser ni pour qui voter.' },
    ],
  },
  validation: {
    eyebrow: 'VALIDATION & LIMITES', title: 'Dire clairement ce qui est établi – et ce qui ne l’est pas encore.',
    intro: 'Le logiciel et la logique de calcul sont testés techniquement. La validation scientifique, cognitive et scolaire correspond à d’autres étapes.',
    sections: [
      { title: 'État actuel', status: 'VERSION CANDIDATE', paragraphs: ['Les tests automatiques couvrent le calcul, le nombre de questions, la génération des résultats et les limites de confidentialité en classe. Cela montre une cohérence technique, pas une validité psychométrique.'] },
      { title: 'Pas encore établi', bullets: ['Normes représentatives de population', 'Fiabilité test-retest', 'Équivalence des construits entre langues et tranches d’âge', 'Compréhension par les publics Junior et Youth', 'Validité prédictive du vote ou d’autres comportements politiques'] },
      { title: 'Ne transforme pas le score en certitude', paragraphs: ['Un résultat comme 61/100 est un indicateur du modèle actuel. Il ne signifie pas qu’une personne « est » une idéologie avec une probabilité de 61 %. Les figures historiques servent de repères, pas d’équivalents personnels.'] },
      { title: 'Feu vert pour les écoles', callout: 'L’utilisation avec de vrais mineurs n’est pas encore autorisée. Elle exige une revue juridique qualifiée, des tests d’accessibilité et une validation des contenus par tranche d’âge.' },
    ],
  },
  privacy: {
    eyebrow: 'VIE PRIVÉE', title: 'Collecter moins. Expliquer clairement. Protéger les opinions politiques.',
    intro: 'Cette page décrit la conception actuelle du produit. Avant un lancement commercial ou scolaire, il manque encore l’identité formelle du responsable et une notice de confidentialité revue juridiquement.',
    sections: [
      { title: 'État de cette page', callout: 'Note de preview : ce n’est pas encore la notice de confidentialité définitive. N’utilise pas le pilote scolaire avec de vrais élèves tant que les validations ne sont pas terminées.' },
      { title: 'Test public', paragraphs: ['Aucun compte n’est nécessaire. Les réponses restent actuellement dans la session du navigateur pour calculer le résultat. Un redémarrage doit pouvoir supprimer cet état local.'] },
      { title: 'Conception pour la classe', paragraphs: ['Les élèves rejoignent la séance avec des identifiants temporaires, sans nom, e-mail, compte ou liste de classe. L’enseignant voit les totaux et répartitions du groupe, jamais qui a répondu quoi ni un profil politique individuel.'] },
      { title: 'À compléter avant le lancement', bullets: ['Identité et contact du responsable', 'Finalités et bases juridiques', 'Hébergement, destinataires et transferts internationaux', 'Durées de conservation et suppression', 'Droits des personnes et autorité de contrôle', 'Rôles école/fournisseur et décision concernant une analyse d’impact'] },
    ],
  },
  terms: {
    eyebrow: 'CONDITIONS', title: 'Les conditions du pilote ne sont pas encore définitives.',
    intro: 'Quick est actuellement proposé pour évaluation. Les licences scolaires et l’utilisation avec de vrais élèves restent hors du périmètre autorisé.',
    sections: [
      { title: 'Cadre actuel', paragraphs: ['Politangle est un outil éducatif d’exploration personnelle. Ce n’est ni un conseil de vote, ni un conseil professionnel, ni une garantie de classification politique exacte.'] },
      { title: 'Avant un lancement commercial', callout: 'Les conditions finales doivent identifier l’opérateur et couvrir correctement la disponibilité, les usages autorisés, les responsabilités des écoles, les prix, l’annulation, la responsabilité, la propriété intellectuelle et le droit applicable.' },
    ],
  },
  about: {
    eyebrow: 'À PROPOS DE POLITANGLE', title: 'Comprendre la politique sans enfermer les gens dans une case.',
    intro: 'Politangle aide à explorer les arbitrages politiques, à distinguer convictions et connaissances et à discuter des désaccords sans exposer les profils individuels en classe.',
    sections: [
      { title: 'Le problème', paragraphs: ['Le vocabulaire politique réduit souvent des combinaisons complexes d’idées à une seule étiquette. Des différences importantes disparaissent alors, et le débat devient plus tribal qu’instructif.'] },
      { title: 'L’approche', paragraphs: ['Politangle garde plusieurs dimensions visibles, sépare BELIEVE de CLASSIFY et UNDERSTAND et considère l’incertitude comme une réponse valable, pas comme un échec.'] },
      { title: 'Notre exigence', paragraphs: ['Afficher plusieurs points de vue ne suffit pas à prouver la neutralité. Les questions, le calcul, les versions linguistiques et l’usage en classe doivent rester critiquables, testables et révisables.'] },
    ],
  },
  contact: {
    eyebrow: 'CONTACT', title: 'Il manque encore un canal de contact vérifié pour le lancement public.',
    intro: 'politangle.org est enregistré. Avant le lancement, une adresse de projet suivie et vérifiée doit être mise en place.',
    sections: [
      { title: 'Pilotes scolaires', paragraphs: ['Les pilotes encadrés ne commenceront qu’après validation des volets vie privée, juridique et pédagogique. La page actuelle recueille de l’intérêt ; elle n’autorise pas l’utilisation avec de vrais élèves.'] },
      { title: 'Configuration à terminer', callout: 'Créer et vérifier une adresse Politangle réellement suivie, puis ajouter ici l’opérateur responsable et des délais de réponse réalistes.' },
    ],
  },
  imprint: {
    eyebrow: 'MENTIONS LÉGALES', title: 'Les informations du fournisseur doivent être complètes avant le lancement.',
    intro: 'politangle.org est enregistré, mais l’identité complète de l’opérateur légalement responsable n’a pas encore été fournie pour cette preview.',
    sections: [
      { title: 'Blocage avant lancement', callout: 'Nom de l’opérateur, forme juridique, adresse de service, e-mail, représentant autorisé et, le cas échéant, informations d’enregistrement et fiscales doivent être ajoutés puis vérifiés juridiquement avant tout lancement commercial.' },
    ],
  },
  'question-banks': {
    eyebrow: 'VERSIONS DES QUESTIONS', title: 'Des publics différents, des versions séparées et traçables.',
    intro: 'Changer de langue ne modifie pas en douce le contexte national, les construits de mesure ou l’évaluation adulte. Toute évolution importante reçoit sa propre version.',
    sections: [
      { title: 'Adultes', table: [['Quick', '26 questions'], ['Full', '42 questions au total'], ['État', 'L’évaluation adulte reste une version distincte']] },
      { title: 'Youth 14–18', paragraphs: ['Une version candidate au langage plus accessible couvre les mêmes construits de fond. L’adéquation à l’âge et l’équivalence doivent encore être validées.'] },
      { title: 'Junior 10–13', paragraphs: ['Une version candidate distincte utilise des formulations plus courtes et plus simples pour la classe. Elle doit être testée avec son public avant toute utilisation réelle en établissement.'] },
      { title: 'Langues', paragraphs: ['Anglais, allemand, espagnol et français sont des couches linguistiques, pas des profils nationaux. Des exemples liés aux partis, élections ou contextes locaux nécessiteraient des versions futures séparées.'] },
    ],
  },
  'school-pilot': {
    eyebrow: 'PILOTE SCOLAIRE ENCADRÉ', title: 'Tu veux tester Politangle avec des enseignants ?',
    intro: 'Cette voie sert à manifester ton intérêt et à participer à la conception. Elle n’autorise pas l’utilisation de l’évaluation candidate actuelle avec de vrais élèves.',
    sections: [
      { title: 'Pour qui', paragraphs: ['Pour les enseignants du secondaire, spécialistes de l’éducation politique et équipes de recherche intéressés par le débat anonyme, la culture politique adaptée à l’âge et des données uniquement agrégées.'] },
      { title: 'Limite actuelle', callout: 'Un pilote avec de vrais élèves exige une revue juridique qualifiée, des contrôles de protection et d’accessibilité, un accord scolaire approuvé et une validation des contenus par âge.' },
      { title: 'Voir le système', paragraphs: ['Les enseignants peuvent examiner l’interface non productive et les supports sans saisir de données de vrais élèves.'], link: { href: '/school', label: 'Voir le mode School →' } },
    ],
  },
};

const copy: Record<Locale, Record<InfoPageId, PageCopy>> = { en, de, es, fr };

export default function LocalizedInfoPage({ page }: { page: InfoPageId }) {
  const { locale } = useLocale();
  const c = copy[locale][page];

  return (
    <InfoShell eyebrow={c.eyebrow} title={c.title} intro={c.intro}>
      {c.sections.map((section) => (
        <InfoSection key={section.title} title={section.title}>
          {section.status && <span className="info-status">{section.status}</span>}
          {section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
          {section.bullets && <ul>{section.bullets.map((item) => <li key={item}>{item}</li>)}</ul>}
          {section.table && <table className="info-table"><tbody>{section.table.map(([label, value]) => <tr key={label}><th>{label}</th><td>{value}</td></tr>)}</tbody></table>}
          {section.callout && <p className="info-callout"><strong>{section.callout}</strong></p>}
          {section.link && <p><Link href={section.link.href}>{section.link.label}</Link></p>}
        </InfoSection>
      ))}
    </InfoShell>
  );
}
