'use client';
import { LanguageSelector, useLocale } from './LocaleProvider';
import { translate } from './translations';

const Arrow = () => <span aria-hidden="true">→</span>;
const Mark = () => <span className="p-mark" aria-hidden="true"><svg viewBox="0 0 36 36" focusable="false"><polygon className="p-mark-ring p-mark-ring-outer" points="18,6.5 26.1,9.9 29.5,18 26.1,26.1 18,29.5 9.9,26.1 6.5,18 9.9,9.9"/><polygon className="p-mark-ring p-mark-ring-inner" points="18,11.8 22.4,13.6 24.2,18 22.4,22.4 18,24.2 13.6,22.4 11.8,18 13.6,13.6"/><line x1="18" y1="18" x2="18" y2="6.5"/><line x1="18" y1="18" x2="26.1" y2="9.9"/><line x1="18" y1="18" x2="29.5" y2="18"/><line x1="18" y1="18" x2="26.1" y2="26.1"/><line x1="18" y1="18" x2="18" y2="29.5"/><line x1="18" y1="18" x2="9.9" y2="26.1"/><line x1="18" y1="18" x2="6.5" y2="18"/><line x1="18" y1="18" x2="9.9" y2="9.9"/><circle cx="18" cy="18" r="1.4"/></svg></span>;

function ShapePreview({ axes }: { axes: readonly (readonly [string, number])[] }) {
 const cx = 180;
 const cy = 160;
 const maxRadius = 108;
 const polar = (radius:number,index:number) => {
  const angle = (-90 + index * 45) * Math.PI / 180;
  return { x: cx + Math.cos(angle) * radius, y: cy + Math.sin(angle) * radius };
 };
 const points = (level:number) => axes.map((_,index) => { const p = polar(maxRadius * (level / 100),index); return `${p.x},${p.y}`; }).join(' ');
 const profile = axes.map(([,score],index) => { const p = polar(maxRadius * (score / 100),index); return `${p.x},${p.y}`; }).join(' ');
 return <svg className="p-shape-preview" viewBox="0 0 360 320" role="img" aria-label="Example eight-axis Politangle shape">
  {[25,50,75,100].map((level) => <polygon className="p-shape-ring" key={level} points={points(level)}/>)}
  {axes.map((_,index) => { const p = polar(maxRadius,index); return <line className="p-shape-spoke" key={`spoke-${index}`} x1={cx} y1={cy} x2={p.x} y2={p.y}/>; })}
  <polygon className="p-shape-area" points={profile}/>
  {axes.map(([,score],index) => { const p = polar(maxRadius * (score / 100),index); return <circle className="p-shape-dot" key={`dot-${index}`} cx={p.x} cy={p.y} r="4"/>; })}
  {axes.map(([label],index) => { const p = polar(132,index); const anchor = p.x > cx + 14 ? 'start' : p.x < cx - 14 ? 'end' : 'middle'; return <text className="p-shape-label" key={label} x={p.x} y={p.y} textAnchor={anchor} dominantBaseline="middle">{label}</text>; })}
 </svg>;
}

export default function Home() {
 const { locale } = useLocale();
 const t = (en:string,de:string) => translate(locale, en, de);
 const dimensions = [[t('Economy','Wirtschaft'),t('Public provision ↔ Market freedom','Öffentliche Vorsorge ↔ Marktfreiheit'),'68'],[t('Society','Gesellschaft'),t('Social change ↔ Continuity','Sozialer Wandel ↔ Kontinuität'),'43'],[t('Power','Macht'),t('Personal freedom ↔ Authority','Persönliche Freiheit ↔ Autorität'),'77'],[t('World','Welt'),t('Cooperation ↔ Sovereignty','Zusammenarbeit ↔ Souveränität'),'55']];
 const heroShapeAxes = [[t('Economy','Wirtschaft'),68],[t('Ownership','Eigentum'),72],[t('Social values','Gesellschaft'),43],[t('Authority','Autorität'),31],[t('Pluralism','Pluralismus'),80],[t('World','Welt'),55],[t('Nationhood','Nation'),39],[t('Ecology','Ökologie'),82]] as const;
 return <main className="home">
  <header className="p-nav"><a className="p-brand" href="/"><Mark/><span>Politangle</span></a><nav><a href="#method">{t('How it works','So funktioniert es')}</a><a href="#result">{t('Your result','Ihr Ergebnis')}</a><a href="#learn">{t('Knowledge quizzes','Wissensquiz')}</a><a className="p-school-nav" href="#schools"><span className="p-school-burst" aria-hidden="true">✦</span>{t('For schools','Für Schulen')}</a></nav><div className="p-nav-actions"><LanguageSelector/><a className="p-button compact" href="/quiz">{t('Take Quick','Quick starten')} <Arrow/></a></div></header>

  <section className="p-hero"><div className="p-orbit one"/><div className="p-orbit two"/><div className="p-shell p-hero-grid">
   <div className="p-hero-copy"><p className="p-kicker">{t('POLITICS WITHOUT THE BOXES','POLITIK OHNE SCHUBLADEN')}</p><h1>{t('See your politics from every angle.','Sehen Sie Ihre Politik aus jedem Blickwinkel.')}</h1><p className="p-lead">{t('26 questions reveal how your views spread across eight political dimensions—without squeezing you into a single left–right label.','26 Fragen zeigen, wie sich Ihre Ansichten über acht politische Dimensionen verteilen – ohne Sie auf ein einziges Links-rechts-Etikett zu reduzieren.')}</p><div className="p-actions"><a className="p-button light" href="/quiz">{t('Start the 3-minute Quick','3-Minuten-Quick starten')} <Arrow/></a><a className="p-text-link light" href="#method">{t('See how it works','So funktioniert es')}</a></div><div className="p-trust"><span>✓ {t('Free','Kostenlos')}</span><span>✓ {t('No account','Kein Konto')}</span><span>✓ {t('Private by default','Standardmäßig privat')}</span></div></div>
   <div className="p-hero-stage"><div className="p-hero-shape-hook"><ShapePreview axes={heroShapeAxes}/></div></div>
  </div></section>

  <section className="p-proof p-shell"><div><small>{t('QUICK','QUICK')}</small><strong>26</strong><span>{t('questions to start','Fragen zum Start')}</span></div><div><small>{t('YOUR MAP','IHRE KARTE')}</small><strong>8</strong><span>{t('political dimensions','politische Dimensionen')}</span></div><div><small>{t('FULL','FULL')}</small><strong>+16</strong><span>{t('questions for more depth','Fragen für mehr Tiefe')}</span></div><div><small>{t('PRIVATE','PRIVAT')}</small><strong>0</strong><span>{t('accounts required','Konten erforderlich')}</span></div></section>

  <section className="p-section p-shell" id="method"><div className="p-section-head"><div><p className="p-kicker">{t('HOW IT WORKS','SO FUNKTIONIERT ES')}</p><h2>{t('One answer at a time. A much richer picture at the end.','Eine Antwort nach der anderen. Am Ende ein viel differenzierteres Bild.')}</h2></div><p>{t('Quick gives you the first map in 26 questions. Full adds 16 more to compare your principles, instincts and practical choices across the same political themes.','Quick erstellt Ihre erste Karte mit 26 Fragen. Full ergänzt 16 weitere, um Prinzipien, Instinkte und praktische Entscheidungen zu denselben politischen Themen zu vergleichen.')}</p></div><div className="p-steps"><article><span>01</span><h3>{t('Answer','Antworten')}</h3><p>{t('Respond to one clear statement at a time on a simple agreement scale.','Beantworten Sie jeweils eine klare Aussage auf einer einfachen Zustimmungsskala.')}</p></article><article><span>02</span><h3>{t('See the shape','Form erkennen')}</h3><p>{t('Your answers become an eight-sided political map instead of one left–right score.','Ihre Antworten werden zu einer achtseitigen politischen Karte statt zu einem einzigen Links-rechts-Wert.')}</p></article><article><span>03</span><h3>{t('Find your political home','Politische Heimat finden')}</h3><p>{t('See which political traditions resemble your overall pattern—and where you depart from them.','Sehen Sie, welche politischen Traditionen Ihrem Gesamtmuster ähneln – und wo Sie davon abweichen.')}</p></article></div></section>

  <section className="p-section p-shell" id="learn"><div className="p-section-head"><div><p className="p-kicker">{t('OPTIONAL KNOWLEDGE QUIZZES','OPTIONALE WISSENSQUIZZE')}</p><h2>{t('Test what you know, separately from what you believe.','Testen Sie Ihr Wissen getrennt von Ihren Überzeugungen.')}</h2></div><p>{t('Two quick challenges. CLASSIFY asks whether you can recognise a political tradition from its ideas. UNDERSTAND asks whether you can tell apart political ideas that people often confuse.','Zwei kurze Herausforderungen. CLASSIFY prüft, ob Sie eine politische Richtung an ihren Ideen erkennen. UNDERSTAND prüft, ob Sie politische Ideen auseinanderhalten können, die oft verwechselt werden.')}</p></div><div className="p-steps"><article><span>01</span><h3>CLASSIFY</h3><p><strong>{t('Can you spot the politics without the label?','Erkennen Sie die politische Richtung ohne Etikett?')}</strong><br/>{t('Read what a party or movement stands for and choose the political tradition that fits best.','Lesen Sie, wofür eine Partei oder Bewegung steht, und wählen Sie die politische Richtung, die am besten passt.')}</p><a className="p-text-link" href="/classify">{t('Take CLASSIFY','CLASSIFY starten')} <Arrow/></a></article><article><span>02</span><h3>UNDERSTAND</h3><p><strong>{t('Can you tell similar political ideas apart?','Können Sie ähnliche politische Ideen auseinanderhalten?')}</strong><br/>{t('Test the differences people often mix up and see where your political knowledge is strongest.','Testen Sie Unterschiede, die häufig verwechselt werden, und sehen Sie, wo Ihr politisches Wissen am stärksten ist.')}</p><a className="p-text-link" href="/understand">{t('Take UNDERSTAND','UNDERSTAND starten')} <Arrow/></a></article></div></section>

  <section className="p-dark-section" id="result"><div className="p-shell p-result-grid"><div><p className="p-kicker light">{t('YOUR POLITANGLE','IHR POLITANGLE')}</p><h2>{t('A political home, without flattening the details.','Eine politische Heimat, ohne die Details glattzubügeln.')}</h2><p className="p-section-copy">{t('Politangle shows your closest political traditions, then keeps the disagreements visible. You may fit one family overall while taking very different positions on individual issues.','Politangle zeigt Ihre nächstliegenden politischen Traditionen und lässt die Abweichungen sichtbar. Insgesamt können Sie zu einer Familie passen und bei einzelnen Themen dennoch ganz anders liegen.')}</p><a className="p-button light" href="/quiz">{t('Discover your angle','Perspektive entdecken')} <Arrow/></a></div><div className="p-dimension-card"><div className="p-card-top"><span>{t('POLITICAL SHAPE','POLITISCHE FORM')}</span><small>{t('Example','Beispiel')}</small></div>{dimensions.map(([name,detail,score])=><div className="p-dimension" key={name}><div><strong>{name}</strong><small>{detail}</small><b>{score}</b></div><i><em style={{width:`${score}%`}}/></i></div>)}<p>{t('Eight dimensions. One pattern that is yours.','Acht Dimensionen. Ein Muster, das Ihnen gehört.')}</p></div></div></section>

  <section className="p-section p-shell" id="schools"><div className="p-school-card"><div><p className="p-kicker p-school-kicker"><span aria-hidden="true">✦</span>{t('FOR SCHOOLS','FÜR SCHULEN')}</p><h2>{t('Teach political thinking without exposing individual beliefs.','Politisches Denken vermitteln, ohne individuelle Überzeugungen offenzulegen.')}</h2><p>{t('Anonymous classroom participation, live group distributions, guided lessons and classroom reports—while individual students’ answers stay private.','Anonyme Teilnahme, Live-Verteilungen der Gruppe, geführte Unterrichtseinheiten und Klassenberichte – während die Antworten einzelner Schülerinnen und Schüler privat bleiben.')}</p><div className="p-actions"><a className="p-button p-school-cta" href="/school">{t('Explore School mode','Schulmodus ansehen')} <Arrow/></a><a className="p-text-link" href="/school/private">{t('Private student mode','Privater Schülermodus')}</a></div></div><div className="p-school-proof"><div><span>01</span><strong>{t('Anonymous by design','Anonym konzipiert')}</strong><small>{t('Join with a temporary room code.','Teilnahme mit temporärem Raumcode.')}</small></div><div><span>02</span><strong>{t('Built for discussion','Für Diskussionen gebaut')}</strong><small>{t('Live distributions reveal agreement and disagreement.','Live-Verteilungen zeigen Zustimmung und Unterschiede.')}</small></div><div><span>03</span><strong>{t('Flexible for teachers','Flexibel für Lehrkräfte')}</strong><small>{t('Use belief mapping, knowledge quizzes or guided discussion activities.','Nutzen Sie Meinungsprofile, Wissensquizze oder geführte Diskussionsformate.')}</small></div></div></div></section>

  <section className="p-final"><div className="p-shell"><p className="p-kicker light">{t('START WITH CURIOSITY','MIT NEUGIER STARTEN')}</p><h2>{t('26 questions. More than one angle.','26 Fragen. Mehr als ein Blickwinkel.')}</h2><a className="p-button light" href="/quiz">{t('Take Politangle Quick','Politangle Quick starten')} <Arrow/></a></div></section>
  <footer className="p-footer p-shell"><a className="p-brand" href="/"><Mark/><span>Politangle</span></a><div className="p-footer-links"><a href="#method">{t('Method','Methode')}</a><a href="#learn">{t('Knowledge quizzes','Wissensquiz')}</a><a className="p-footer-school" href="/school"><span aria-hidden="true">✦</span>{t('For schools','Für Schulen')}</a></div><small>© 2026 Politangle</small></footer>
 </main>;
}
