'use client';
import { LanguageSelector, useLocale } from './LocaleProvider';
import { translate } from './translations';

const Arrow = () => <span aria-hidden="true">→</span>;
const Mark = () => <span className="p-mark" aria-hidden="true"><i/><i/><i/></span>;

function ShapePreview({ axes }: { axes: readonly (readonly [string, number])[] }) {
 const cx = 180;
 const cy = 160;
 const maxRadius = 108;
 const polar = (radius:number,index:number) => {
  const angle = (-90 + index * 45) * Math.PI / 180;
  return { x: cx + Math.cos(angle) * radius, y: cy + Math.sin(angle) * radius };
 };
 const points = (level:number) => axes.map((_,index) => { const p = polar(maxRadius * (level / 100),index); return `${p.x},${p.y}`; }).join(' ');
 const profile = axes.map(([,score],index) => { const p = polar(maxRadius * (score / 100),index); return `${p.x},${p.y}`; }).join(' ');
 return <svg className="p-shape-preview" viewBox="0 0 360 320" role="img" aria-label="Example eight-axis Politangle shape">
  {[25,50,75,100].map((level) => <polygon className="p-shape-ring" key={level} points={points(level)}/>)}
  {axes.map((_,index) => { const p = polar(maxRadius,index); return <line className="p-shape-spoke" key={`spoke-${index}`} x1={cx} y1={cy} x2={p.x} y2={p.y}/>; })}
  <polygon className="p-shape-area" points={profile}/>
  {axes.map(([,score],index) => { const p = polar(maxRadius * (score / 100),index); return <circle className="p-shape-dot" key={`dot-${index}`} cx={p.x} cy={p.y} r="4"/>; })}
  {axes.map(([label],index) => { const p = polar(132,index); const anchor = p.x > cx + 14 ? 'start' : p.x < cx - 14 ? 'end' : 'middle'; return <text className="p-shape-label" key={label} x={p.x} y={p.y} textAnchor={anchor} dominantBaseline="middle">{label}</text>; })}
 </svg>;
}

export default function Home() {
 const { locale } = useLocale();
 const t = (en:string,de:string) => translate(locale, en, de);
 const dimensions = [[t('Economy','Wirtschaft'),t('Public provision ↔ Market freedom','Öffentliche Vorsorge ↔ Marktfreiheit'),'68'],[t('Society','Gesellschaft'),t('Social change ↔ Continuity','Sozialer Wandel ↔ Kontinuität'),'43'],[t('Power','Macht'),t('Personal freedom ↔ Authority','Persönliche Freiheit ↔ Autorität'),'77'],[t('World','Welt'),t('Cooperation ↔ Sovereignty','Zusammenarbeit ↔ Souveränität'),'55']];
 const heroShapeAxes = [[t('Economy','Wirtschaft'),68],[t('Ownership','Eigentum'),72],[t('Social values','Gesellschaft'),43],[t('Authority','Autorität'),31],[t('Pluralism','Pluralismus'),80],[t('World','Welt'),55],[t('Nationhood','Nation'),39],[t('Ecology','Ökologie'),82]] as const;
 return <main className="home">
  <header className="p-nav"><a className="p-brand" href="/"><Mark/><span>Politangle</span></a><nav><a href="#method">{t('Method','Methode')}</a><a href="#learn">{t('Knowledge quizzes','Wissensquiz')}</a><a href="#schools">{t('For schools','Für Schulen')}</a><a href="/about">{t('About','Über uns')}</a></nav><div className="p-nav-actions"><LanguageSelector/><a className="p-button compact" href="/quiz">{t('Start Quick','Quick starten')} <Arrow/></a></div></header>

  <section className="p-hero"><div className="p-orbit one"/><div className="p-orbit two"/><div className="p-shell p-hero-grid">
   <div className="p-hero-copy"><p className="p-kicker">{t('POLITICS WITHOUT THE BOXES','POLITIK OHNE SCHUBLADEN')}</p><h1>{t('Your politics are not a line.','Ihre Politik ist keine Linie.')}</h1><p className="p-lead">{t('26 questions reveal how your views spread across eight political dimensions—without reducing you to one label.','26 Fragen zeigen, wie sich Ihre Ansichten über acht politische Dimensionen verteilen – ohne Sie auf ein Etikett zu reduzieren.')}</p><div className="p-actions"><a className="p-button light" href="/quiz">{t('Start the 3-minute Quick','3-Minuten-Quick starten')} <Arrow/></a><a className="p-text-link light" href="#method">{t('See how it works','So funktioniert es')}</a></div><div className="p-trust"><span>✓ {t('Free','Kostenlos')}</span><span>✓ {t('No sign-up','Keine Anmeldung')}</span><span>✓ {t('Private by default','Standardmäßig privat')}</span></div></div>
   <div className="p-hero-stage"><div className="p-hero-shape-hook"><ShapePreview axes={heroShapeAxes}/></div></div>
  </div></section>

  <section className="p-proof p-shell"><div><small>{t('QUICK','QUICK')}</small><strong>26</strong><span>{t('questions to start','Fragen zum Start')}</span></div><div><small>{t('YOUR MAP','IHRE KARTE')}</small><strong>8</strong><span>{t('political dimensions','politische Dimensionen')}</span></div><div><small>{t('FULL','FULL')}</small><strong>+16</strong><span>{t('questions for more depth','Fragen für mehr Tiefe')}</span></div><div><small>{t('PRIVATE','PRIVAT')}</small><strong>{t('No','Nein')}</strong><span>{t('sign-up required','Anmeldung erforderlich')}</span></div></section>

  <section className="p-section p-shell p-how" id="method"><div className="p-title-row"><h2>{t('How it works','So funktioniert es')}</h2><p><i/>{t('THREE STEPS. A CLEARER PICTURE.','DREI SCHRITTE. EIN KLARERES BILD.')}</p></div><div className="p-steps"><article><span className="p-step-icon">▤</span><div><h3>1. {t('Answer one statement.','Eine Aussage beantworten.')}</h3><p>{t('Respond to 26 short, balanced statements on real political issues. There are no right or wrong answers.','Beantworten Sie 26 kurze, ausgewogene Aussagen zu echten politischen Themen. Es gibt keine richtigen oder falschen Antworten.')}</p></div></article><article><span className="p-step-icon">⬠</span><div><h3>2. {t('See your shape.','Ihre Form sehen.')}</h3><p>{t('Your answers are mapped across eight dimensions, revealing the shape of your political thinking.','Ihre Antworten werden auf acht Dimensionen abgebildet und zeigen die Form Ihres politischen Denkens.')}</p></div></article><article><span className="p-step-icon bars">▥</span><div><h3>3. {t('Understand the pattern.','Das Muster verstehen.')}</h3><p>{t('Explore what your results mean, the trade-offs in your views, and how they compare to different perspectives.','Entdecken Sie, was Ihre Ergebnisse bedeuten, welche Zielkonflikte Ihre Ansichten enthalten und wie sie sich mit anderen Perspektiven vergleichen.')}</p></div></article></div></section>

  <section className="p-section p-shell p-transparency"><div><h2>{t('A result you can inspect, not a label you must accept.','Ein Ergebnis, das Sie prüfen können – kein Etikett, das Sie akzeptieren müssen.')}</h2><p>{t('Politangle is built on a transparent method, an open question bank and a clear scoring model. You can explore how it works, what it can and cannot tell you, and review the different versions of the questions.','Politangle basiert auf einer transparenten Methode, einem offenen Fragenkatalog und einem klaren Bewertungsmodell. Sie können nachvollziehen, wie es funktioniert, was es aussagen kann und was nicht, und die verschiedenen Frageversionen prüfen.')}</p><div className="p-resource-links"><a href="/method">{t('Read the method','Methode lesen')} <Arrow/></a><a href="/validation">{t('Scoring & limitations','Bewertung & Grenzen')} <Arrow/></a><a href="/question-banks">{t('Question-bank versions','Versionen der Fragen')} <Arrow/></a></div></div><div className="p-paper-scene"><article><small>{t('THE METHOD','DIE METHODE')}</small><span>{t('Dimensions','Dimensionen')}</span><span>{t('Question design','Fragegestaltung')}</span><span>{t('Scoring model','Bewertungsmodell')}</span><span>{t('Interpretation','Interpretation')}</span></article><article><small>{t('OPEN TO SCRUTINY','OFFEN ZUR PRÜFUNG')}</small><p>{t('Different questions. Same dimensions. A broader conversation.','Andere Fragen. Dieselben Dimensionen. Eine breitere Diskussion.')}</p><i/></article><aside><i/>{t('MORE INSIGHT. A HEALTHIER DEMOCRACY.','MEHR EINBLICK. EINE GESÜNDERE DEMOKRATIE.')}</aside></div></section>

  <section className="p-section p-shell" id="learn"><div className="p-section-head"><div><p className="p-kicker">{t('OPTIONAL KNOWLEDGE QUIZZES','OPTIONALE WISSENSQUIZZE')}</p><h2>{t('Test what you know, separately from what you believe.','Testen Sie Ihr Wissen getrennt von Ihren Überzeugungen.')}</h2></div><p>{t('CLASSIFY tests whether you can recognise political traditions. UNDERSTAND tests concepts, distinctions and trade-offs. Take either one independently.','CLASSIFY prüft, ob Sie politische Traditionen erkennen. UNDERSTAND prüft Begriffe, Unterschiede und Zielkonflikte. Beide können unabhängig voneinander absolviert werden.')}</p></div><div className="p-steps"><article><span>01</span><h3>CLASSIFY</h3><p>{t('Match political descriptions to the traditions that fit them best.','Ordnen Sie politische Beschreibungen den passendsten Traditionen zu.')}</p><a className="p-text-link" href="/classify">{t('Take CLASSIFY','CLASSIFY starten')} <Arrow/></a></article><article><span>02</span><h3>UNDERSTAND</h3><p>{t('Distinguish political concepts, boundaries and common misconceptions.','Unterscheiden Sie politische Begriffe, Abgrenzungen und häufige Missverständnisse.')}</p><a className="p-text-link" href="/understand">{t('Take UNDERSTAND','UNDERSTAND starten')} <Arrow/></a></article></div></section>

  <section className="p-dark-section" id="result"><div className="p-shell p-result-grid"><div><p className="p-kicker light">{t('YOUR POLITANGLE','IHR POLITANGLE')}</p><h2>{t('A political home, without flattening the details.','Eine politische Heimat, ohne die Details glattzubügeln.')}</h2><p className="p-section-copy">{t('Politangle shows your closest political traditions, then keeps the disagreements visible. You may fit one family overall while taking very different positions on individual issues.','Politangle zeigt Ihre nächstliegenden politischen Traditionen und lässt die Abweichungen sichtbar. Insgesamt können Sie zu einer Familie passen und bei einzelnen Themen dennoch ganz anders liegen.')}</p><a className="p-button light" href="/quiz">{t('Discover your angle','Perspektive entdecken')} <Arrow/></a></div><div className="p-dimension-card"><div className="p-card-top"><span>{t('POLITICAL SHAPE','POLITISCHE FORM')}</span><small>{t('Example','Beispiel')}</small></div>{dimensions.map(([name,detail,score])=><div className="p-dimension" key={name}><div><strong>{name}</strong><small>{detail}</small><b>{score}</b></div><i><em style={{width:`${score}%`}}/></i></div>)}<p>{t('Eight dimensions. One pattern that is yours.','Acht Dimensionen. Ein Muster, das Ihnen gehört.')}</p></div></div></section>

  <section className="p-section p-shell p-schools" id="schools"><div className="p-school-intro"><h2>{t('Political thinking in the classroom. Individual beliefs stay private.','Politisches Denken im Unterricht. Individuelle Überzeugungen bleiben privat.')}</h2><p>{t('Help young people explore politics beyond simple labels. Our school pilot offers a safe, age-appropriate way to spark thoughtful discussion, with anonymous classroom aggregates instead of individual results.','Helfen Sie jungen Menschen, Politik jenseits einfacher Etiketten zu erkunden. Unser Schulpilot ermöglicht sichere, altersgerechte Diskussionen mit anonymen Klassenaggregaten statt Einzelergebnissen.')}</p><a className="p-button" href="/school/pilot">{t('Apply for a controlled school pilot','Für einen kontrollierten Schulpilot bewerben')} <Arrow/></a></div><div className="p-age-bands"><span><b>{t('Junior','Junior')}</b>10–13<small>{t('Foundations for open-minded thinking','Grundlagen für offenes Denken')}</small></span><span><b>{t('Youth','Jugend')}</b>14–18<small>{t('Deeper discussion for a complex world','Vertiefte Diskussion für eine komplexe Welt')}</small></span></div><div className="p-school-proof"><div><span>♙</span><strong>{t('Anonymous classroom aggregates','Anonyme Klassenaggregate')}</strong></div><div><span>▥</span><strong>{t('Designed for educators','Für Lehrkräfte entwickelt')}</strong></div><div><span>♢</span><strong>{t('Individual answers stay private','Einzelantworten bleiben privat')}</strong></div><small>{t('CURIOSITY TODAY. A MORE THOUGHTFUL TOMORROW.','NEUGIER HEUTE. EIN REFLEKTIERTERES MORGEN.')}</small></div></section>

  <section className="p-section p-shell p-languages"><div><h2>{t('Available in English, Deutsch, Español and Français.','Verfügbar auf English, Deutsch, Español und Français.')}</h2><p>{t('You can take Politangle in different languages. Country-specific content—such as examples, context and classroom materials—is separate from the language and can be added over time.','Sie können Politangle in verschiedenen Sprachen nutzen. Länderspezifische Inhalte – etwa Beispiele, Kontext und Unterrichtsmaterialien – sind von der Sprache getrennt und können später ergänzt werden.')}</p></div><div className="p-language-list"><span><img src="/languages/london.svg" alt="London landmark illustration"/><small>English</small></span><span><img src="/languages/berlin.svg" alt="Berlin landmark illustration"/><small>Deutsch</small></span><span><img src="/languages/barcelona.svg" alt="Barcelona landmark illustration"/><small>Español</small></span><span><img src="/languages/paris.svg" alt="Paris landmark illustration"/><small>Français</small></span></div><aside><i/>{t('SAME IDEAS. MORE VOICES.','DIESELBEN IDEEN. MEHR STIMMEN.')}</aside></section>

  <section className="p-final p-shell"><div><h2>{t('Start with curiosity.','Mit Neugier starten.')}</h2><p>{t('Take Politangle Quick and see a broader picture of your political thinking.','Machen Sie Politangle Quick und entdecken Sie ein breiteres Bild Ihres politischen Denkens.')}</p><a className="p-button" href="/quiz">{t('Take Politangle Quick','Politangle Quick starten')} <Arrow/></a></div><aside><i/>{t('DIFFERENT PEOPLE. A BRIGHTER COMMON GROUND.','VERSCHIEDENE MENSCHEN. EINE HELLERE GEMEINSAME BASIS.')}</aside><div className="p-mountains" aria-hidden="true"><i/><i/><i/></div></section>
  <footer className="p-footer p-shell"><a className="p-brand" href="/"><Mark/><span><b>Politangle</b><small>politangle.org</small></span></a><div><a href="/method">{t('Method','Methode')}</a><a href="/validation">{t('Validation','Validierung')}</a><a href="/privacy">{t('Privacy','Datenschutz')}</a><a href="/imprint">{t('Imprint','Impressum')}</a><a href="/terms">{t('Terms','Bedingungen')}</a><a href="/contact">{t('Contact','Kontakt')}</a></div><small>© 2026 Politangle</small></footer>
 </main>;
}
