'use client';
import { localePath, useLocale } from './LocaleProvider';
import { SiteHeader } from './SiteChrome';
import { translate } from './translations';

const Arrow = () => <span aria-hidden="true">→</span>;

function ShapePreview({ axes, ariaLabel }: { axes: readonly (readonly [string, number])[]; ariaLabel: string }) {
 const cx = 180;
 const cy = 160;
 const maxRadius = 108;
 const polar = (radius:number,index:number) => {
  const angle = (-90 + index * 45) * Math.PI / 180;
  return { x: cx + Math.cos(angle) * radius, y: cy + Math.sin(angle) * radius };
 };
 const points = (level:number) => axes.map((_,index) => { const p = polar(maxRadius * (level / 100),index); return `${p.x},${p.y}`; }).join(' ');
 const profile = axes.map(([,score],index) => { const p = polar(maxRadius * (score / 100),index); return `${p.x},${p.y}`; }).join(' ');
 return <svg className="p-shape-preview" viewBox="0 0 360 320" role="img" aria-label={ariaLabel}>
  {[25,50,75,100].map((level) => <polygon className="p-shape-ring" key={level} points={points(level)}/>)}
  {axes.map((_,index) => { const p = polar(maxRadius,index); return <line className="p-shape-spoke" key={`spoke-${index}`} x1={cx} y1={cy} x2={p.x} y2={p.y}/>; })}
  <polygon className="p-shape-area" points={profile}/>
  {axes.map(([,score],index) => { const p = polar(maxRadius * (score / 100),index); return <circle className="p-shape-dot" key={`dot-${index}`} cx={p.x} cy={p.y} r="4"/>; })}
  {axes.map(([label],index) => { const p = polar(132,index); const anchor = p.x > cx + 14 ? 'start' : p.x < cx - 14 ? 'end' : 'middle'; return <text className="p-shape-label" key={label} x={p.x} y={p.y} textAnchor={anchor} dominantBaseline="middle">{label}</text>; })}
 </svg>;
}

export default function Home() {
 const { locale } = useLocale();
 const t = (en:string,de:string) => translate(locale, en, de);
 const href = (path:string) => localePath(locale, path);
 const dimensions = [
  [t('Economic role','Staat und Markt'),t('Public provision / redistribution ↔ Market / private responsibility','Öffentliche Absicherung ↔ Markt und Eigenverantwortung'),'68'],
  [t('Ownership','Eigentum'),t('Social / worker ownership ↔ Private / shareholder ownership','Gemeinschaftliches Eigentum ↔ Privateigentum'),'72'],
  [t('Social values','Gesellschaft und Werte'),t('Personal autonomy / change ↔ Tradition / moral continuity','Persönliche Freiheit ↔ Tradition und Beständigkeit'),'43'],
  [t('Authority','Freiheit und Ordnung'),t('Liberty / safeguards ↔ Order / preventive authority','Freiheitsrechte ↔ Staatliche Ordnung'),'31'],
  [t('Pluralism','Demokratische Kontrolle'),t('Checks / competing institutions ↔ Majoritarian concentration','Macht begrenzen ↔ Mehrheit entscheiden lassen'),'80'],
  [t('World','Internationale Zusammenarbeit'),t('International cooperation ↔ National discretion','Gemeinsam entscheiden ↔ National entscheiden'),'55'],
  [t('Nationhood','Nation und Zugehörigkeit'),t('Civic / inclusive membership ↔ Inherited / status-based continuity','Offene Zugehörigkeit ↔ Herkunft und Tradition'),'39'],
  [t('Ecology','Klima und Wirtschaft'),t('Ecological limits / structural change ↔ Growth / incremental adaptation','Ökologische Grenzen ↔ Wachstum und schrittweise Anpassung'),'82'],
 ];
 const heroShapeAxes = dimensions.map(([name,,score]) => [name, Number(score)] as const);
 return <main className="home">
  <SiteHeader />

  <section className="p-hero"><div className="p-orbit one"/><div className="p-orbit two"/><div className="p-shell p-hero-grid">
   <div className="p-hero-copy"><p className="p-kicker">{t('POLITICS WITHOUT THE BOXES','DEIN POLITISCHES PROFIL')}</p><h1>{t('Your politics are not a line.','Politik ist mehr als links oder rechts.')}</h1><p className="p-lead">{t('26 questions reveal how your views spread across eight political dimensions—without reducing you to one label.','26 Fragen zeigen, welche politischen Werte dir wichtig sind – und wo deine Ansichten nicht in ein einfaches Lager passen.')}</p><div className="p-actions"><a className="p-button light" href={href('/quiz')}>{t('Start the 3-minute Quick','Quick-Test starten')} <Arrow/></a><a className="p-text-link light" href={href('/method')}>{t('See how it works','So entsteht dein Ergebnis')}</a></div><div className="p-trust"><span>✓ {t('Free','Kostenlos')}</span><span>✓ {t('First Quick without sign-up','Ohne Anmeldung starten')}</span><span>✓ {t('Private by default','Deine Antworten bleiben privat')}</span></div></div>
   <div className="p-hero-stage"><div className="p-hero-shape-hook"><ShapePreview axes={heroShapeAxes} ariaLabel={t('Example eight-axis Politangle shape','Beispiel für ein Politangle-Profil mit acht Achsen')}/></div></div>
  </div></section>

  <section className="p-proof p-shell"><div><small>{t('QUICK','KURZTEST')}</small><strong>26</strong><span>{t('questions to start','Fragen zum Einstieg')}</span></div><div><small>{t('YOUR MAP','DEIN ERGEBNIS')}</small><strong>8</strong><span>{t('political dimensions','politische Blickwinkel')}</span></div><div><small>{t('FULL','VERTIEFUNG')}</small><strong>+16</strong><span>{t('questions for more depth','weitere Fragen')}</span></div><div><small>{t('FIRST QUICK','BEIM ERSTEN MAL')}</small><strong>{t('No account','Ohne Konto')}</strong><span>{t('for your first run','direkt loslegen')}</span></div></section>

  <section className="p-section p-shell p-how" id="method"><div className="p-title-row"><h2>{t('How it works','So funktioniert Politangle')}</h2><p><i/>{t('THREE STEPS. A CLEARER PICTURE.','DREI SCHRITTE ZU EINEM KLAREREN BILD.')}</p></div><div className="p-steps"><article><span className="p-step-icon">▤</span><div><h3>1. {t('Answer one statement.','Beantworte 26 Aussagen.')}</h3><p>{t('Respond to 26 short, balanced statements on real political issues. There are no right or wrong answers.','Es geht um politische Fragen aus dem Alltag. Keine Antwort wird als richtig oder falsch bewertet.')}</p></div></article><article><span className="p-step-icon">⬠</span><div><h3>2. {t('See your shape.','Sieh, was dir wichtig ist.')}</h3><p>{t('Your answers are mapped across eight dimensions, revealing the shape of your political thinking.','Deine Antworten ergeben ein Profil aus acht Bereichen – statt nur einen Platz auf einer Links-rechts-Skala.')}</p></div></article><article><span className="p-step-icon bars">▥</span><div><h3>3. {t('Understand the pattern.','Verstehe dein Gesamtbild.')}</h3><p>{t('Explore what your results mean, the trade-offs in your views, and how they compare to different perspectives.','Du erfährst, welche politischen Traditionen zu deinem Profil passen – und in welchen Punkten du von ihnen abweichst.')}</p></div></article></div></section>

  <section className="p-section p-shell p-transparency"><div><h2>{t('A result you can inspect, not a label you must accept.','Ein Ergebnis, das du nachvollziehen kannst.')}</h2><p>{t('Politangle is built on a transparent method, an open question bank and a clear scoring model. You can explore how it works, what it can and cannot tell you, and review the different versions of the questions.','Politangle zeigt, welche Antworten in welche Bereiche einfließen und wie dein Profil berechnet wird. Methode, Grenzen und verwendete Fragen kannst du jederzeit nachlesen.')}</p><div className="p-resource-links"><a href={href('/method')}>{t('Read the method','So funktioniert die Auswertung')} <Arrow/></a><a href={href('/validation')}>{t('Scoring & limitations','Was das Ergebnis aussagt')} <Arrow/></a><a href={href('/question-banks')}>{t('Question-bank versions','Verwendete Fragen')} <Arrow/></a></div></div><div className="p-paper-scene"><article><small>{t('THE METHOD','SO ENTSTEHT DEIN ERGEBNIS')}</small><span>{t('Dimensions','Acht Bereiche')}</span><span>{t('Question design','Die Fragen')}</span><span>{t('Scoring model','Die Berechnung')}</span><span>{t('Interpretation','Die Einordnung')}</span></article><article><small>{t('OPEN TO SCRUTINY','TRANSPARENT ERKLÄRT')}</small><p>{t('Different questions. Same dimensions. A broader conversation.','Du kannst jeden Schritt der Auswertung nachvollziehen.')}</p><i/></article><aside><i/>{t('MORE INSIGHT. A HEALTHIER DEMOCRACY.','MEHR VERSTEHEN. BESSER DISKUTIEREN.')}</aside></div></section>

  <section className="p-section p-shell" id="learn"><div className="p-section-head"><div><p className="p-kicker">{t('FREE LEARN & PRACTICE','KOSTENLOS LERNEN UND ÜBEN')}</p><h2>{t('Understand the words before testing what you know.','Politische Begriffe verstehen – und das eigene Wissen prüfen.')}</h2></div><p>{t('Read short, plain-language definitions, then try a balanced practice set or a focused quiz with feedback after every answer.','Kurze Erklärungen helfen beim Einstieg. Danach kannst du dein Wissen in Übungen und Themenquizzen testen.')}</p></div><div className="p-steps"><article><span>01</span><h3>{t('LEARN','NACHSCHLAGEN')}</h3><p>{t('Political traditions and difficult terms are explained in everyday language, with sources for readers who want more depth.','Politische Strömungen und schwierige Begriffe werden verständlich erklärt. Wer tiefer einsteigen möchte, findet dazu passende Quellen.')}</p><a className="p-text-link" href={href('/learn')}>{t('Open the glossary','Zum Glossar')} <Arrow/></a></article><article><span>02</span><h3>{t('PRACTICE','WISSEN TESTEN')}</h3><p>{t('Choose CLASSIFY or UNDERSTAND. Each free set covers the subject broadly instead of drawing 25 questions at random.','Teste, ob du politische Begriffe erkennst und ihre Bedeutung verstehst. Jede Runde deckt verschiedene Themen ab.')}</p><a className="p-text-link" href={href('/practice')}>{t('Start a practice set','Übung starten')} <Arrow/></a></article><article><span>03</span><h3>{t('SPOT POPULISM','POPULISMUS ERKENNEN')}</h3><p>{t('Recognize populist framing, democratic warning signs and false accusations across 12 focused questions.','Lerne, populistische Argumentationsmuster zu erkennen – ohne berechtigte Kritik vorschnell als populistisch abzutun.')}</p><a className="p-text-link" href={href('/populism-quiz')}>{t('Take the free quiz','Quiz starten')} <Arrow/></a></article></div></section>

  <section className="p-section p-shell p-countries-home">
    <div className="p-section-head">
      <div><p className="p-kicker">{t('COUNTRY PERSPECTIVES','POLITIK NACH LÄNDERN')}</p><h2>{t('The same political words can mean different things in different systems.','Was politisch „links“, „liberal“ oder „konservativ“ bedeutet, ist von Land zu Land verschieden.')}</h2></div>
      <p>{t('Explore how institutions, political vocabulary and historical turning points shape debate across 20 country perspectives. Current-data snapshots are shown only where they have been source-checked.','Unsere Länderporträts erklären politische Systeme, wichtige Wendepunkte und Begriffe im jeweiligen nationalen Zusammenhang. Aktuelle Angaben werden mit Quellen belegt.')}</p>
    </div>
    <div className="p-country-sample-grid">
      {[t('United States','USA'),t('Germany','Deutschland'),t('France','Frankreich'),t('United Kingdom','Vereinigtes Königreich'),t('India','Indien'),t('Brazil','Brasilien'),t('Mexico','Mexiko'),t('Japan','Japan')].map((country) => <span key={country}>{country}</span>)}
    </div>
    <a className="p-text-link" href={href('/countries')}>{t('Explore country perspectives','Länder entdecken')} <Arrow/></a>
  </section>

  <section className="p-dark-section" id="result"><div className="p-shell p-result-grid"><div><p className="p-kicker light">{t('YOUR POLITANGLE','DEIN ERGEBNIS')}</p><h2>{t('A political home, without flattening the details.','Dein politisches Profil – ohne dich auf ein Etikett zu reduzieren.')}</h2><p className="p-section-copy">{t('Politangle shows your closest political traditions, then keeps the disagreements visible. You may fit one family overall while taking very different positions on individual issues.','Du siehst, welchen politischen Strömungen deine Antworten am nächsten kommen. Gleichzeitig bleibt sichtbar, in welchen Fragen du anders denkst.')}</p><a className="p-button light" href={href('/quiz')}>{t('Discover your angle','Mein Profil entdecken')} <Arrow/></a></div><div className="p-dimension-card"><div className="p-card-top"><span>{t('POLITICAL SHAPE','BEISPIELPROFIL')}</span><small>{t('Example','Beispiel')}</small></div>{dimensions.map(([name,detail,score])=><div className="p-dimension" key={name}><div><strong>{name}</strong><small>{detail}</small><b>{score}</b></div><i><em style={{width:`${score}%`}}/></i></div>)}<p>{t('Eight dimensions. One pattern that is yours.','Acht Bereiche ergeben dein persönliches Gesamtbild.')}</p></div></div></section>

  <section className="p-section p-shell p-schools" id="schools"><div className="p-school-intro"><h2>{t('Political thinking in the classroom. Individual beliefs stay private.','Politik gemeinsam besprechen. Persönliche Antworten bleiben privat.')}</h2><p>{t('Help young people explore politics beyond simple labels. Our school pilot offers a safe, age-appropriate way to spark thoughtful discussion, with anonymous classroom aggregates instead of individual results.','Politangle hilft Jugendlichen, politische Fragen aus mehreren Blickwinkeln zu betrachten. Lehrkräfte sehen nur zusammengefasste Ergebnisse der Klasse – niemals das Profil einzelner Schüler:innen.')}</p><a className="p-button" href={href('/school/pilot')}>{t('Apply for a controlled school pilot','Mehr zum Schulpilot')} <Arrow/></a></div><div className="p-age-bands"><span><b>{t('Junior','Junior')}</b>10–13<small>{t('Foundations for open-minded thinking','Politische Grundlagen verstehen')}</small></span><span><b>{t('Youth','Youth')}</b>14–18<small>{t('Deeper discussion for a complex world','Komplexe Fragen diskutieren')}</small></span></div><div className="p-school-proof"><div><span>♙</span><strong>{t('Anonymous classroom aggregates','Nur zusammengefasste Klassenergebnisse')}</strong></div><div><span>▥</span><strong>{t('Designed for educators','Für den Unterricht entwickelt')}</strong></div><div><span>♢</span><strong>{t('Individual answers stay private','Persönliche Antworten bleiben privat')}</strong></div><small>{t('CURIOSITY TODAY. A MORE THOUGHTFUL TOMORROW.','NEUGIER WECKEN. GESPRÄCHE ANSTOSSEN.')}</small></div></section>

  <section className="p-section p-shell p-languages"><div><h2>{t('Quick and Full are available in English, Deutsch, Español, Français and Português (Brasil).','Politangle spricht fünf Sprachen.')}</h2><p>{t('The core Politangle assessment is available in five languages. Literacy practice and certification are enabled only where the relevant language content has completed its own review and validation.','Quick und Full gibt es auf Englisch, Deutsch, Spanisch, Französisch und brasilianischem Portugiesisch. Jede Sprachfassung wird eigenständig geprüft.')}</p></div><nav className="p-language-list" aria-label={t('Choose a language','Sprache auswählen')}><a href="/en"><img src="/languages/us.webp" alt={t('Statue of Liberty illustration','Freiheitsstatue')}/><small>English (US)</small></a><a href="/de"><img src="/languages/de.webp" alt={t('Brandenburg Gate illustration','Brandenburger Tor')}/><small>Deutsch</small></a><a href="/es"><img src="/languages/es.webp" alt={t('Sagrada Família illustration','Sagrada Família')}/><small>Español</small></a><a href="/fr"><img src="/languages/fr.webp" alt={t('Eiffel Tower illustration','Eiffelturm')}/><small>Français</small></a><a href="/pt-br"><img src="/languages/br.webp" alt={t('Christ the Redeemer illustration','Cristo Redentor')}/><small>Português (Brasil)</small></a></nav><aside><i/>{t('SAME IDEAS. MORE VOICES.','FÜNF SPRACHEN. EIN ANSATZ.')}</aside></section>

  <section className="p-final p-shell"><div><h2>{t('Start with curiosity.','Finde heraus, was dir politisch wichtig ist.')}</h2><p>{t('Take Politangle Quick and see a broader picture of your political thinking.','26 Fragen geben dir einen ersten Überblick – kostenlos und ohne Anmeldung.')}</p><a className="p-button" href={href('/quiz')}>{t('Take Politangle Quick','Quick-Test starten')} <Arrow/></a></div><aside><i/>{t('DIFFERENT PEOPLE. A BRIGHTER COMMON GROUND.','UNTERSCHIEDE VERSTEHEN. GEMEINSAMES FINDEN.')}</aside></section>
 </main>;
}
