export const countrySpecificityAnchors: Record<string, RegExp> = {
  'united-states': /gun rights|Reconstruction|Nineteenth Amendment/i,
  germany: /Bundesrat|constructive vote|Föderalismus|Federalism reform/i,
  france: /Fifth Republic|libéralisme|French revolutionary/i,
  'united-kingdom': /devolution|Brexit|parliamentary sovereignty/i,
  netherlands: /Polder model|Pillarisation/i,
  denmark: /Venstre|negative parliamentarism/i,
  finland: /Åland|National Coalition Party/i,
  iceland: /Independence Party|Althingi/i,
  norway: /Centre Party|Progress Party|petroleum/i,
  sweden: /people.?s home|Moderates|Sweden Democrats/i,
  spain: /Catalan|Basque|autonomous communit/i,
  mexico: /revolutionary and nationalist|Mexican revolutionary/i,
  canada: /Quebec|Indigenous self-government|Nunavut/i,
  'south-africa': /apartheid|African National Congress/i,
  india: /Indian secularism|Hindu nationalism|caste representation/i,
  nigeria: /Biafra|patronage|ethnicity/i,
  philippines: /People Power|political families|Bangsamoro/i,
  brazil: /coalition|military dictatorship|federal republic/i,
  indonesia: /Pancasila|Reformasi/i,
  japan: /Liberal Democratic Party|pacifism|developmental state/i,

  italy: /Christian democracy|post-communist|regional autonomy/i,
  poland: /church.?state|national sovereignty|European integration/i,
  romania: /anti-corruption|post-communist|judicial independence/i,
  portugal: /Social Democratic Party|1974 revolution/i,
  belgium: /Dutch-speaking|French-speaking|Flemish|Francophone/i,
  switzerland: /radical-liberal|direct democracy|cantonal/i,
  ireland: /Republican|civil-war split|partition/i,
  argentina: /Peronism|Radical Civic Union/i,
  colombia: /armed conflict|peace implementation|rural land/i,
  chile: /military rule|pensions|constitutional design/i,
  peru: /electoral vehicles|presidential power|party.*fluid/i,
  'costa-rica': /social-Christian|two-party|social-democratic/i,
  kenya: /47 counties|devolution/i,
  ghana: /Nkrumahism|pan-African/i,
  senegal: /pan-African|sovereignty|rupture/i,
  australia: /Liberal Party|preferential voting|compulsory voting/i,
  'new-zealand': /Treaty of Waitangi|Māori|iwi/i,
  'south-korea': /North Korea|regional political traditions/i,
  taiwan: /pan-blue|pan-green|Taiwan Strait|cross-strait/i,
  malaysia: /Malay rulers|ethnicity|religion|federal.?state/i,

  austria: /social partnership|Proporz/i,
  czechia: /Velvet Revolution|Czechoslovak|Senate/i,
  greece: /Metapolitefsi/i,
  hungary: /cardinal laws/i,
  ukraine: /martial law|Maidan/i,
  turkiye: /Laiklik|Kemalism/i,
  israel: /Basic Laws/i,
  uruguay: /Batllismo/i,
  ecuador: /muerte cruzada/i,
  'dominican-republic': /Trujillo|2024/i,
  panama: /Canal|comarca/i,
  cameroon: /Anglophone|Francophone/i,
  zambia: /1991|2025|copper/i,
  bangladesh: /caretaker/i,
  pakistan: /Federal Constitutional Court|civil.?military/i,
  thailand: /People.?s Constitution|military coup/i,
  egypt: /1952 Revolution/i,
  ethiopia: /House of the Federation/i,
  'democratic-republic-congo': /Congolité/i,
  serbia: /Kosovo/i,

  vietnam: /Đổi Mới/i,
  morocco: /Commander of the Faithful|monarchy/i,
  algeria: /Hirak/i,
  tanzania: /Zanzibar|Ujamaa/i,
  uganda: /Movement political system|National Resistance/i,
  'cote-divoire': /Ivoirité|Houphouëtisme/i,
  angola: /MPLA|UNITA/i,
  mozambique: /FRELIMO|RENAMO/i,
  'sri-lanka': /devolution|Thirteenth Amendment/i,
  nepal: /Madhesi|Maoist insurgency/i,
  iraq: /Muhasasa|Kurdistan/i,
  guatemala: /Maya|Xinka|Garifuna|Peace Accords/i,
  bolivia: /Plurinational|MAS|Movement toward Socialism/i,
  paraguay: /Stroessner|Colorado Party/i,
  venezuela: /Chavismo|Bolivarian/i,
  honduras: /2009 political crisis|Zelaya/i,
  'el-salvador': /ARENA|FMLN|Nuevas Ideas/i,
  singapore: /PAP|past reserves|elected presidency/i,
  tunisia: /2011 revolution|2022 Constitution|secular.*Islamist/i,
  georgia: /Rose Revolution|Abkhazia|South Ossetia|EU and NATO/i,
};
