import type { BeliefPolarity } from './belief-statements';

export const GERMAN_BELIEVE_VERSION = 'de-believe-2026.09-candidate-v1' as const;

const dePairs: Record<string, readonly [string, string]> = {
  T01: ['Der Staat sollte umfassend dafür sorgen, dass alle Menschen Zugang zu grundlegenden Leistungen haben.', 'Der Staat sollte eine begrenztere Rolle spielen; bei grundlegenden Leistungen sollten Menschen stärker private Angebote nutzen.'],
  T02: ['Der Staat sollte große Einkommensunterschiede durch Steuern und Transfers verringern, auch wenn dadurch manche mehr Steuern zahlen.', 'Der Staat sollte Einkommensunterschiede aus der Wirtschaft weniger verändern, auch wenn große Abstände bestehen bleiben.'],
  T03: ['Ein größerer Teil großer Unternehmen sollte Beschäftigten, Genossenschaften oder öffentlichen Trägern gehören statt überwiegend privaten Anteilseignern.', 'Große Unternehmen sollten normalerweise überwiegend privat bleiben, auch wenn der Staat sie reguliert und Beschäftigte schützt.'],
  T04: ['Wenn eine neue gesellschaftliche Norm deutlich unterstützt wird, sollten öffentliche Institutionen sich relativ früh anpassen.', 'Wenn eine neue gesellschaftliche Norm umstritten bleibt, sollten Institutionen warten, bis sie breit und dauerhaft akzeptiert ist.'],
  T05: ['Das Gesetz sollte privates, einvernehmliches Verhalten Erwachsener grundsätzlich zulassen, solange es anderen nicht direkt schadet.', 'Das Gesetz darf manche privaten, einvernehmlichen Handlungen Erwachsener begrenzen, um gemeinsame moralische Maßstäbe zu schützen.'],
  T06: ['Schwangerschaftsabbrüche sollten grundsätzlich legal möglich sein, weil die schwangere Person hauptsächlich entscheiden sollte.', 'Schwangerschaftsabbrüche sollten stärker gesetzlich begrenzt werden, weil der Staat ungeborenes Leben stärker schützen sollte.'],
  T07: ['Der Staat sollte Freiheit nur einschränken, wenn er eine konkrete und ernste Gefahr nachweisen kann.', 'Der Staat darf manche Freiheiten vorsorglich einschränken, wenn eine glaubhafte Gefahr schwerer Unruhen besteht.'],
  T08: ['Ein Wahlsieg sollte eine Regierung nicht von unabhängigen Kontrollen wie Gerichten und rechtlichen Schutzregeln befreien.', 'Eine gewählte Regierung sollte großen Spielraum haben, ihr Programm umzusetzen, auch wenn unabhängige Institutionen sie blockieren.'],
  T09: ['Staaten sollten verbindliche internationale Regeln akzeptieren, wenn grenzüberschreitende Probleme gemeinsames Handeln erfordern.', 'Staaten sollten das letzte Wort behalten, auch wenn gemeinsames Handeln dadurch weniger wirksam wird.'],
  T10: ['Eingebürgerte Menschen können genauso vollständig zur Nation gehören wie Menschen, die seit ihrer Geburt Staatsbürger sind.', 'Staatsbürgerschaft seit der Geburt sollte zusätzliches Gewicht dafür haben, wer vollständig zur Nation gehört.'],
  T11: ['Politische Konflikte spiegeln meist echte Unterschiede zwischen Gruppen und Werten wider, nicht hauptsächlich Volk gegen Elite.', 'Politik ist oft ein Konflikt zwischen normalen Menschen und einer eigennützigen Elite, die ihre gemeinsamen Interessen ignoriert.'],
  T12: ['Bei einem klaren Konflikt sollten ökologische Grenzen manchmal Vorrang vor Wirtschaftswachstum haben.', 'Bei einem Konflikt sollte Wirtschaftswachstum meist Vorrang haben; Umweltschäden sollten ohne absichtliche Wachstumsbegrenzung gelöst werden.'],
  T13: ['Religiöse Moralvorstellungen sollten nicht als öffentliche Begründung für Gesetze gelten, die auch Andersgläubige betreffen.', 'Religiöse Moralvorstellungen können legitime öffentliche Gründe für Gesetze sein, auch wenn nicht alle die Religion teilen.'],
  T14: ['Wichtige gesellschaftliche Aufgaben sollten von übergeordneten staatlichen Ebenen übernommen werden, wenn so gleiche Standards garantiert werden.', 'Wichtige Aufgaben sollten auf der niedrigsten leistungsfähigen Ebene bleiben; höhere Ebenen sollten nur bei Bedarf eingreifen.'],
  F01: ['Ich sorge mich stärker darum, dass Menschen ohne grundlegende Leistungen bleiben, wenn der Zugang stark von privaten Angeboten abhängt.', 'Ich sorge mich stärker um Abhängigkeit und fehlende Wahlfreiheit, wenn der Staat umfassend für grundlegende Leistungen zuständig ist.'],
  F02: ['Große Einkommensunterschiede beunruhigen mich stärker als die höheren Steuern, mit denen sie verringert werden.', 'Höhere Steuern beunruhigen mich stärker als große Einkommensunterschiede.'],
  F03: ['Es fühlt sich gerechter an, wenn Beschäftigte, Genossenschaften oder die Öffentlichkeit einen größeren Teil großer Unternehmen besitzen.', 'Es fühlt sich gerechter an, wenn private Investoren den größten Eigentumsanteil behalten und Gesetze Beschäftigte schützen.'],
  F04: ['Ich fühle mich unwohler, wenn öffentliche Institutionen einer deutlich unterstützten gesellschaftlichen Veränderung hinterherhinken.', 'Ich fühle mich unwohler, wenn Institutionen langjährige Regeln ändern, bevor eine neue Norm breit akzeptiert ist.'],
  F05: ['Ich fühle mich unwohler, wenn der Staat privates Verhalten Erwachsener einschränkt, das anderen nicht direkt schadet.', 'Ich fühle mich unwohler, wenn gemeinsame moralische Maßstäbe bei der Regelung privaten Verhaltens keine Rolle spielen.'],
  F06: ['Bei der Abtreibungspolitik sorge ich mich stärker um eine Einschränkung der Selbstbestimmung der schwangeren Person.', 'Bei der Abtreibungspolitik sorge ich mich stärker um einen unzureichenden Schutz ungeborenen Lebens.'],
  F07: ['In Krisen oder Unruhen sorge ich mich stärker um staatliche Übergriffe und unnötige Freiheitseinschränkungen.', 'In Krisen oder Unruhen sorge ich mich stärker darum, dass Behörden zu wenig Macht haben, Sicherheit und Ordnung wiederherzustellen.'],
  F08: ['Es alarmiert mich stärker, wenn eine gewählte Mehrheit unabhängige Kontrollen staatlicher Macht schwächt.', 'Es alarmiert mich stärker, wenn unabhängige Institutionen eine gewählte Regierung wiederholt an ihrem Programm hindern.'],
  F09: ['Ich fühle mich unwohler, wenn gemeinsame Probleme ungelöst bleiben, weil Staaten verbindliche internationale Verpflichtungen ablehnen.', 'Ich fühle mich unwohler, wenn internationale Verpflichtungen das letzte Wort meines Landes begrenzen.'],
  F10: ['Eingebürgerte Menschen, die am gesellschaftlichen Leben teilnehmen, fühlen sich für mich genauso zugehörig wie Staatsbürger seit Geburt.', 'Staatsbürger seit Geburt fühlen sich für mich stärker zur Nation gehörig als eingebürgerte Menschen.'],
  F11: ['Wenn Politik enttäuscht, denke ich eher an schwierige Abwägungen zwischen konkurrierenden Interessen.', 'Wenn Politik enttäuscht, gebe ich eher einer eigennützigen Elite die Schuld, die normale Menschen ignoriert.'],
  F12: ['Bei einem echten Zielkonflikt sorge ich mich stärker um ökologische Schäden durch den Vorrang des Wachstums.', 'Bei einem echten Zielkonflikt sorge ich mich stärker um Arbeitsplätze und Lebensstandard durch den Vorrang ökologischer Grenzen.'],
  F13: ['Ich fühle mich unwohler, wenn religiöse Moralvorstellungen Gesetze für Menschen begründen, die diesen Glauben nicht teilen.', 'Ich fühle mich unwohler, wenn religiöse Moralvorstellungen allein wegen ihres religiösen Ursprungs als illegitim gelten.'],
  F14: ['Ich fühle mich wohler, wenn höhere staatliche Ebenen wichtige Aufgaben übernehmen, um einheitliche Standards zu gewährleisten.', 'Ich fühle mich wohler, wenn fähige Familien, Gemeinden oder lokale Institutionen Verantwortung behalten.'],
  A01: ['Bei einer Abstimmung würde ich eine umfassendere öffentliche Verantwortung für den Zugang zu grundlegenden Leistungen unterstützen.', 'Bei einer Abstimmung würde ich eine kleinere staatliche Rolle und mehr private Verantwortung unterstützen.'],
  A02: ['Ich würde höhere Steuern und Transfers unterstützen, die große Einkommensunterschiede verringern, auch wenn meine Steuern moderat steigen.', 'Ich würde niedrigere Steuern vorziehen, auch wenn große Einkommensunterschiede bestehen bleiben.'],
  A03: ['Ich würde Maßnahmen unterstützen, die einen erheblichen Eigentumsanteil großer Unternehmen an Beschäftigte, Genossenschaften oder öffentliche Fonds übertragen.', 'Ich würde es vorziehen, wenn große Unternehmen überwiegend privaten Anteilseignern gehören.'],
  A04: ['Bei deutlicher, aber noch nicht überwältigender Unterstützung würde ich eine alte gesellschaftliche Regel eher früher aktualisieren.', 'Ich würde die alte Regel beibehalten, bis die neue Norm breit und dauerhaft akzeptiert ist.'],
  A05: ['Auch wenn ich privates Verhalten Erwachsener stark ablehnte, würde ich gesetzliche Verbote ohne direkten Schaden ablehnen.', 'Wenn Verhalten gemeinsame moralische Maßstäbe ernsthaft untergräbt, könnte ich gesetzliche Einschränkungen auch ohne direkten Schaden unterstützen.'],
  A06: ['Bei einer direkten Abstimmung würde ich für einen breiteren legalen Zugang zu Schwangerschaftsabbrüchen stimmen.', 'Bei einer direkten Abstimmung würde ich für stärkere gesetzliche Grenzen zum Schutz ungeborenen Lebens stimmen.'],
  A07: ['Bei schweren Unruhen würde ich starke rechtliche Schutzregeln beibehalten, auch wenn die Reaktion langsamer wäre.', 'Bei schweren Unruhen würde ich weitergehende vorübergehende Befugnisse erlauben, auch wenn Schutzregeln reduziert würden.'],
  A08: ['Auch bei einer von mir unterstützten Regierung würde ich unabhängige Kontrollen verteidigen, wenn sie ihr Programm verlangsamen.', 'Wenn Kontrollen ein gewähltes Programm wiederholt blockierten, könnte ich eine Verringerung ihrer Macht unterstützen.'],
  A09: ['Ich würde ein notwendiges verbindliches internationales Abkommen unterstützen, auch wenn es nationale Entscheidungen begrenzt.', 'Ich würde nationale Entscheidungshoheit behalten, auch wenn die internationale Reaktion dadurch weniger wirksam wäre.'],
  A10: ['Bei zwei sonst gleich geeigneten Kandidaten würde ich niemanden allein wegen der Staatsbürgerschaft seit Geburt bevorzugen.', 'Bei zwei sonst gleich geeigneten Kandidaten würde ich die Person mit Staatsbürgerschaft seit Geburt bevorzugen.'],
  A11: ['Ich würde Kandidaten bevorzugen, die politische Probleme nicht auf Volk gegen Elite reduzieren.', 'Ich würde Kandidaten bevorzugen, die versprechen, einer eigennützigen Elite Macht zu entziehen und den gemeinsamen Volkswillen umzusetzen.'],
  A12: ['Ich würde verbindliche Umweltgrenzen unterstützen, auch wenn sie das Wirtschaftswachstum moderat verlangsamen.', 'Ich würde Grenzen ablehnen, die Wachstum absichtlich verlangsamen, und wachstumsschonende Umweltpolitik bevorzugen.'],
  A13: ['Ich würde es vorziehen, wenn Amtsträger religiöse Moralvorstellungen nicht als Begründung für allgemein geltende Gesetze anführen.', 'Ich würde religiöse Moralvorstellungen als legitime Begründung für allgemein geltende Gesetze akzeptieren.'],
  A14: ['Wenn beide Ansätze funktionieren könnten, würde ich höhere staatliche Verantwortung wählen, um einheitliche Standards zu garantieren.', 'Wenn beide Ansätze funktionieren könnten, würde ich Verantwortung bei der niedrigsten leistungsfähigen Ebene belassen.'],
  J01: ['Der Staat sollte dafür sorgen, dass jede Familie Schulen und Ärzte nutzen kann.', 'Familien sollten mehr selbst entscheiden und weniger staatliche Hilfe erhalten.'],
  J02: ['Steuern sollten helfen, den Abstand zwischen Arm und Reich zu verkleinern.', 'Menschen sollten mehr von ihrem Einkommen behalten, auch wenn der Abstand groß bleibt.'],
  J03: ['Beschäftigte oder die Öffentlichkeit sollten mehr von den größten Unternehmen besitzen.', 'Die größten Unternehmen sollten überwiegend privaten Eigentümern gehören.'],
  J04: ['Öffentliche Regeln sollten sich ändern, wenn sich die Meinung der meisten Menschen ändert.', 'Alte Regeln sollten sich langsam ändern, nachdem lange Einigkeit bestand.'],
  J05: ['Erwachsene sollten private Entscheidungen frei treffen dürfen, solange niemand geschädigt wird.', 'Manche privaten Entscheidungen dürfen begrenzt werden, um gemeinsame Werte zu schützen.'],
  J06: ['Verantwortliche sollten Freiheit nur bei einer klaren und ernsten Gefahr begrenzen.', 'Verantwortliche dürfen Freiheit früh begrenzen, um schwere Unruhen zu verhindern.'],
  J07: ['Gerichte, Gesetze, andere Parteien und unabhängige Medien sollten gewählte Regierungen kontrollieren.', 'Wahlgewinner sollten großen Spielraum haben, das umzusetzen, was die Wähler gewählt haben.'],
  J08: ['Staaten sollten bei grenzüberschreitenden Problemen gemeinsame Regeln einhalten.', 'Jeder Staat sollte das letzte Wort behalten, auch wenn gemeinsame Probleme schwerer lösbar werden.'],
  J09: ['Eingebürgerte Menschen gehören genauso vollständig dazu wie Menschen, die als Staatsbürger geboren wurden.', 'Staatsbürgerschaft seit Geburt sollte stärker zählen, wenn es um vollständige Zugehörigkeit geht.'],
  J10: ['In der Politik gibt es meist viele Gruppen mit unterschiedlichen Bedürfnissen und Ideen.', 'Politik ist oft normale Menschen gegen eine mächtige Gruppe, die sie ignoriert.'],
  J11: ['Der Schutz der Natur sollte manchmal wichtiger sein als Wirtschaftswachstum.', 'Wirtschaftswachstum sollte meist zuerst kommen, während wir gleichzeitig die Natur schützen.'],
  J12: ['Religion sollte nicht für Gesetze genutzt werden, die auch Menschen anderer Religionen betreffen.', 'Religion kann ein fairer Grund für Gesetze sein, auch wenn nicht alle sie teilen.'],
  J13: ['Die nationale Regierung sollte wichtige Leistungen organisieren, damit alle denselben Standard erhalten.', 'Lokale Gemeinden sollten wichtige Leistungen organisieren, wann immer sie dazu in der Lage sind.'],
  J14: ['In einer Krise sorge ich mich stärker darum, dass Verantwortliche zu viel Macht erhalten.', 'In einer Krise sorge ich mich stärker darum, dass Verantwortliche zu wenig Macht für Sicherheit haben.'],
  J15: ['Ich sorge mich stärker, wenn gewählte Regierungen Gerichte, Gesetze oder unabhängige Medien schwächen.', 'Ich sorge mich stärker, wenn Gerichte oder andere Stellen gewählte Regierungen ständig blockieren.'],
  J16: ['Wenn Politik schlecht läuft, denke ich zuerst an schwierige Entscheidungen und unterschiedliche Wünsche.', 'Wenn Politik schlecht läuft, denke ich zuerst, dass eine mächtige Gruppe normale Menschen ignoriert.'],
};

export function germanBeliefStatement(sourceItemId: string, polarity: BeliefPolarity) {
  const pair = dePairs[sourceItemId];
  return pair?.[polarity === 'negative' ? 0 : 1] ?? null;
}

export const germanBeliefPairCount = Object.keys(dePairs).filter((id) => !id.startsWith('J')).length;
export const germanJuniorPairCount = Object.keys(dePairs).filter((id) => id.startsWith('J')).length;
