import type { LiteracyQuestion } from './deep-engine';

export const literacyQuestions: readonly LiteracyQuestion[] = [
  {
    id: 'C1', section: 'classify',
    prompt: 'A party keeps most businesses privately owned but supports strong public services, social insurance, worker protections and redistribution. Which tradition fits best?',
    options: [
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'communism', label: 'Communism' },
      { id: 'conservatism', label: 'Conservatism' },
    ],
    acceptedAnswerSets: [['social-democracy']],
    explanation: 'Modern social democracy usually keeps a mainly capitalist economy while using public services, regulation and redistribution to pursue social justice.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'C2', section: 'classify',
    prompt: 'A movement wants much more public, cooperative or worker ownership of major businesses. Which broad political family fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'socialism', label: 'Socialism' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['socialism']],
    explanation: 'Socialism is the broad family in which social, public, cooperative or worker ownership plays a central role, although its institutional forms vary.',
    evidenceIds: ['SEP-SOCIALISM'],
  },
  {
    id: 'C3', section: 'classify',
    prompt: 'A philosophy puts individual liberty, private property and voluntary exchange first, and wants government coercion kept very limited. Which tradition fits best?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'christian-democracy', label: 'Christian democracy' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['libertarianism']],
    explanation: 'Libertarianism gives especially strong priority to individual freedom, private property and voluntary exchange while seeking tight limits on coercive state power.',
    evidenceIds: ['SEP-LIBERTARIANISM'],
  },
  {
    id: 'C4', section: 'classify',
    prompt: 'A movement trusts inherited institutions, prefers gradual change and distrusts sweeping reforms built from abstract plans. Which tradition fits best?',
    options: [
      { id: 'socialism', label: 'Socialism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'populism', label: 'Populism' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'A major conservative tradition emphasizes continuity, inherited institutions and caution about rapid or abstractly designed social reform.',
    evidenceIds: ['SEP-CONSERVATISM'],
  },
  {
    id: 'C5', section: 'classify',
    prompt: 'A movement supports markets and private property, prefers gradual social change, and accepts welfare or regulation when these help maintain social cohesion. Which broad tradition fits best?',
    options: [
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'communism', label: 'Communism' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'Conservatism does not require a minimal state; conservative traditions can accept welfare and regulation while stressing continuity, obligation and social cohesion.',
    evidenceIds: ['SEP-CONSERVATISM', 'CHES-ECON-GALTAN'],
  },
  {
    id: 'C6', section: 'classify',
    prompt: 'A movement puts ecological limits and long-term sustainability near the center of politics and links them to participation, decentralization and social justice. Which tradition fits best?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'classical-liberalism', label: 'Classical liberalism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['green-politics']],
    explanation: 'Green political thought makes ecological limits and sustainability central and often connects them to participatory politics, decentralization and social justice.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  },
  {
    id: 'C7', section: 'classify',
    prompt: 'A movement aims ultimately for a classless, stateless society with no private ownership of the means of production. Which tradition is being described?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'communism', label: 'Communism' },
    ],
    acceptedAnswerSets: [['communism']],
    explanation: 'That is the Marxian communist ideal: a classless and ultimately stateless society without private ownership of the means of production.',
    evidenceIds: ['OXFORD-COMMUNISM', 'SEP-SOCIALISM'],
  },
  {
    id: 'C8', section: 'classify',
    prompt: 'A movement combines ultranationalism, authoritarian rule, rejection of political pluralism and hostility to liberal democracy. Which ideology fits best?',
    options: [
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['fascism']],
    explanation: 'Fascism combines ultranationalism and authoritarianism with rejection of pluralist liberal democracy; nationalism or conservatism alone is not fascism.',
    evidenceIds: ['USHMM-FASCISM'],
  },
  {
    id: 'C9', section: 'classify',
    prompt: 'A movement says nations have special political value and should be able to govern themselves, without taking a fixed position on markets or welfare. Which concept fits best?',
    options: [
      { id: 'populism', label: 'Populism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'social-democracy', label: 'Social democracy' },
    ],
    acceptedAnswerSets: [['nationalism']],
    explanation: 'Nationalism gives political importance to nations and national self-determination, but it can combine with different economic and social ideologies.',
    evidenceIds: ['SEP-NATIONALISM'],
  },
  {
    id: 'C10', section: 'classify',
    prompt: 'A political family puts liberty at its center but contains major disagreements about markets, welfare and what government should do to protect freedom. Which family is this?',
    options: [
      { id: 'liberalism', label: 'Liberalism' },
      { id: 'communism', label: 'Communism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'populism', label: 'Populism' },
    ],
    acceptedAnswerSets: [['liberalism']],
    explanation: 'Liberalism is a broad family united by the political importance of liberty but divided over what freedom requires from markets and government.',
    evidenceIds: ['SEP-LIBERALISM'],
  },
  {
    id: 'C11', section: 'classify',
    prompt: 'A movement explicitly draws on Christian social teaching, supports a social-market economy and welfare, and emphasizes subsidiarity. Which tradition fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['christian-democracy']],
    explanation: 'Christian democracy is distinguished by Christian political inspiration together with social-market ideas and principles such as subsidiarity.',
    evidenceIds: ['CAMBRIDGE-CHRISTIAN-DEMOCRACY', 'CAMBRIDGE-CD-RELIGIOUS-INSPIRATION', 'CAMBRIDGE-CD-SUBSIDIARITY'],
  },
  {
    id: 'C12', section: 'classify',
    prompt: 'A movement says politics is fundamentally a struggle between ordinary people and a corrupt establishment, and that government should carry out the people’s common will. Which concept fits best?',
    options: [
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'populism', label: 'Populism' },
      { id: 'liberalism', label: 'Liberalism' },
      { id: 'green-politics', label: 'Green politics' },
    ],
    acceptedAnswerSets: [['populism']],
    explanation: 'A widely used definition of populism contrasts a virtuous people with a corrupt establishment and gives special weight to the people’s general will.',
    evidenceIds: ['MUDDE-POPULISM'],
  },
  {
    id: 'C13', section: 'classify',
    prompt: 'A movement combines restrictive ideas of national membership, strong law-and-order authority and populist politics, while still competing in elections. Which pattern fits best?',
    options: [
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'populist-radical-right', label: 'Populist radical right' },
      { id: 'social-democracy', label: 'Social democracy' },
    ],
    acceptedAnswerSets: [['populist-radical-right']],
    explanation: 'Comparative scholarship commonly identifies the populist radical right through the combination of nativism, authoritarianism and populism within electoral politics.',
    evidenceIds: ['MUDDE-RADICAL-RIGHT', 'PIRRO-FAR-RIGHT'],
  },
  {
    id: 'C14', section: 'classify',
    prompt: 'A far-right movement openly rejects democracy itself, rather than merely opposing some liberal checks on elected government. Which label fits best?',
    options: [
      { id: 'extreme-right', label: 'Extreme right' },
      { id: 'radical-right', label: 'Radical right' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'populism', label: 'Populism' },
    ],
    acceptedAnswerSets: [['extreme-right']],
    explanation: 'A common scholarly distinction uses explicit rejection of democracy as a key marker of the extreme right.',
    evidenceIds: ['PIRRO-FAR-RIGHT'],
  },
  {
    id: 'C15', section: 'classify',
    prompt: 'A political system combines competitive elections with civil liberties, rule of law and independent checks on elected leaders. Which system is being described?',
    options: [
      { id: 'majoritarian-democracy', label: 'Unconstrained majoritarian democracy' },
      { id: 'one-party-rule', label: 'One-party rule' },
      { id: 'authoritarianism', label: 'Authoritarian government' },
      { id: 'liberal-democracy', label: 'Liberal democracy' },
    ],
    acceptedAnswerSets: [['liberal-democracy']],
    explanation: 'Liberal democracy combines electoral competition with civil liberties, rule of law and checks and balances on government power.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'C16', section: 'classify',
    prompt: 'A center-left party wants universal healthcare, stronger worker protections and progressive taxes, but does not want government to take over most businesses. Which tradition fits best?',
    options: [
      { id: 'socialism', label: 'Socialism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'communism', label: 'Communism' },
    ],
    acceptedAnswerSets: [['social-democracy']],
    explanation: 'Modern social democracy generally regulates and redistributes within a mainly capitalist ownership structure rather than replacing it.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'C17', section: 'classify',
    prompt: 'A democratic movement wants much more worker, cooperative or public ownership while keeping competitive elections, civil liberties and political pluralism. Which broad family fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'socialism', label: 'Socialism' },
      { id: 'fascism', label: 'Fascism' },
    ],
    acceptedAnswerSets: [['socialism']],
    explanation: 'Socialism can take democratic and pluralist forms; greater social ownership does not by itself imply one-party or authoritarian rule.',
    evidenceIds: ['SEP-SOCIALISM', 'VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'C18', section: 'classify',
    prompt: 'A movement argues that wealthy societies may sometimes need less growth or consumption because ecological limits cannot always be solved by cleaner technology alone. Which tradition fits best?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'conservatism', label: 'Conservatism' },
    ],
    acceptedAnswerSets: [['green-politics']],
    explanation: 'Green political thought gives distinctive weight to ecological limits and can support deeper changes to production and consumption.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  },
  {
    id: 'C19', section: 'classify',
    prompt: 'A movement wants government to protect rights and contracts but otherwise leave adults, markets and voluntary associations as free from coercion as possible. Which tradition fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'christian-democracy', label: 'Christian democracy' },
      { id: 'socialism', label: 'Socialism' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['libertarianism']],
    explanation: 'Libertarianism gives unusually strong priority to individual liberty and voluntary exchange and seeks a narrow role for coercive government action.',
    evidenceIds: ['SEP-LIBERTARIANISM'],
  },
  {
    id: 'C20', section: 'classify',
    prompt: 'A movement stresses continuity, social order and inherited institutions while accepting elections, opposition parties and constitutional limits. Which broad tradition fits best?',
    options: [
      { id: 'fascism', label: 'Fascism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'communism', label: 'Communism' },
      { id: 'populist-radical-right', label: 'Populist radical right' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'Conservatism can emphasize order, continuity and inherited institutions while remaining compatible with constitutional democratic politics.',
    evidenceIds: ['SEP-CONSERVATISM', 'VDEM-LIBERAL-DEMOCRACY'],
  },

  {
    id: 'U1', section: 'understand',
    prompt: 'Which description of populism is best supported?',
    options: [
      { id: 'u1-a', label: 'Populism is mainly a communication style; any recurring ideological content is too weak to matter.' },
      { id: 'u1-b', label: 'Populism is a full economic ideology that usually requires protectionism, redistribution and state ownership.' },
      { id: 'u1-c', label: 'Populism is usually treated as a thin-centered ideology that can attach to different host ideologies.' },
      { id: 'u1-d', label: 'Populism is best understood as direct democracy itself because it always rejects representatives and parties.' },
    ],
    acceptedAnswerSets: [['u1-c']],
    explanation: 'A widely used academic definition treats populism as thin-centered: it has recurring ideological claims but can combine with different host ideologies.',
    evidenceIds: ['MUDDE-POPULISM'],
  },
  {
    id: 'U2', section: 'understand',
    prompt: 'What can nationalism tell you about a movement?',
    options: [
      { id: 'u2-a', label: 'Nationalism normally implies right-wing economics because national self-determination and market conservatism usually come together.' },
      { id: 'u2-b', label: 'Nationalism can combine with several political traditions, so other beliefs are needed to place it left or right.' },
      { id: 'u2-c', label: 'Nationalism refers mainly to border control, so views on national self-government are secondary to immigration policy.' },
      { id: 'u2-d', label: 'Nationalism is essentially cultural traditionalism, so a movement with progressive social views cannot also be nationalist.' },
    ],
    acceptedAnswerSets: [['u2-b']],
    explanation: 'Nationalism gives political significance to nations and self-determination, but it has appeared in conservative, liberal, socialist and other forms.',
    evidenceIds: ['SEP-NATIONALISM'],
  },
  {
    id: 'U3', section: 'understand',
    prompt: 'What makes a democracy liberal as well as electoral?',
    options: [
      { id: 'u3-a', label: 'Competitive elections are enough, provided voters can replace the government at regular and meaningful intervals.' },
      { id: 'u3-b', label: 'A market economy and private property are the defining additions that turn electoral democracy into liberal democracy.' },
      { id: 'u3-c', label: 'A strong elected executive is the defining addition because it can act without unelected institutional obstruction.' },
      { id: 'u3-d', label: 'Competitive elections must operate alongside civil liberties, rule of law and meaningful checks on executive power.' },
    ],
    acceptedAnswerSets: [['u3-d']],
    explanation: 'Liberal democracy adds civil liberties, rule of law and checks on executive power to competitive electoral politics.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'U4', section: 'understand',
    prompt: 'What most clearly separates the extreme right from the radical right in comparative scholarship?',
    options: [
      { id: 'u4-a', label: 'The extreme right is simply more nationalist, while both remain equally committed to procedural democratic government.' },
      { id: 'u4-b', label: 'The radical right is defined by lower taxes, while the extreme right is defined by state ownership.' },
      { id: 'u4-c', label: 'The extreme right is explicitly anti-democratic, while the radical right can accept elections despite illiberal positions.' },
      { id: 'u4-d', label: 'The radical right necessarily uses populist language, while the extreme right is defined by avoiding populist appeals.' },
    ],
    acceptedAnswerSets: [['u4-c']],
    explanation: 'A common distinction places both under the far-right umbrella but treats explicit rejection of democracy as a key marker of the extreme right.',
    evidenceIds: ['PIRRO-FAR-RIGHT', 'MUDDE-RADICAL-RIGHT'],
  },
  {
    id: 'U5', section: 'understand',
    prompt: 'Why is liberalism difficult to reduce to one economic program?',
    options: [
      { id: 'u5-a', label: 'All liberal traditions favor a minimal state, so disagreement is mostly about how quickly to reduce government.' },
      { id: 'u5-b', label: 'Liberalism is mainly a theory of elections, while economic and personal liberty belong to separate traditions.' },
      { id: 'u5-c', label: 'Modern liberalism is defined by welfare provision, so market-oriented liberals fall outside the liberal family.' },
      { id: 'u5-d', label: 'Liberalism is a broad family centered on liberty, with real disagreements about markets, welfare and state action.' },
    ],
    acceptedAnswerSets: [['u5-d']],
    explanation: 'Liberal traditions share a concern with liberty but disagree substantially about property, markets, welfare and the proper role of government.',
    evidenceIds: ['SEP-LIBERALISM'],
  },
  {
    id: 'U6', section: 'understand',
    prompt: 'Which description of socialism is most accurate?',
    options: [
      { id: 'u6-a', label: 'Socialism is best defined by extensive welfare spending, even when most productive assets remain privately owned.' },
      { id: 'u6-b', label: 'Socialism is a broad family in which social ownership or control plays a central role, with varied institutional forms.' },
      { id: 'u6-c', label: 'Socialism requires central planning and state ownership, so cooperative or market-socialist models do not count.' },
      { id: 'u6-d', label: 'Socialism requires one-party government because competitive pluralist politics is incompatible with social ownership.' },
    ],
    acceptedAnswerSets: [['u6-b']],
    explanation: 'Socialism is a broad family with several models of social ownership and both democratic and non-democratic historical forms.',
    evidenceIds: ['SEP-SOCIALISM'],
  },
  {
    id: 'U7', section: 'understand',
    prompt: 'What is the clearest general difference between modern social democracy and socialism?',
    options: [
      { id: 'u7-a', label: 'Modern social democracy usually keeps predominantly private ownership, while socialism gives social ownership a more central role.' },
      { id: 'u7-b', label: 'The main difference is tax levels: social democracy favors moderate taxes, while socialism necessarily favors very high taxes.' },
      { id: 'u7-c', label: 'The main difference is democracy: social democracy accepts elections, while socialism necessarily rejects competitive multiparty government.' },
      { id: 'u7-d', label: 'The main difference is welfare: socialism supports public services, while social democracy relies mainly on private provision.' },
    ],
    acceptedAnswerSets: [['u7-a']],
    explanation: 'Modern social democracy generally regulates and redistributes within a mainly capitalist ownership structure, while social ownership is more central to socialism.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'U8', section: 'understand',
    prompt: 'Can conservatism include a welfare state?',
    options: [
      { id: 'u8-a', label: 'Conservatism can support welfare only when every benefit is privately delivered rather than publicly funded.' },
      { id: 'u8-b', label: 'Any universal welfare program moves a movement out of conservatism because conservatism requires a minimal state.' },
      { id: 'u8-c', label: 'Conservative traditions can accept welfare or regulation when these support social obligation, continuity, stability or cohesion.' },
      { id: 'u8-d', label: 'Conservative welfare support is possible only if the movement also favors public ownership of major industries.' },
    ],
    acceptedAnswerSets: [['u8-c']],
    explanation: 'Conservatism is not defined by one welfare-state position; some conservative traditions accept substantial social provision for reasons of obligation and cohesion.',
    evidenceIds: ['SEP-CONSERVATISM', 'CHES-ECON-GALTAN'],
  },
  {
    id: 'U9', section: 'understand',
    prompt: 'What makes Christian democracy more specific than markets plus welfare?',
    options: [
      { id: 'u9-a', label: 'A social-market economy plus generous welfare is already enough to identify Christian democracy with confidence.' },
      { id: 'u9-b', label: 'Christian political inspiration and subsidiarity, alongside social-market ideas, make the classification distinctly Christian democratic.' },
      { id: 'u9-c', label: 'Strong support for family policy is enough, even when the movement rejects religious inspiration and subsidiarity.' },
      { id: 'u9-d', label: 'Support for European cooperation is the key feature that separates Christian democracy from every other tradition.' },
    ],
    acceptedAnswerSets: [['u9-b']],
    explanation: 'The social-market mix is not unique to Christian democracy; Christian political inspiration and subsidiarity provide more distinctive evidence.',
    evidenceIds: ['CAMBRIDGE-CHRISTIAN-DEMOCRACY', 'CAMBRIDGE-CD-RELIGIOUS-INSPIRATION', 'CAMBRIDGE-CD-SUBSIDIARITY'],
  },
  {
    id: 'U10', section: 'understand',
    prompt: 'What most clearly distinguishes fascism from ordinary conservatism or nationalism?',
    options: [
      { id: 'u10-a', label: 'Strong patriotism plus strict law-and-order policies is enough to classify a movement as fascist.' },
      { id: 'u10-b', label: 'Corporatist economic organization is the defining feature, even if pluralism and competitive democracy remain protected.' },
      { id: 'u10-c', label: 'Fascism combines ultranationalism and authoritarianism with rejection of pluralism, individual rights and liberal representative democracy.' },
      { id: 'u10-d', label: 'Any nationalist movement becomes fascist once it favors a larger state or stronger social welfare programs.' },
    ],
    acceptedAnswerSets: [['u10-c']],
    explanation: 'Fascism is not a synonym for patriotism, conservatism or nationalism; its defining pattern includes authoritarian ultranationalism and rejection of liberal-democratic pluralism.',
    evidenceIds: ['USHMM-FASCISM'],
  },
  {
    id: 'U11', section: 'understand',
    prompt: 'Which description best matches the Marxian communist ideal?',
    options: [
      { id: 'u11-a', label: 'It ultimately envisions a classless and stateless society without private ownership of the means of production.' },
      { id: 'u11-b', label: 'It ultimately envisions a permanent one-party state with centralized planning as the final political goal.' },
      { id: 'u11-c', label: 'It ultimately envisions a worker-owned market economy that keeps private capital but distributes profits more equally.' },
      { id: 'u11-d', label: 'It ultimately envisions a regulated capitalist welfare state with private firms, universal services and progressive taxation.' },
    ],
    acceptedAnswerSets: [['u11-a']],
    explanation: 'In the Marxian ideal, communism is classless and ultimately stateless, with no private ownership of the means of production.',
    evidenceIds: ['OXFORD-COMMUNISM'],
  },
  {
    id: 'U12', section: 'understand',
    prompt: 'Why are public provision and public ownership different questions?',
    options: [
      { id: 'u12-a', label: 'Public funding usually means public ownership because governments must own any service they guarantee for everyone.' },
      { id: 'u12-b', label: 'Public services can be funded or guaranteed by government while delivery organizations remain public, private, cooperative or mixed.' },
      { id: 'u12-c', label: 'Public ownership matters only for industrial firms, while service provision has no meaningful ownership dimension.' },
      { id: 'u12-d', label: 'Public provision and ownership differ only in wording; in practice they always rise or fall together.' },
    ],
    acceptedAnswerSets: [['u12-b']],
    explanation: 'A government can fund or guarantee a service without owning every organization that provides it, so provision and ownership should be measured separately.',
    evidenceIds: ['WVS-W7-DOCUMENTATION', 'ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'U13', section: 'understand',
    prompt: 'What does populism tell you about democratic risk?',
    options: [
      { id: 'u13-a', label: 'Populist governments are authoritarian by definition, so the populist label alone is enough to predict democratic erosion.' },
      { id: 'u13-b', label: 'Winning elections protects democracy from erosion because electoral popularity gives a government sufficient democratic legitimacy.' },
      { id: 'u13-c', label: 'Populism can coexist with democracy, but anti-pluralism and weak commitment to democratic rules are stronger warning signs.' },
      { id: 'u13-d', label: 'Economic intervention is the main warning sign; populist governments become democratically risky primarily when they regulate markets.' },
    ],
    acceptedAnswerSets: [['u13-c']],
    explanation: 'Populism alone does not prove authoritarianism; anti-pluralism and weak commitment to democratic rules are more direct warning signs of erosion.',
    evidenceIds: ['VDEM-POPULISM-AUTOCRATIZATION', 'IDEA-POPULISM-DEMOCRACY'],
  },
  {
    id: 'U14', section: 'understand',
    prompt: 'Why should national sovereignty and restrictive national membership be measured separately?',
    options: [
      { id: 'u14-a', label: 'People who favor national self-government usually also believe naturalized citizens should have fewer political rights.' },
      { id: 'u14-b', label: 'A person can strongly favor national self-government while also treating naturalized citizens as full members of the nation.' },
      { id: 'u14-c', label: 'National sovereignty concerns immigration law only, while national membership concerns trade and international agreements.' },
      { id: 'u14-d', label: 'The two ideas are effectively the same because both measure how strongly someone identifies with their country.' },
    ],
    acceptedAnswerSets: [['u14-b']],
    explanation: 'National sovereignty concerns a country’s final political authority; national membership concerns who is treated as fully belonging. They can vary independently.',
    evidenceIds: ['SEP-NATIONALISM'],
  },
  {
    id: 'U15', section: 'understand',
    prompt: 'What makes green politics broader than ordinary environmental regulation?',
    options: [
      { id: 'u15-a', label: 'Any strong environmental regulation counts as green politics, even when economic growth remains the overriding political goal.' },
      { id: 'u15-b', label: 'Green politics treats ecological limits and sustainability as organizing concerns and often connects them to democracy and justice.' },
      { id: 'u15-c', label: 'Green politics requires rejecting markets entirely because market incentives are incompatible with ecological political goals.' },
      { id: 'u15-d', label: 'Green politics is mainly a conservation policy tradition and does not usually address economic or democratic institutions.' },
    ],
    acceptedAnswerSets: [['u15-b']],
    explanation: 'Green political thought treats ecological limits and sustainability as organizing political concerns rather than as one policy area among many.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  },
  {
    id: 'U16', section: 'understand',
    prompt: 'How does libertarianism fit within the broader politics of liberty?',
    options: [
      { id: 'u16-a', label: 'Libertarianism gives especially strong priority to individual freedom, private property, voluntary exchange and limits on coercive government.' },
      { id: 'u16-b', label: 'Libertarianism is mainly cultural liberalism, so economic regulation and property rights are secondary to personal lifestyle freedom.' },
      { id: 'u16-c', label: 'Libertarianism is a welfare-oriented branch of liberalism that uses redistribution to expand material freedom.' },
      { id: 'u16-d', label: 'Libertarianism is a traditionalist branch of liberalism that gives inherited institutions priority over individual choice.' },
    ],
    acceptedAnswerSets: [['u16-a']],
    explanation: 'Libertarianism belongs to the wider politics of liberty but gives unusually strong protection to personal freedom, property and voluntary exchange against coercion.',
    evidenceIds: ['SEP-LIBERTARIANISM', 'SEP-LIBERALISM'],
  },
  {
    id: 'U17', section: 'understand',
    prompt: 'Does support for redistribution by itself make someone socialist?',
    options: [
      { id: 'u17-a', label: 'Yes. Once redistribution becomes substantial, private ownership no longer matters for deciding whether a system is socialist.' },
      { id: 'u17-b', label: 'Yes. Taxation and social ownership are two names for the same underlying economic institution in practice.' },
      { id: 'u17-c', label: 'No. Redistribution can be extensive in systems that still keep predominantly private ownership of productive assets.' },
      { id: 'u17-d', label: 'No. Socialism concerns central planning only, so ownership and redistribution are not relevant to the definition.' },
    ],
    acceptedAnswerSets: [['u17-c']],
    explanation: 'Redistribution and social ownership are different dimensions; a country can redistribute extensively while retaining mainly private ownership.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM', 'WVS-W7-DOCUMENTATION'],
  },
  {
    id: 'U18', section: 'understand',
    prompt: 'What does subsidiarity mean in political organization?',
    options: [
      { id: 'u18-a', label: 'National government should normally control important services so standards remain identical in every local community.' },
      { id: 'u18-b', label: 'Responsibility should stay with the lowest capable level, with higher levels stepping in when necessary.' },
      { id: 'u18-c', label: 'Private organizations should replace government wherever possible because public authority should always be minimized.' },
      { id: 'u18-d', label: 'Regional governments should have final authority over national and local institutions whenever responsibilities overlap.' },
    ],
    acceptedAnswerSets: [['u18-b']],
    explanation: 'Subsidiarity favors keeping responsibility at the lowest level capable of handling it, while allowing higher levels to act when needed.',
    evidenceIds: ['CAMBRIDGE-CD-SUBSIDIARITY'],
  },
  {
    id: 'U19', section: 'understand',
    prompt: 'What separates ordinary conservatism from authoritarian politics?',
    options: [
      { id: 'u19-a', label: 'A conservative preference for law and order normally implies support for a stronger executive with fewer institutional checks.' },
      { id: 'u19-b', label: 'Conservatism can value order and continuity while remaining compatible with rights, pluralism, elections and constitutional limits.' },
      { id: 'u19-c', label: 'Conservative social values are the main marker of authoritarian politics, regardless of how political power is constrained.' },
      { id: 'u19-d', label: 'Authoritarianism is simply a more intense form of conservatism, so the two differ mostly by degree.' },
    ],
    acceptedAnswerSets: [['u19-b']],
    explanation: 'Conservative views about order or continuity do not by themselves imply rejection of pluralism, rights or constitutional limits.',
    evidenceIds: ['SEP-CONSERVATISM', 'VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'U20', section: 'understand',
    prompt: 'What is the best way to infer a person’s broader political tradition from questionnaire answers?',
    options: [
      { id: 'u20-a', label: 'Use the single issue on which the person answers most strongly because intensity reveals their underlying tradition.' },
      { id: 'u20-b', label: 'Use several dimensions and look for a pattern because political traditions overlap and contain important internal variation.' },
      { id: 'u20-c', label: 'Use the person’s own left-right label because self-placement is more reliable than the pattern across specific answers.' },
      { id: 'u20-d', label: 'Average every answer into one left-right number because one scale captures the main political traditions sufficiently.' },
    ],
    acceptedAnswerSets: [['u20-b']],
    explanation: 'Political traditions are bundles of ideas, so a multidimensional pattern is more defensible than classification from one answer or one left-right number.',
    evidenceIds: ['AAPOR-BEST-PRACTICES', 'SEP-LIBERALISM', 'SEP-CONSERVATISM', 'SEP-SOCIALISM'],
  },
] as const;
