import type { LiteracyQuestion } from './deep-engine';
import { LITERACY_MASTER_BANK_VERSION, type LiteracyDifficulty, type LiteracyQuestionRecord } from './literacy-bank-schema';
import { literacyQuestions } from './literacy-questions';

type CandidateMetadata = {
  blueprintBucket: LiteracyQuestionRecord['blueprintBucket'];
  difficulty: LiteracyDifficulty;
  secondaryTags: readonly string[];
};

function asCandidate(question: LiteracyQuestion, metadata: CandidateMetadata): LiteracyQuestionRecord {
  return {
    ...question,
    ...metadata,
    bankVersion: LITERACY_MASTER_BANK_VERSION,
    status: 'candidate',
    sourceLanguage: 'en',
  } as LiteracyQuestionRecord;
}

const CORE_METADATA: Readonly<Record<string, CandidateMetadata>> = {
  C1: { blueprintBucket: 'socialist_communist', difficulty: 'intermediate', secondaryTags: ['social-democracy', 'capitalism', 'redistribution'] },
  C2: { blueprintBucket: 'socialist_communist', difficulty: 'introductory', secondaryTags: ['socialism', 'social-ownership'] },
  C3: { blueprintBucket: 'liberal', difficulty: 'introductory', secondaryTags: ['libertarianism', 'private-property'] },
  C4: { blueprintBucket: 'conservative_christian_democratic', difficulty: 'introductory', secondaryTags: ['conservatism', 'gradual-change'] },
  C5: { blueprintBucket: 'conservative_christian_democratic', difficulty: 'intermediate', secondaryTags: ['conservatism', 'welfare'] },
  C6: { blueprintBucket: 'green_ecological', difficulty: 'introductory', secondaryTags: ['green-politics', 'ecological-limits'] },
  C7: { blueprintBucket: 'socialist_communist', difficulty: 'advanced', secondaryTags: ['communism', 'means-of-production'] },
  C8: { blueprintBucket: 'radical_extreme_fascist', difficulty: 'introductory', secondaryTags: ['fascism', 'ultranationalism'] },
  C9: { blueprintBucket: 'nationalism_populism', difficulty: 'introductory', secondaryTags: ['nationalism', 'self-determination'] },
  C10: { blueprintBucket: 'liberal', difficulty: 'introductory', secondaryTags: ['liberalism', 'liberty'] },
  C11: { blueprintBucket: 'conservative_christian_democratic', difficulty: 'advanced', secondaryTags: ['christian-democracy', 'subsidiarity'] },
  C12: { blueprintBucket: 'nationalism_populism', difficulty: 'introductory', secondaryTags: ['populism', 'people-elite'] },
  C13: { blueprintBucket: 'radical_extreme_fascist', difficulty: 'advanced', secondaryTags: ['populist-radical-right', 'nativism'] },
  C14: { blueprintBucket: 'radical_extreme_fascist', difficulty: 'advanced', secondaryTags: ['extreme-right', 'democracy-rejection'] },
  C15: { blueprintBucket: 'democracy_authoritarianism', difficulty: 'introductory', secondaryTags: ['liberal-democracy', 'rule-of-law'] },
  C16: { blueprintBucket: 'socialist_communist', difficulty: 'intermediate', secondaryTags: ['social-democracy', 'private-ownership'] },
  C17: { blueprintBucket: 'socialist_communist', difficulty: 'intermediate', secondaryTags: ['democratic-socialism', 'pluralism'] },
  C18: { blueprintBucket: 'green_ecological', difficulty: 'advanced', secondaryTags: ['green-politics', 'degrowth'] },
  C19: { blueprintBucket: 'liberal', difficulty: 'intermediate', secondaryTags: ['libertarianism', 'limited-government'] },
  C20: { blueprintBucket: 'conservative_christian_democratic', difficulty: 'intermediate', secondaryTags: ['conservatism', 'constitutionalism'] },
  U1: { blueprintBucket: 'definitions', difficulty: 'intermediate', secondaryTags: ['populism', 'thin-centered-ideology'] },
  U2: { blueprintBucket: 'left_right_limits', difficulty: 'intermediate', secondaryTags: ['nationalism', 'left-right'] },
  U3: { blueprintBucket: 'institutions_power', difficulty: 'introductory', secondaryTags: ['liberal-democracy', 'checks-and-balances'] },
  U4: { blueprintBucket: 'adjacent_distinctions', difficulty: 'advanced', secondaryTags: ['radical-right', 'extreme-right'] },
  U5: { blueprintBucket: 'adjacent_distinctions', difficulty: 'intermediate', secondaryTags: ['liberalism', 'economic-policy'] },
  U6: { blueprintBucket: 'definitions', difficulty: 'introductory', secondaryTags: ['socialism', 'social-ownership'] },
  U7: { blueprintBucket: 'adjacent_distinctions', difficulty: 'intermediate', secondaryTags: ['social-democracy', 'socialism'] },
  U8: { blueprintBucket: 'misconceptions', difficulty: 'intermediate', secondaryTags: ['conservatism', 'welfare'] },
  U9: { blueprintBucket: 'adjacent_distinctions', difficulty: 'advanced', secondaryTags: ['christian-democracy', 'subsidiarity'] },
  U10: { blueprintBucket: 'adjacent_distinctions', difficulty: 'intermediate', secondaryTags: ['fascism', 'conservatism'] },
  U11: { blueprintBucket: 'definitions', difficulty: 'introductory', secondaryTags: ['communism', 'marxism'] },
  U12: { blueprintBucket: 'economics_ownership', difficulty: 'intermediate', secondaryTags: ['public-provision', 'public-ownership'] },
  U13: { blueprintBucket: 'institutions_power', difficulty: 'advanced', secondaryTags: ['populism', 'anti-pluralism'] },
  U14: { blueprintBucket: 'misconceptions', difficulty: 'advanced', secondaryTags: ['national-sovereignty', 'membership'] },
  U15: { blueprintBucket: 'definitions', difficulty: 'intermediate', secondaryTags: ['green-politics', 'ecological-limits'] },
  U16: { blueprintBucket: 'adjacent_distinctions', difficulty: 'intermediate', secondaryTags: ['libertarianism', 'liberalism'] },
  U17: { blueprintBucket: 'misconceptions', difficulty: 'introductory', secondaryTags: ['redistribution', 'socialism'] },
  U18: { blueprintBucket: 'institutions_power', difficulty: 'introductory', secondaryTags: ['subsidiarity', 'decentralization'] },
  U19: { blueprintBucket: 'authoritarian_totalitarian', difficulty: 'intermediate', secondaryTags: ['conservatism', 'authoritarianism'] },
  U20: { blueprintBucket: 'multidimensional_patterns', difficulty: 'introductory', secondaryTags: ['measurement', 'political-patterns'] },
};

export const existingLiteracyCandidateRecords: readonly LiteracyQuestionRecord[] = literacyQuestions.map((question) => {
  const metadata = CORE_METADATA[question.id];
  if (!metadata) throw new Error(`Missing candidate metadata for ${question.id}`);
  return asCandidate(question, metadata);
});

const addedClassifyCandidates: readonly LiteracyQuestionRecord[] = [
  asCandidate({
    id: 'C21', section: 'classify',
    prompt: 'A movement protects democracy and rights but wants far more public, cooperative or worker ownership. Which tradition fits best?',
    options: [
      { id: 'social-democracy', label: 'Modern social democracy' },
      { id: 'democratic-socialism', label: 'Democratic socialism' },
      { id: 'marxism-leninism', label: 'Marxism–Leninism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['democratic-socialism']],
    explanation: 'Democratic socialism combines democracy with much more social ownership. Modern social democracy usually keeps most businesses private.',
    evidenceIds: ['SEP-SOCIALISM', 'ROUTLEDGE-SOCIAL-DEMOCRACY'],
  }, { blueprintBucket: 'socialist_communist', difficulty: 'intermediate', secondaryTags: ['democratic-socialism', 'social-democracy', 'social-ownership'] }),
  asCandidate({
    id: 'C22', section: 'classify',
    prompt: 'A tradition supports individual rights, limited government, private property and open markets. Which tradition fits best?',
    options: [
      { id: 'social-liberalism', label: 'Social liberalism' },
      { id: 'classical-liberalism', label: 'Classical liberalism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'anarchism', label: 'Anarchism' },
    ],
    acceptedAnswerSets: [['classical-liberalism']],
    explanation: 'Classical liberalism links freedom and limited government with private property and markets. Unlike anarchism, it still accepts a state.',
    evidenceIds: ['SEP-LIBERALISM', 'SEP-LIBERTARIANISM'],
  }, { blueprintBucket: 'liberal', difficulty: 'intermediate', secondaryTags: ['classical-liberalism', 'constitutional-government', 'markets'] }),
  asCandidate({
    id: 'C23', section: 'classify',
    prompt: 'A regime blocks real opposition and checks on rulers but leaves some private life alone. Which system fits best?',
    options: [
      { id: 'liberal-democracy', label: 'Liberal democracy' },
      { id: 'authoritarianism', label: 'Authoritarianism' },
      { id: 'totalitarianism', label: 'Totalitarianism' },
      { id: 'federalism', label: 'Federalism' },
    ],
    acceptedAnswerSets: [['authoritarianism']],
    explanation: 'Authoritarianism concentrates power and blocks real competition. Unlike totalitarianism, it may leave parts of private life alone.',
    evidenceIds: ['VDEM-REGIMES-OF-THE-WORLD', 'OXFORD-TOTALITARIANISM'],
  }, { blueprintBucket: 'democracy_authoritarianism', difficulty: 'intermediate', secondaryTags: ['authoritarianism', 'political-competition', 'constraints'] }),
  asCandidate({
    id: 'C24', section: 'classify',
    prompt: 'A tradition rejects unjustified central power and favors voluntary groups, mutual aid and local self-rule. Which tradition fits best?',
    options: [
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'anarchism', label: 'Anarchism' },
      { id: 'populism', label: 'Populism' },
      { id: 'federalism', label: 'Federalism' },
    ],
    acceptedAnswerSets: [['anarchism']],
    explanation: 'Anarchist traditions question central power and hierarchy and often favor voluntary, local cooperation.',
    evidenceIds: ['SEP-ANARCHISM'],
  }, { blueprintBucket: 'anarchism_other', difficulty: 'introductory', secondaryTags: ['anarchism', 'mutual-aid', 'decentralization'] }),
  asCandidate({
    id: 'C25', section: 'classify',
    prompt: 'A doctrine calls for a tightly organized revolutionary party to seize power and lead a transition to communism. Which doctrine fits best?',
    options: [
      { id: 'democratic-socialism', label: 'Democratic socialism' },
      { id: 'marxism-leninism', label: 'Marxism–Leninism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'anarchism', label: 'Anarchism' },
    ],
    acceptedAnswerSets: [['marxism-leninism']],
    explanation: 'Marxism–Leninism gives a leading role to a tightly organized revolutionary party. It is not another name for every socialist or communist view.',
    evidenceIds: ['BRITANNICA-MARXISM-LENINISM', 'OXFORD-COMMUNISM'],
  }, { blueprintBucket: 'socialist_communist', difficulty: 'advanced', secondaryTags: ['marxism-leninism', 'vanguard-party', 'communism'] }),
  asCandidate({
    id: 'C26', section: 'classify',
    prompt: 'A liberal movement says education, social insurance and market rules can give people more real freedom. Which tradition fits best?',
    options: [
      { id: 'classical-liberalism', label: 'Classical liberalism' },
      { id: 'social-liberalism', label: 'Social or modern liberalism' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'democratic-socialism', label: 'Democratic socialism' },
    ],
    acceptedAnswerSets: [['social-liberalism']],
    explanation: 'Social or modern liberalism values freedom but accepts more government action to expand people’s real opportunities.',
    evidenceIds: ['SEP-LIBERALISM'],
  }, { blueprintBucket: 'liberal', difficulty: 'advanced', secondaryTags: ['social-liberalism', 'positive-liberty', 'welfare'] }),
  asCandidate({
    id: 'C27', section: 'classify',
    prompt: 'A movement accepts markets and democracy but values social duty, tradition and cautious reform over individual choice. Which tradition fits best?',
    options: [
      { id: 'classical-liberalism', label: 'Classical liberalism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'social-democracy', label: 'Social democracy' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'The strongest clues are tradition, social duty and cautious reform. Markets alone do not identify one tradition.',
    evidenceIds: ['SEP-CONSERVATISM', 'SEP-LIBERALISM'],
  }, { blueprintBucket: 'conservative_christian_democratic', difficulty: 'advanced', secondaryTags: ['conservatism', 'social-duty', 'gradual-change'] }),
  asCandidate({
    id: 'C28', section: 'classify',
    prompt: 'A movement says protecting nature requires much more public or worker ownership. Which combined tradition fits best?',
    options: [
      { id: 'eco-socialism', label: 'Eco-socialism' },
      { id: 'green-liberalism', label: 'Green liberalism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
      { id: 'national-conservatism', label: 'National conservatism' },
    ],
    acceptedAnswerSets: [['eco-socialism']],
    explanation: 'This combines the green focus on ecological limits with the socialist focus on social ownership. Eco-socialism is the best fit.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS', 'SEP-SOCIALISM'],
  }, { blueprintBucket: 'green_ecological', difficulty: 'advanced', secondaryTags: ['eco-socialism', 'ecology', 'social-ownership'] }),
  asCandidate({
    id: 'C29', section: 'classify',
    prompt: 'A movement puts ecological limits first while supporting democracy, regulated markets and individual rights. Which family is most clearly present?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'marxism-leninism', label: 'Marxism–Leninism' },
      { id: 'populism', label: 'Populism' },
    ],
    acceptedAnswerSets: [['green-politics']],
    explanation: 'Ecological limits are the main clue. Green politics can use democratic government and markets and has no single ownership model.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  }, { blueprintBucket: 'green_ecological', difficulty: 'intermediate', secondaryTags: ['green-politics', 'regulated-markets', 'rights'] }),
  asCandidate({
    id: 'C30', section: 'classify',
    prompt: 'A movement defines the nation through shared citizenship, not ancestry, and supports national self-government. Which concept fits best?',
    options: [
      { id: 'civic-nationalism', label: 'Civic nationalism' },
      { id: 'nativism', label: 'Ancestry-based nationalism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'cosmopolitanism', label: 'Cosmopolitanism' },
    ],
    acceptedAnswerSets: [['civic-nationalism']],
    explanation: 'Civic nationalism bases national membership mainly on shared citizenship rather than family background or ancestry.',
    evidenceIds: ['SEP-NATIONALISM', 'GLOBALCIT-BIRTHRIGHT'],
  }, { blueprintBucket: 'nationalism_populism', difficulty: 'advanced', secondaryTags: ['civic-nationalism', 'citizenship', 'self-government'] }),
  asCandidate({
    id: 'C31', section: 'classify',
    prompt: 'A movement supports workers and attacks a corrupt elite in the name of ordinary people. Which part is populist?',
    options: [
      { id: 'redistribution', label: 'Supporting redistribution' },
      { id: 'worker-protection', label: 'Supporting worker protection' },
      { id: 'people-versus-elite', label: 'Setting people against a corrupt elite' },
      { id: 'public-services', label: 'Supporting public services' },
    ],
    acceptedAnswerSets: [['people-versus-elite']],
    explanation: 'The people-versus-elite claim is populist. Worker protection and redistribution can belong to several political programs.',
    evidenceIds: ['MUDDE-POPULISM', 'VDEM-POPULISM-AUTOCRATIZATION'],
  }, { blueprintBucket: 'nationalism_populism', difficulty: 'intermediate', secondaryTags: ['left-populism', 'host-ideology', 'people-elite'] }),
  asCandidate({
    id: 'C32', section: 'classify',
    prompt: 'A far-right organization rejects competitive democracy and argues that political opposition should be eliminated. Which label fits best?',
    options: [
      { id: 'radical-right', label: 'Radical right' },
      { id: 'extreme-right', label: 'Extreme right' },
      { id: 'ordinary-conservatism', label: 'Ordinary conservatism' },
      { id: 'populism', label: 'Populism' },
    ],
    acceptedAnswerSets: [['extreme-right']],
    explanation: 'Openly rejecting democracy and opposition is the key reason to classify this group as extreme right rather than radical right.',
    evidenceIds: ['PIRRO-FAR-RIGHT'],
  }, { blueprintBucket: 'radical_extreme_fascist', difficulty: 'intermediate', secondaryTags: ['extreme-right', 'democracy-rejection', 'opposition'] }),
  asCandidate({
    id: 'C33', section: 'classify',
    prompt: 'A country holds elections, but rulers block real competition and prevent voters from removing them. Which description fits best?',
    options: [
      { id: 'liberal-democracy', label: 'Liberal democracy' },
      { id: 'electoral-authoritarianism', label: 'Electoral authoritarianism' },
      { id: 'direct-democracy', label: 'Direct democracy' },
      { id: 'federalism', label: 'Federalism' },
    ],
    acceptedAnswerSets: [['electoral-authoritarianism']],
    explanation: 'Elections are not democratic when the competition is controlled and voters cannot realistically remove the rulers.',
    evidenceIds: ['VDEM-REGIMES-OF-THE-WORLD', 'VDEM-LIBERAL-DEMOCRACY'],
  }, { blueprintBucket: 'democracy_authoritarianism', difficulty: 'advanced', secondaryTags: ['electoral-authoritarianism', 'competition', 'media'] }),
  asCandidate({
    id: 'C34', section: 'classify',
    prompt: 'A system has fair elections but weak civil rights and weak checks on leaders. Which description fits best?',
    options: [
      { id: 'electoral-democracy', label: 'Electoral democracy, but not full liberal democracy' },
      { id: 'liberal-democracy', label: 'Full liberal democracy by definition' },
      { id: 'totalitarianism', label: 'Totalitarianism' },
      { id: 'anarchism', label: 'Anarchism' },
    ],
    acceptedAnswerSets: [['electoral-democracy']],
    explanation: 'Electoral democracy requires real competition. Liberal democracy also requires civil rights, rule of law and checks on leaders.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY', 'VDEM-REGIMES-OF-THE-WORLD'],
  }, { blueprintBucket: 'democracy_authoritarianism', difficulty: 'advanced', secondaryTags: ['electoral-democracy', 'liberal-democracy', 'civil-liberties'] }),
  asCandidate({
    id: 'C35', section: 'classify',
    prompt: 'A movement opposes state rule and bosses controlling workers. It favors worker-run groups and mutual aid. Which family fits best?',
    options: [
      { id: 'social-anarchism', label: 'Social anarchism' },
      { id: 'marxism-leninism', label: 'Marxism–Leninism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'classical-liberalism', label: 'Classical liberalism' },
    ],
    acceptedAnswerSets: [['social-anarchism']],
    explanation: 'Social anarchism opposes both central state power and unfair workplace hierarchy and favors voluntary, worker-run cooperation.',
    evidenceIds: ['SEP-ANARCHISM', 'SEP-SOCIALISM'],
  }, { blueprintBucket: 'anarchism_other', difficulty: 'advanced', secondaryTags: ['social-anarchism', 'workplace-hierarchy', 'mutual-aid'] }),
  asCandidate({
    id: 'C36', section: 'classify',
    prompt: 'A thinker rejects state power but strongly supports private property and voluntary markets. Which classification fits best?',
    options: [
      { id: 'social-anarchism', label: 'Social anarchism' },
      { id: 'market-anarchism', label: 'Market-oriented anarchism' },
      { id: 'social-democracy', label: 'Modern social democracy' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['market-anarchism']],
    explanation: 'Anarchism includes different economic views. Supporting property and markets points to a market-oriented or individualist form.',
    evidenceIds: ['SEP-ANARCHISM', 'SEP-LIBERTARIANISM'],
  }, { blueprintBucket: 'anarchism_other', difficulty: 'advanced', secondaryTags: ['individualist-anarchism', 'markets', 'private-property'] }),
  asCandidate({
    id: 'C37', section: 'classify',
    prompt: 'A party supports markets and family benefits but says nothing about Christian ideas or local decision-making. What can we conclude?',
    options: [
      { id: 'yes-welfare', label: 'Yes; welfare and markets are sufficient' },
      { id: 'yes-family', label: 'Yes; family benefits are sufficient' },
      { id: 'no-insufficient', label: 'No; the evidence is insufficient' },
      { id: 'no-socialist', label: 'No; it must be socialist' },
    ],
    acceptedAnswerSets: [['no-insufficient']],
    explanation: 'Several traditions mix markets and welfare. Christian social ideas and subsidiarity would give stronger evidence for Christian democracy.',
    evidenceIds: ['CAMBRIDGE-CHRISTIAN-DEMOCRACY', 'CAMBRIDGE-CD-RELIGIOUS-INSPIRATION', 'CAMBRIDGE-CD-SUBSIDIARITY'],
  }, { blueprintBucket: 'cross_family', difficulty: 'advanced', secondaryTags: ['classification-evidence', 'christian-democracy', 'insufficient-information'] }),
  asCandidate({
    id: 'C38', section: 'classify',
    prompt: 'A voter supports public railways, strict social rules and strong national self-government. Which single tradition clearly follows?',
    options: [
      { id: 'socialism', label: 'This clearly shows socialism' },
      { id: 'conservatism', label: 'This clearly shows conservatism' },
      { id: 'nationalism', label: 'This clearly shows nationalism' },
      { id: 'insufficient', label: 'No single tradition clearly follows' },
    ],
    acceptedAnswerSets: [['insufficient']],
    explanation: 'Ownership, social rules and national power are separate questions. This mixed pattern does not justify one simple label.',
    evidenceIds: ['CHES-ECON-GALTAN', 'SEP-SOCIALISM', 'SEP-NATIONALISM'],
  }, { blueprintBucket: 'cross_family', difficulty: 'intermediate', secondaryTags: ['mixed-pattern', 'economic-left', 'cultural-right'] }),
  asCandidate({
    id: 'C39', section: 'classify',
    prompt: 'A movement supports national self-government, equal citizenship, civil rights and limits on leaders. Which description fits best?',
    options: [
      { id: 'liberal-nationalism', label: 'Liberal nationalism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'marxism-leninism', label: 'Marxism–Leninism' },
      { id: 'totalitarianism', label: 'Totalitarianism' },
    ],
    acceptedAnswerSets: [['liberal-nationalism']],
    explanation: 'National self-government can combine with equal citizenship, rights and limits on leaders. Nationalism is not always illiberal.',
    evidenceIds: ['SEP-NATIONALISM', 'SEP-LIBERALISM'],
  }, { blueprintBucket: 'cross_family', difficulty: 'advanced', secondaryTags: ['liberal-nationalism', 'equal-citizenship', 'constitutionalism'] }),
  asCandidate({
    id: 'C40', section: 'classify',
    prompt: 'A party promises lower taxes and says ordinary people must defeat a corrupt elite. What can we conclude?',
    options: [
      { id: 'libertarian', label: 'It must be libertarian because it lowers taxes' },
      { id: 'conservative', label: 'It must be conservative because it lowers taxes' },
      { id: 'populist-host-open', label: 'It is populist; its wider politics remain unclear' },
      { id: 'fascist', label: 'It must be fascist because it attacks elites' },
    ],
    acceptedAnswerSets: [['populist-host-open']],
    explanation: 'The people-versus-elite claim is populist. One tax policy does not reveal the party’s whole political outlook.',
    evidenceIds: ['MUDDE-POPULISM', 'VDEM-POPULISM-AUTOCRATIZATION'],
  }, { blueprintBucket: 'cross_family', difficulty: 'intermediate', secondaryTags: ['populism', 'host-ideology', 'taxation'] }),
] as const;

const addedUnderstandCandidates: readonly LiteracyQuestionRecord[] = [
  asCandidate({
    id: 'U21', section: 'understand',
    prompt: 'How should communism and Marxism–Leninism be distinguished?',
    options: [
      { id: 'u21-a', label: 'They are exact synonyms for every theory of social ownership.' },
      { id: 'u21-b', label: 'Communism is broader; Marxism–Leninism adds rule by a revolutionary party.' },
      { id: 'u21-c', label: 'Communism means welfare capitalism, while Marxism–Leninism means democratic socialism.' },
      { id: 'u21-d', label: 'Marxism–Leninism rejects communism’s goal of collective ownership.' },
    ],
    acceptedAnswerSets: [['u21-b']],
    explanation: 'Communism is broader than Marxism–Leninism. Marxism–Leninism is a historically specific doctrine centered on a disciplined vanguard party and centralized transition.',
    evidenceIds: ['OXFORD-COMMUNISM', 'BRITANNICA-MARXISM-LENINISM'],
  }, { blueprintBucket: 'adjacent_distinctions', difficulty: 'advanced', secondaryTags: ['communism', 'marxism-leninism', 'vanguard-party'] }),
  asCandidate({
    id: 'U22', section: 'understand',
    prompt: 'What best distinguishes democratic socialism from modern social democracy?',
    options: [
      { id: 'u22-a', label: 'Democratic socialism rejects elections; social democracy accepts them.' },
      { id: 'u22-b', label: 'Democratic socialism seeks more social ownership; social democracy usually reforms capitalism.' },
      { id: 'u22-c', label: 'Only social democracy supports public services.' },
      { id: 'u22-d', label: 'The two always mean exactly the same thing in every country and period.' },
    ],
    acceptedAnswerSets: [['u22-b']],
    explanation: 'Both can support democracy and welfare. The clearest general distinction is the larger role that democratic socialism assigns to social ownership beyond regulated capitalism.',
    evidenceIds: ['SEP-SOCIALISM', 'ROUTLEDGE-SOCIAL-DEMOCRACY'],
  }, { blueprintBucket: 'adjacent_distinctions', difficulty: 'intermediate', secondaryTags: ['democratic-socialism', 'social-democracy', 'ownership'] }),
  asCandidate({
    id: 'U23', section: 'understand',
    prompt: 'Which comparison of classical liberalism, social liberalism and libertarianism is most accurate?',
    options: [
      { id: 'u23-a', label: 'All three require the same minimal state and reject social provision.' },
      { id: 'u23-b', label: 'All value freedom but disagree about property, welfare and government action.' },
      { id: 'u23-c', label: 'Social liberalism is socialist because it accepts welfare.' },
      { id: 'u23-d', label: 'Libertarianism values authority over individual choice.' },
    ],
    acceptedAnswerSets: [['u23-b']],
    explanation: 'These traditions overlap around liberty but make different judgments about property, markets, welfare and permissible government action.',
    evidenceIds: ['SEP-LIBERALISM', 'SEP-LIBERTARIANISM'],
  }, { blueprintBucket: 'adjacent_distinctions', difficulty: 'advanced', secondaryTags: ['classical-liberalism', 'social-liberalism', 'libertarianism'] }),
  asCandidate({
    id: 'U24', section: 'understand',
    prompt: 'What is the clearest difference between authoritarianism and totalitarianism?',
    options: [
      { id: 'u24-a', label: 'Authoritarianism is always right-wing, while totalitarianism is always left-wing.' },
      { id: 'u24-b', label: 'Totalitarianism seeks control of private life as well as politics.' },
      { id: 'u24-c', label: 'Authoritarianism has no rulers, while totalitarianism has one ruler.' },
      { id: 'u24-d', label: 'There is no meaningful distinction in political science.' },
    ],
    acceptedAnswerSets: [['u24-b']],
    explanation: 'Both restrict political competition, but totalitarianism describes a more encompassing project to control institutions, society and private life.',
    evidenceIds: ['OXFORD-TOTALITARIANISM', 'VDEM-REGIMES-OF-THE-WORLD'],
  }, { blueprintBucket: 'authoritarian_totalitarian', difficulty: 'intermediate', secondaryTags: ['authoritarianism', 'totalitarianism', 'state-control'] }),
  asCandidate({
    id: 'U25', section: 'understand',
    prompt: 'Why is authoritarianism not inherently a left- or right-wing economic ideology?',
    options: [
      { id: 'u25-a', label: 'It describes political power, which can sit beside different economic systems.' },
      { id: 'u25-b', label: 'Because authoritarian regimes never make economic policy.' },
      { id: 'u25-c', label: 'Because every authoritarian regime uses an identical mixed economy.' },
      { id: 'u25-d', label: 'Because left and right refer only to foreign policy.' },
    ],
    acceptedAnswerSets: [['u25-a']],
    explanation: 'Authoritarianism primarily describes concentrated, weakly accountable political power. It can coexist with different ownership and distribution arrangements.',
    evidenceIds: ['VDEM-REGIMES-OF-THE-WORLD', 'CHES-ECON-GALTAN'],
  }, { blueprintBucket: 'authoritarian_totalitarian', difficulty: 'intermediate', secondaryTags: ['authoritarianism', 'economic-left-right', 'political-power'] }),
  asCandidate({
    id: 'U26', section: 'understand',
    prompt: 'Can a regime be authoritarian while allowing some elections and private businesses?',
    options: [
      { id: 'u26-a', label: 'No; either feature automatically makes a country democratic.' },
      { id: 'u26-b', label: 'Yes; elections can be controlled and private business does not ensure democracy.' },
      { id: 'u26-c', label: 'No; authoritarianism requires abolishing all money and markets.' },
      { id: 'u26-d', label: 'Yes, but only when the country is formally federal.' },
    ],
    acceptedAnswerSets: [['u26-b']],
    explanation: 'Authoritarian systems can hold controlled elections and retain private firms. The key questions concern real competition, rights and constraints on rulers.',
    evidenceIds: ['VDEM-REGIMES-OF-THE-WORLD', 'VDEM-LIBERAL-DEMOCRACY'],
  }, { blueprintBucket: 'authoritarian_totalitarian', difficulty: 'introductory', secondaryTags: ['electoral-authoritarianism', 'private-ownership', 'accountability'] }),
  asCandidate({
    id: 'U27', section: 'understand',
    prompt: 'What is the difference between negative and positive liberty in liberal thought?',
    options: [
      { id: 'u27-a', label: 'One means freedom from interference; the other means real power to act.' },
      { id: 'u27-b', label: 'Negative liberty is illegal freedom; positive liberty is lawful freedom.' },
      { id: 'u27-c', label: 'Negative liberty concerns markets only; positive liberty concerns elections only.' },
      { id: 'u27-d', label: 'They are two names for exactly the same claim about government.' },
    ],
    acceptedAnswerSets: [['u27-a']],
    explanation: 'Negative liberty focuses on absence of interference, while positive liberty focuses on self-direction or effective capacity. Liberal traditions disagree about their implications.',
    evidenceIds: ['SEP-LIBERALISM'],
  }, { blueprintBucket: 'definitions', difficulty: 'advanced', secondaryTags: ['negative-liberty', 'positive-liberty', 'liberalism'] }),
  asCandidate({
    id: 'U28', section: 'understand',
    prompt: 'What is the democratic purpose of independent courts reviewing government action?',
    options: [
      { id: 'u28-a', label: 'To replace elections with rule by judges.' },
      { id: 'u28-b', label: 'To help enforce law and constitutional limits even against current office holders.' },
      { id: 'u28-c', label: 'To guarantee that courts always agree with public opinion.' },
      { id: 'u28-d', label: 'To let judges write every public policy directly.' },
    ],
    acceptedAnswerSets: [['u28-b']],
    explanation: 'Independent courts can uphold rights, legality and constitutional limits. That constraining role complements rather than replaces competitive elections.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY'],
  }, { blueprintBucket: 'institutions_power', difficulty: 'intermediate', secondaryTags: ['judicial-independence', 'rule-of-law', 'executive-constraints'] }),
  asCandidate({
    id: 'U29', section: 'understand',
    prompt: 'Why do checks and balances matter after a government wins an election?',
    options: [
      { id: 'u29-a', label: 'An election gives the winner unlimited authority until the next vote.' },
      { id: 'u29-b', label: 'Checks protect rights, law and the ability of opponents to compete later.' },
      { id: 'u29-c', label: 'Checks exist mainly to prevent governments from changing tax rates.' },
      { id: 'u29-d', label: 'Checks matter only in countries without constitutions.' },
    ],
    acceptedAnswerSets: [['u29-b']],
    explanation: 'Democratic authorization is limited: institutions protect rights, legality and future competition from abuse by current majorities or executives.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY'],
  }, { blueprintBucket: 'institutions_power', difficulty: 'intermediate', secondaryTags: ['checks-and-balances', 'majority-rule', 'rights'] }),
  asCandidate({
    id: 'U30', section: 'understand',
    prompt: 'How are social ownership and state ownership related?',
    options: [
      { id: 'u30-a', label: 'They are always identical.' },
      { id: 'u30-b', label: 'State ownership is one form; cooperatives and worker control are others.' },
      { id: 'u30-c', label: 'Social ownership means private shareholders own all firms.' },
      { id: 'u30-d', label: 'State ownership refers only to welfare payments.' },
    ],
    acceptedAnswerSets: [['u30-b']],
    explanation: 'Social ownership is broader than central state ownership and can include public, cooperative, municipal and worker-controlled arrangements.',
    evidenceIds: ['SEP-SOCIALISM'],
  }, { blueprintBucket: 'economics_ownership', difficulty: 'intermediate', secondaryTags: ['social-ownership', 'state-ownership', 'cooperatives'] }),
  asCandidate({
    id: 'U31', section: 'understand',
    prompt: 'What does “means of production” refer to in debates about socialism and communism?',
    options: [
      { id: 'u31-a', label: 'Only personal belongings such as clothing and furniture.' },
      { id: 'u31-b', label: 'Productive assets and resources used to make goods and services.' },
      { id: 'u31-c', label: 'Only the money collected through income tax.' },
      { id: 'u31-d', label: 'Voting systems used to select governments.' },
    ],
    acceptedAnswerSets: [['u31-b']],
    explanation: 'The phrase refers to productive assets—such as workplaces, equipment, land and capital—not ordinary personal possessions.',
    evidenceIds: ['SEP-SOCIALISM', 'OXFORD-COMMUNISM'],
  }, { blueprintBucket: 'economics_ownership', difficulty: 'introductory', secondaryTags: ['means-of-production', 'productive-assets', 'personal-property'] }),
  asCandidate({
    id: 'U32', section: 'understand',
    prompt: 'Can markets exist in a socialist model?',
    options: [
      { id: 'u32-a', label: 'No; socialism is defined only by complete central planning.' },
      { id: 'u32-b', label: 'Yes; some market-socialist models combine markets with social or worker ownership.' },
      { id: 'u32-c', label: 'Yes, but only if every firm remains owned by outside private investors.' },
      { id: 'u32-d', label: 'No; any voluntary exchange makes a system libertarian.' },
    ],
    acceptedAnswerSets: [['u32-b']],
    explanation: 'Socialism is a diverse family. Some models use markets while changing who owns or controls productive assets.',
    evidenceIds: ['SEP-SOCIALISM'],
  }, { blueprintBucket: 'economics_ownership', difficulty: 'intermediate', secondaryTags: ['market-socialism', 'markets', 'social-ownership'] }),
  asCandidate({
    id: 'U33', section: 'understand',
    prompt: 'Why is a worker cooperative not the same thing as redistribution?',
    options: [
      { id: 'u33-a', label: 'A cooperative changes business ownership; redistribution changes how income or wealth is shared.' },
      { id: 'u33-b', label: 'They are the same because both require identical tax rates.' },
      { id: 'u33-c', label: 'Redistribution changes voting rights inside firms, while cooperatives only change welfare benefits.' },
      { id: 'u33-d', label: 'Neither has any relation to economic institutions.' },
    ],
    acceptedAnswerSets: [['u33-a']],
    explanation: 'Cooperative ownership concerns governance and ownership of production; redistribution concerns the allocation of income or wealth after or alongside production.',
    evidenceIds: ['SEP-SOCIALISM', 'WVS-W7-DOCUMENTATION'],
  }, { blueprintBucket: 'economics_ownership', difficulty: 'advanced', secondaryTags: ['worker-cooperative', 'redistribution', 'ownership'] }),
  asCandidate({
    id: 'U34', section: 'understand',
    prompt: 'Why are elections alone not enough to establish liberal democracy?',
    options: [
      { id: 'u34-a', label: 'Because liberal democracy additionally requires one economic policy.' },
      { id: 'u34-b', label: 'Elections can exist without rights, fair competition or checks on rulers.' },
      { id: 'u34-c', label: 'Because liberal democracy does not use elections.' },
      { id: 'u34-d', label: 'Because only referendums are democratic.' },
    ],
    acceptedAnswerSets: [['u34-b']],
    explanation: 'Liberal democracy combines meaningful electoral competition with liberties, legality and constraints. Controlled elections can also exist under authoritarian rule.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY', 'VDEM-REGIMES-OF-THE-WORLD'],
  }, { blueprintBucket: 'misconceptions', difficulty: 'introductory', secondaryTags: ['elections', 'liberal-democracy', 'authoritarianism'] }),
  asCandidate({
    id: 'U35', section: 'understand',
    prompt: 'Why should one policy position not determine a person’s entire political tradition?',
    options: [
      { id: 'u35-a', label: 'Traditions combine several ideas and can share the same policy.' },
      { id: 'u35-b', label: 'Because policy positions never contain political information.' },
      { id: 'u35-c', label: 'Because only party membership can reveal political beliefs.' },
      { id: 'u35-d', label: 'Because every political tradition agrees on all policies.' },
    ],
    acceptedAnswerSets: [['u35-a']],
    explanation: 'Political traditions overlap and contain internal variation. Classification needs a broader pattern rather than a single shared policy.',
    evidenceIds: ['AAPOR-BEST-PRACTICES', 'SEP-LIBERALISM', 'SEP-CONSERVATISM', 'SEP-SOCIALISM'],
  }, { blueprintBucket: 'misconceptions', difficulty: 'introductory', secondaryTags: ['classification', 'single-issue', 'overlap'] }),
  asCandidate({
    id: 'U36', section: 'understand',
    prompt: 'Why can “left” and “right” mean somewhat different things across countries and periods?',
    options: [
      { id: 'u36-a', label: 'The labels describe changing political conflicts, not one timeless policy list.' },
      { id: 'u36-b', label: 'Because the terms have no political meaning at all.' },
      { id: 'u36-c', label: 'Because left always means national sovereignty and right always means internationalism.' },
      { id: 'u36-d', label: 'Because economic questions never influence left-right placement.' },
    ],
    acceptedAnswerSets: [['u36-a']],
    explanation: 'Left-right language compresses historically and nationally specific conflicts. Its content can shift even though it remains politically useful.',
    evidenceIds: ['CHES-2024', 'CHES-ECON-GALTAN', 'SEP-NATIONALISM'],
  }, { blueprintBucket: 'left_right_limits', difficulty: 'advanced', secondaryTags: ['left-right', 'context', 'political-history'] }),
  asCandidate({
    id: 'U37', section: 'understand',
    prompt: 'Why should economic and social-cultural positions be measured separately?',
    options: [
      { id: 'u37-a', label: 'People can combine economic views with different views on authority, tradition and personal freedom.' },
      { id: 'u37-b', label: 'Because economic views are objective while social views are not political.' },
      { id: 'u37-c', label: 'Because the two dimensions always move in opposite directions.' },
      { id: 'u37-d', label: 'Because only social-cultural issues matter in elections.' },
    ],
    acceptedAnswerSets: [['u37-a']],
    explanation: 'Economic and social-cultural views correlate imperfectly. Measuring them separately preserves combinations that a single line can hide.',
    evidenceIds: ['CHES-2024', 'CHES-ECON-GALTAN'],
  }, { blueprintBucket: 'left_right_limits', difficulty: 'intermediate', secondaryTags: ['economic-dimension', 'social-cultural-dimension', 'left-right'] }),
  asCandidate({
    id: 'U38', section: 'understand',
    prompt: 'What should Politangle do when a person’s answers point toward different traditions on different dimensions?',
    options: [
      { id: 'u38-a', label: 'Discard the answers that conflict with the strongest score.' },
      { id: 'u38-b', label: 'Show the mixed pattern and explain its different parts.' },
      { id: 'u38-c', label: 'Force the person into the nearest party label.' },
      { id: 'u38-d', label: 'Average everything into one number and hide the differences.' },
    ],
    acceptedAnswerSets: [['u38-b']],
    explanation: 'A mixed pattern is useful information. Politangle should show the combination instead of hiding it behind one cleaner label.',
    evidenceIds: ['CHES-2024', 'AAPOR-BEST-PRACTICES'],
  }, { blueprintBucket: 'multidimensional_patterns', difficulty: 'intermediate', secondaryTags: ['cross-pressure', 'mixed-pattern', 'interpretation'] }),
  asCandidate({
    id: 'U39', section: 'understand',
    prompt: 'If two political attitudes are often correlated, what can a questionnaire safely conclude about one individual?',
    options: [
      { id: 'u39-a', label: 'The individual must hold both attitudes.' },
      { id: 'u39-b', label: 'Measure them separately; a common pattern does not determine every person.' },
      { id: 'u39-c', label: 'Only the more common attitude needs to be measured.' },
      { id: 'u39-d', label: 'Correlation proves both attitudes have the same meaning.' },
    ],
    acceptedAnswerSets: [['u39-b']],
    explanation: 'A recurring association does not make two constructs identical or determine an individual answer. Separate measurement preserves real exceptions and combinations.',
    evidenceIds: ['AAPOR-BEST-PRACTICES', 'CHES-2024'],
  }, { blueprintBucket: 'multidimensional_patterns', difficulty: 'advanced', secondaryTags: ['correlation', 'individual-inference', 'measurement'] }),
  asCandidate({
    id: 'U40', section: 'understand',
    prompt: 'Why can two people with the same average political score still have meaningfully different profiles?',
    options: [
      { id: 'u40-a', label: 'Different high and low scores can produce the same average.' },
      { id: 'u40-b', label: 'They cannot; identical averages prove identical beliefs.' },
      { id: 'u40-c', label: 'Averages record party membership rather than answers.' },
      { id: 'u40-d', label: 'Only unanswered questions can produce equal averages.' },
    ],
    acceptedAnswerSets: [['u40-a']],
    explanation: 'Different combinations can produce the same average. Retaining dimension-level scores shows political structure that a single total loses.',
    evidenceIds: ['CHES-2024', 'AAPOR-BEST-PRACTICES'],
  }, { blueprintBucket: 'multidimensional_patterns', difficulty: 'introductory', secondaryTags: ['averaging', 'dimension-scores', 'profile-shape'] }),
] as const;

export const literacyMasterBankCandidates: readonly LiteracyQuestionRecord[] = [
  ...existingLiteracyCandidateRecords,
  ...addedClassifyCandidates,
  ...addedUnderstandCandidates,
];

export const classifyMasterBankCandidates = literacyMasterBankCandidates.filter((question) => question.section === 'classify');
export const understandMasterBankCandidates = literacyMasterBankCandidates.filter((question) => question.section === 'understand');
