import type { LiteracyQuestion } from './deep-engine';

export const literacyQuestions: readonly LiteracyQuestion[] = [
  {
    id: 'C1', section: 'classify',
    prompt: 'Most businesses stay private. The party also supports strong public services, worker protections and redistribution. Which tradition fits best?',
    options: [
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'communism', label: 'Communism' },
      { id: 'conservatism', label: 'Conservatism' },
    ],
    acceptedAnswerSets: [['social-democracy']],
    explanation: 'Modern social democracy usually keeps private businesses while using public services, rules and redistribution to reduce inequality.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'C2', section: 'classify',
    prompt: 'A movement wants major businesses owned by the public, workers or cooperatives. Which political family fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'socialism', label: 'Socialism' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['socialism']],
    explanation: 'Socialism gives a central role to public, cooperative or worker ownership, although socialist systems can be organized in different ways.',
    evidenceIds: ['SEP-SOCIALISM'],
  },
  {
    id: 'C3', section: 'classify',
    prompt: 'A philosophy puts personal freedom, private property and voluntary exchange first. It wants government power kept very limited. Which tradition fits best?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'christian-democracy', label: 'Christian democracy' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['libertarianism']],
    explanation: 'Libertarianism strongly protects personal freedom, private property and voluntary exchange while placing tight limits on government power.',
    evidenceIds: ['SEP-LIBERTARIANISM'],
  },
  {
    id: 'C4', section: 'classify',
    prompt: 'A movement trusts long-standing institutions, prefers gradual change and distrusts sweeping reforms designed on paper. Which tradition fits best?',
    options: [
      { id: 'socialism', label: 'Socialism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'populism', label: 'Populism' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'A major conservative tradition values continuity and long-standing institutions and is cautious about rapid, planned social change.',
    evidenceIds: ['SEP-CONSERVATISM'],
  },
  {
    id: 'C5', section: 'classify',
    prompt: 'A movement supports markets, gradual change and welfare programs that hold society together. Which broad tradition fits best?',
    options: [
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'communism', label: 'Communism' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'Conservatism does not always mean minimal government. It can support welfare and regulation to protect stability and social duty.',
    evidenceIds: ['SEP-CONSERVATISM', 'CHES-ECON-GALTAN'],
  },
  {
    id: 'C6', section: 'classify',
    prompt: 'A movement puts nature’s limits and long-term sustainability at the center of politics. Which tradition fits best?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'classical-liberalism', label: 'Classical liberalism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['green-politics']],
    explanation: 'Green politics makes ecological limits and sustainability central, often linking them to participation, local decision-making and social justice.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  },
  {
    id: 'C7', section: 'classify',
    prompt: 'A movement seeks a classless society with no state and no private ownership of productive businesses. Which tradition is this?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'communism', label: 'Communism' },
    ],
    acceptedAnswerSets: [['communism']],
    explanation: 'The Marxian communist ideal is a classless society without a state or private ownership of productive businesses.',
    evidenceIds: ['OXFORD-COMMUNISM', 'SEP-SOCIALISM'],
  },
  {
    id: 'C8', section: 'classify',
    prompt: 'A movement combines extreme nationalism, authoritarian rule and rejection of political opposition and liberal democracy. Which ideology fits best?',
    options: [
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['fascism']],
    explanation: 'Fascism combines extreme nationalism and authoritarian rule with rejection of liberal democracy. Nationalism or conservatism alone is not fascism.',
    evidenceIds: ['USHMM-FASCISM'],
  },
  {
    id: 'C9', section: 'classify',
    prompt: 'A movement values nations and their right to govern themselves but has no fixed economic policy. Which concept fits best?',
    options: [
      { id: 'populism', label: 'Populism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'social-democracy', label: 'Social democracy' },
    ],
    acceptedAnswerSets: [['nationalism']],
    explanation: 'Nationalism values nations and national self-government, but it can combine with different economic and social views.',
    evidenceIds: ['SEP-NATIONALISM'],
  },
  {
    id: 'C10', section: 'classify',
    prompt: 'A political family centers on freedom but disagrees about markets, welfare and the role of government. Which family is this?',
    options: [
      { id: 'liberalism', label: 'Liberalism' },
      { id: 'communism', label: 'Communism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'populism', label: 'Populism' },
    ],
    acceptedAnswerSets: [['liberalism']],
    explanation: 'Liberalism is a broad family centered on freedom, with real disagreements about markets, welfare and government.',
    evidenceIds: ['SEP-LIBERALISM'],
  },
  {
    id: 'C11', section: 'classify',
    prompt: 'A movement uses Christian social ideas, supports markets and welfare, and keeps decisions at the lowest capable level. Which tradition fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['christian-democracy']],
    explanation: 'Christian democracy combines Christian political ideas with markets, welfare and subsidiarity—keeping decisions at the lowest capable level.',
    evidenceIds: ['CAMBRIDGE-CHRISTIAN-DEMOCRACY', 'CAMBRIDGE-CD-RELIGIOUS-INSPIRATION', 'CAMBRIDGE-CD-SUBSIDIARITY'],
  },
  {
    id: 'C12', section: 'classify',
    prompt: 'A movement describes politics as ordinary people against a corrupt elite. Which concept fits best?',
    options: [
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'populism', label: 'Populism' },
      { id: 'liberalism', label: 'Liberalism' },
      { id: 'green-politics', label: 'Green politics' },
    ],
    acceptedAnswerSets: [['populism']],
    explanation: 'A common definition of populism sets ordinary, good people against a corrupt political establishment and emphasizes the people’s shared will.',
    evidenceIds: ['MUDDE-POPULISM'],
  },
  {
    id: 'C13', section: 'classify',
    prompt: 'A movement combines restrictive national membership, strong authority and people-versus-elite politics while still competing in elections. Which pattern fits best?',
    options: [
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'populist-radical-right', label: 'Populist radical right' },
      { id: 'social-democracy', label: 'Social democracy' },
    ],
    acceptedAnswerSets: [['populist-radical-right']],
    explanation: 'The populist radical right combines restrictive national membership, strong authority and people-versus-elite politics while still using elections.',
    evidenceIds: ['MUDDE-RADICAL-RIGHT', 'PIRRO-FAR-RIGHT'],
  },
  {
    id: 'C14', section: 'classify',
    prompt: 'A far-right movement openly rejects democracy itself. Which label fits best?',
    options: [
      { id: 'extreme-right', label: 'Extreme right' },
      { id: 'radical-right', label: 'Radical right' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'populism', label: 'Populism' },
    ],
    acceptedAnswerSets: [['extreme-right']],
    explanation: 'Researchers often use open rejection of democracy as a key difference between the extreme right and radical right.',
    evidenceIds: ['PIRRO-FAR-RIGHT'],
  },
  {
    id: 'C15', section: 'classify',
    prompt: 'A system combines real elections, civil rights, rule of law and independent checks on leaders. Which system is this?',
    options: [
      { id: 'majoritarian-democracy', label: 'Elections with no limits on the winner' },
      { id: 'one-party-rule', label: 'One-party rule' },
      { id: 'authoritarianism', label: 'Authoritarian government' },
      { id: 'liberal-democracy', label: 'Liberal democracy' },
    ],
    acceptedAnswerSets: [['liberal-democracy']],
    explanation: 'Liberal democracy combines real electoral competition with civil rights, rule of law and checks on government power.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'C16', section: 'classify',
    prompt: 'A center-left party supports universal healthcare, worker protections and progressive taxes while keeping most businesses private. Which tradition fits best?',
    options: [
      { id: 'socialism', label: 'Socialism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'communism', label: 'Communism' },
    ],
    acceptedAnswerSets: [['social-democracy']],
    explanation: 'Modern social democracy regulates markets and redistributes income while keeping most businesses privately owned.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'C17', section: 'classify',
    prompt: 'A movement wants more worker, cooperative or public ownership while protecting elections, rights and opposition parties. Which family fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'socialism', label: 'Socialism' },
      { id: 'fascism', label: 'Fascism' },
    ],
    acceptedAnswerSets: [['socialism']],
    explanation: 'Socialism can be democratic. More social ownership does not automatically mean one-party or authoritarian rule.',
    evidenceIds: ['SEP-SOCIALISM', 'VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'C18', section: 'classify',
    prompt: 'A movement says rich societies may need less consumption because cleaner technology alone cannot solve ecological limits. Which tradition fits best?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'conservatism', label: 'Conservatism' },
    ],
    acceptedAnswerSets: [['green-politics']],
    explanation: 'Green politics gives special weight to ecological limits and may support deeper changes to production and consumption.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  },
  {
    id: 'C19', section: 'classify',
    prompt: 'A movement wants government to protect rights and contracts but otherwise interfere as little as possible. Which tradition fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'christian-democracy', label: 'Christian democracy' },
      { id: 'socialism', label: 'Socialism' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['libertarianism']],
    explanation: 'Libertarianism gives unusually strong priority to personal freedom and voluntary exchange and seeks a narrow role for government.',
    evidenceIds: ['SEP-LIBERTARIANISM'],
  },
  {
    id: 'C20', section: 'classify',
    prompt: 'A movement values continuity, order and long-standing institutions while accepting elections, opposition parties and constitutional limits. Which tradition fits best?',
    options: [
      { id: 'fascism', label: 'Fascism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'communism', label: 'Communism' },
      { id: 'populist-radical-right', label: 'Populist radical right' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'Conservatism can value order and continuity while still accepting rights, opposition parties and constitutional democracy.',
    evidenceIds: ['SEP-CONSERVATISM', 'VDEM-LIBERAL-DEMOCRACY'],
  },

  {
    id: 'U1', section: 'understand',
    prompt: 'Which description of populism is most accurate?',
    options: [
      { id: 'u1-a', label: 'It is only a way of speaking, with no shared political idea.' },
      { id: 'u1-b', label: 'It is a complete economic program based on state ownership.' },
      { id: 'u1-c', label: 'It sets ordinary people against a corrupt establishment and can join different ideologies.' },
      { id: 'u1-d', label: 'It is the same as direct democracy and rejects all representatives.' },
    ],
    acceptedAnswerSets: [['u1-c']],
    explanation: 'Populism has a core people-versus-establishment idea, but it can combine with left-wing, right-wing or other political programs.',
    evidenceIds: ['MUDDE-POPULISM'],
  },
  {
    id: 'U2', section: 'understand',
    prompt: 'What does nationalism tell you about a movement?',
    options: [
      { id: 'u2-a', label: 'It places the movement on the economic right.' },
      { id: 'u2-b', label: 'It values the nation; its other views may be left or right.' },
      { id: 'u2-c', label: 'It shows that border control is its only concern.' },
      { id: 'u2-d', label: 'It places the movement on the traditional social right.' },
    ],
    acceptedAnswerSets: [['u2-b']],
    explanation: 'Nationalism values nations and self-government, but it has appeared in conservative, liberal, socialist and other forms.',
    evidenceIds: ['SEP-NATIONALISM'],
  },
  {
    id: 'U3', section: 'understand',
    prompt: 'What makes a democracy liberal, not only electoral?',
    options: [
      { id: 'u3-a', label: 'Regular elections are enough.' },
      { id: 'u3-b', label: 'Private property and markets are enough.' },
      { id: 'u3-c', label: 'Courts and lawmakers must not limit the elected leader.' },
      { id: 'u3-d', label: 'Elections work alongside civil rights, rule of law and checks on leaders.' },
    ],
    acceptedAnswerSets: [['u3-d']],
    explanation: 'Liberal democracy adds civil rights, rule of law and checks on leaders to real electoral competition.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'U4', section: 'understand',
    prompt: 'What most clearly separates the extreme right from the radical right?',
    options: [
      { id: 'u4-a', label: 'The extreme right is simply more nationalist.' },
      { id: 'u4-b', label: 'The difference is mainly their preferred tax rate.' },
      { id: 'u4-c', label: 'The extreme right rejects democracy; the radical right may still accept elections.' },
      { id: 'u4-d', label: 'The radical right is populist, while the extreme right never is.' },
    ],
    acceptedAnswerSets: [['u4-c']],
    explanation: 'Both sit within the far right, but open rejection of democracy is a key sign of the extreme right.',
    evidenceIds: ['PIRRO-FAR-RIGHT', 'MUDDE-RADICAL-RIGHT'],
  },
  {
    id: 'U5', section: 'understand',
    prompt: 'Why does liberalism not have one fixed economic program?',
    options: [
      { id: 'u5-a', label: 'All liberals want minimal government, but at different speeds.' },
      { id: 'u5-b', label: 'Liberalism concerns elections, not personal or economic freedom.' },
      { id: 'u5-c', label: 'Only supporters of welfare belong to the liberal family.' },
      { id: 'u5-d', label: 'Liberals value freedom but disagree about markets, welfare and government.' },
    ],
    acceptedAnswerSets: [['u5-d']],
    explanation: 'Liberal traditions value freedom but disagree about property, markets, welfare and the proper role of government.',
    evidenceIds: ['SEP-LIBERALISM'],
  },
  {
    id: 'U6', section: 'understand',
    prompt: 'Which description of socialism is most accurate?',
    options: [
      { id: 'u6-a', label: 'It is any system with high welfare spending.' },
      { id: 'u6-b', label: 'It is a broad family centered on social ownership or control.' },
      { id: 'u6-c', label: 'It is any system with central economic planning.' },
      { id: 'u6-d', label: 'It is any system led by one political party.' },
    ],
    acceptedAnswerSets: [['u6-b']],
    explanation: 'Socialism is a broad family with several forms of social ownership and both democratic and non-democratic histories.',
    evidenceIds: ['SEP-SOCIALISM'],
  },
  {
    id: 'U7', section: 'understand',
    prompt: 'What is the clearest difference between modern social democracy and socialism?',
    options: [
      { id: 'u7-a', label: 'Social democracy usually keeps private ownership; socialism gives social ownership a larger role.' },
      { id: 'u7-b', label: 'The main difference is whether taxes are moderate or very high.' },
      { id: 'u7-c', label: 'Social democracy accepts elections, while socialism rejects them.' },
      { id: 'u7-d', label: 'Socialism supports public services, while social democracy does not.' },
    ],
    acceptedAnswerSets: [['u7-a']],
    explanation: 'Modern social democracy usually reforms an economy with private businesses. Socialism gives public, cooperative or worker ownership a larger role.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'U8', section: 'understand',
    prompt: 'Can conservatism support a welfare state?',
    options: [
      { id: 'u8-a', label: 'Only when every benefit is privately delivered.' },
      { id: 'u8-b', label: 'No; conservatism always requires minimal government.' },
      { id: 'u8-c', label: 'Yes; welfare can support duty, stability and social unity.' },
      { id: 'u8-d', label: 'Only when major industries are also publicly owned.' },
    ],
    acceptedAnswerSets: [['u8-c']],
    explanation: 'Conservatism has no single welfare position. Some conservatives support social programs because they value duty, stability and social unity.',
    evidenceIds: ['SEP-CONSERVATISM', 'CHES-ECON-GALTAN'],
  },
  {
    id: 'U9', section: 'understand',
    prompt: 'What makes Christian democracy more than markets plus welfare?',
    options: [
      { id: 'u9-a', label: 'Its support for markets and generous welfare.' },
      { id: 'u9-b', label: 'Its Christian social ideas and support for local decisions.' },
      { id: 'u9-c', label: 'Its support for families and traditional values.' },
      { id: 'u9-d', label: 'Its support for European political cooperation.' },
    ],
    acceptedAnswerSets: [['u9-b']],
    explanation: 'Other traditions also mix markets and welfare. Christian social ideas and keeping suitable decisions local make this tradition more specific.',
    evidenceIds: ['CAMBRIDGE-CHRISTIAN-DEMOCRACY', 'CAMBRIDGE-CD-RELIGIOUS-INSPIRATION', 'CAMBRIDGE-CD-SUBSIDIARITY'],
  },
  {
    id: 'U10', section: 'understand',
    prompt: 'What most clearly separates fascism from ordinary conservatism or nationalism?',
    options: [
      { id: 'u10-a', label: 'Strong patriotism and strict law-and-order policies.' },
      { id: 'u10-b', label: 'Government coordination of business, even with democracy protected.' },
      { id: 'u10-c', label: 'Extreme nationalism, authoritarian rule and rejection of rights and democratic opposition.' },
      { id: 'u10-d', label: 'Nationalism combined with a larger welfare state.' },
    ],
    acceptedAnswerSets: [['u10-c']],
    explanation: 'Fascism is not another word for patriotism or nationalism. It combines extreme nationalism, authoritarian rule and rejection of liberal democracy.',
    evidenceIds: ['USHMM-FASCISM'],
  },
  {
    id: 'U11', section: 'understand',
    prompt: 'Which description best matches the communist ideal described by Marx?',
    options: [
      { id: 'u11-a', label: 'A classless society without a state or privately owned production.' },
      { id: 'u11-b', label: 'A permanent one-party state with central planning.' },
      { id: 'u11-c', label: 'Private businesses that share their profits more equally.' },
      { id: 'u11-d', label: 'A capitalist economy with strong welfare programs.' },
    ],
    acceptedAnswerSets: [['u11-a']],
    explanation: 'In the Marxian ideal, communism is classless and has no state or private ownership of productive businesses.',
    evidenceIds: ['OXFORD-COMMUNISM'],
  },
  {
    id: 'U12', section: 'understand',
    prompt: 'Why are public services and public ownership different questions?',
    options: [
      { id: 'u12-a', label: 'Government funding and ownership always come together.' },
      { id: 'u12-b', label: 'Government can fund services delivered by different kinds of organizations.' },
      { id: 'u12-c', label: 'Ownership matters for factories but not for public services.' },
      { id: 'u12-d', label: 'Public services and public ownership are the same arrangement.' },
    ],
    acceptedAnswerSets: [['u12-b']],
    explanation: 'Government can fund or guarantee a service while public, private, cooperative or mixed organizations provide it.',
    evidenceIds: ['WVS-W7-DOCUMENTATION', 'ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'U13', section: 'understand',
    prompt: 'What does populism tell you about risks to democracy?',
    options: [
      { id: 'u13-a', label: 'Every populist government will become authoritarian.' },
      { id: 'u13-b', label: 'Winning an election removes later democratic risks.' },
      { id: 'u13-c', label: 'Risk rises when populists reject opposition and democratic rules.' },
      { id: 'u13-d', label: 'Risk rises mainly when populists regulate markets.' },
    ],
    acceptedAnswerSets: [['u13-c']],
    explanation: 'Populism alone does not prove authoritarianism. Rejecting legitimate opposition and weakening democratic rules are clearer warning signs.',
    evidenceIds: ['VDEM-POPULISM-AUTOCRATIZATION', 'IDEA-POPULISM-DEMOCRACY'],
  },
  {
    id: 'U14', section: 'understand',
    prompt: 'Why should national self-government and national membership be measured separately?',
    options: [
      { id: 'u14-a', label: 'Self-government requires fewer rights for naturalized citizens.' },
      { id: 'u14-b', label: 'Self-government can include naturalized citizens as full members.' },
      { id: 'u14-c', label: 'Self-government concerns immigration; membership concerns trade.' },
      { id: 'u14-d', label: 'Self-government and membership are the same political idea.' },
    ],
    acceptedAnswerSets: [['u14-b']],
    explanation: 'Self-government asks who has final political authority. Membership asks who fully belongs. A person can answer these questions differently.',
    evidenceIds: ['SEP-NATIONALISM'],
  },
  {
    id: 'U15', section: 'understand',
    prompt: 'What makes green politics broader than environmental regulation?',
    options: [
      { id: 'u15-a', label: 'It means supporting stronger environmental rules.' },
      { id: 'u15-b', label: 'It makes ecological limits central to democracy, society and justice.' },
      { id: 'u15-c', label: 'It means replacing every market with government planning.' },
      { id: 'u15-d', label: 'It focuses on conservation rather than society or democracy.' },
    ],
    acceptedAnswerSets: [['u15-b']],
    explanation: 'Green politics treats ecological limits and sustainability as central political concerns, not just one policy area among many.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  },
  {
    id: 'U16', section: 'understand',
    prompt: 'How does libertarianism fit within the wider liberal family?',
    options: [
      { id: 'u16-a', label: 'It strongly protects personal freedom, property and voluntary exchange from government power.' },
      { id: 'u16-b', label: 'It concerns lifestyle freedom, not property or markets.' },
      { id: 'u16-c', label: 'It uses redistribution as its main route to freedom.' },
      { id: 'u16-d', label: 'It places tradition above individual choice.' },
    ],
    acceptedAnswerSets: [['u16-a']],
    explanation: 'Libertarianism belongs to the wider liberal family but places especially tight limits on government interference with people and property.',
    evidenceIds: ['SEP-LIBERTARIANISM', 'SEP-LIBERALISM'],
  },
  {
    id: 'U17', section: 'understand',
    prompt: 'Does supporting redistribution by itself make someone socialist?',
    options: [
      { id: 'u17-a', label: 'Yes; enough redistribution makes ownership irrelevant.' },
      { id: 'u17-b', label: 'Yes; taxation and social ownership are the same.' },
      { id: 'u17-c', label: 'No; a country can redistribute income while businesses remain mostly private.' },
      { id: 'u17-d', label: 'No; socialism concerns central planning only.' },
    ],
    acceptedAnswerSets: [['u17-c']],
    explanation: 'Redistribution and ownership are different. A country can redistribute substantial income while most businesses remain privately owned.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM', 'WVS-W7-DOCUMENTATION'],
  },
  {
    id: 'U18', section: 'understand',
    prompt: 'What does subsidiarity mean?',
    options: [
      { id: 'u18-a', label: 'National government should control every major decision.' },
      { id: 'u18-b', label: 'Decisions should stay at the lowest level that works.' },
      { id: 'u18-c', label: 'Private organizations should replace all levels of government.' },
      { id: 'u18-d', label: 'Regional government should control every major decision.' },
    ],
    acceptedAnswerSets: [['u18-b']],
    explanation: 'Subsidiarity keeps decisions at the lowest level that can handle them well, while allowing higher levels to help when needed.',
    evidenceIds: ['CAMBRIDGE-CD-SUBSIDIARITY'],
  },
  {
    id: 'U19', section: 'understand',
    prompt: 'What separates ordinary conservatism from authoritarian politics?',
    options: [
      { id: 'u19-a', label: 'Wanting law and order usually means wanting fewer checks on leaders.' },
      { id: 'u19-b', label: 'Conservatism can value order while accepting rights, elections and limits on leaders.' },
      { id: 'u19-c', label: 'Traditional social values are the main sign of authoritarianism.' },
      { id: 'u19-d', label: 'Authoritarianism is simply stronger conservatism.' },
    ],
    acceptedAnswerSets: [['u19-b']],
    explanation: 'Valuing order or continuity does not by itself mean rejecting rights, opposition parties, elections or limits on leaders.',
    evidenceIds: ['SEP-CONSERVATISM', 'VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'U20', section: 'understand',
    prompt: 'What is the best way to understand someone’s wider political outlook from a questionnaire?',
    options: [
      { id: 'u20-a', label: 'Use only the issue on which the person feels strongest.' },
      { id: 'u20-b', label: 'Look for a pattern across several separate dimensions.' },
      { id: 'u20-c', label: 'Use only the person’s own left-right label.' },
      { id: 'u20-d', label: 'Average every answer into one left-right number.' },
    ],
    acceptedAnswerSets: [['u20-b']],
    explanation: 'Political traditions combine several ideas. A pattern across separate dimensions is more useful than one answer or one left-right number.',
    evidenceIds: ['AAPOR-BEST-PRACTICES', 'SEP-LIBERALISM', 'SEP-CONSERVATISM', 'SEP-SOCIALISM'],
  },
] as const;
