import type { LiteracyQuestion } from './deep-engine';

export const literacyQuestions: readonly LiteracyQuestion[] = [
  {
    id: 'C1', section: 'classify',
    prompt: 'A movement keeps most firms privately owned but supports strong social insurance, public services, labor protections and redistribution to reduce inequality. Which tradition fits best?',
    options: [
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'communism', label: 'Communism' },
      { id: 'conservatism', label: 'Conservatism' },
    ],
    acceptedAnswerSets: [['social-democracy']],
    explanation: 'Modern social democracy generally keeps a predominantly capitalist economy while using regulation, public services, social insurance and redistribution to pursue social justice.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'C2', section: 'classify',
    prompt: 'A movement wants a substantial share of productive assets to be publicly, cooperatively or worker controlled rather than mainly owned by private shareholders. Which broad family fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'socialism', label: 'Socialism' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['socialism']],
    explanation: 'Socialism is a broad family distinguished in large part by social rather than predominantly private control of productive assets, although its institutional forms vary widely.',
    evidenceIds: ['SEP-SOCIALISM'],
  },
  {
    id: 'C3', section: 'classify',
    prompt: 'A political philosophy makes individual liberty central, strongly protects voluntary exchange and private property, and is highly skeptical of coercive state intervention. Which tradition fits best?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'christian-democracy', label: 'Christian democracy' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['libertarianism']],
    explanation: 'Libertarianism gives especially strong priority to individual freedom, voluntary exchange and private property while seeking tight limits on coercive state power.',
    evidenceIds: ['SEP-LIBERTARIANISM'],
  },
  {
    id: 'C4', section: 'classify',
    prompt: 'A movement values inherited institutions and living traditions, prefers gradual change and is skeptical of sweeping reforms designed from abstract principles. Which tradition fits best?',
    options: [
      { id: 'socialism', label: 'Socialism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'populism', label: 'Populism' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'A major conservative tradition emphasizes continuity, inherited institutions and skepticism toward rapid or abstractly designed social reform.',
    evidenceIds: ['SEP-CONSERVATISM'],
  },
  {
    id: 'C5', section: 'classify',
    prompt: 'A movement supports private property and markets, prefers gradual social change, and accepts welfare programs or regulation when they help preserve social cohesion. Which broad tradition fits best?',
    options: [
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'communism', label: 'Communism' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'Conservatism need not mean a minimal state. Conservative traditions can accept social obligations, welfare institutions and regulation while retaining private property, continuity and gradual change.',
    evidenceIds: ['SEP-CONSERVATISM', 'CHES-ECON-GALTAN'],
  },
  {
    id: 'C6', section: 'classify',
    prompt: 'A movement treats ecological limits and a sustainable society as central political concerns and connects them to decentralization, grassroots democracy and social justice. Which tradition fits best?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'classical-liberalism', label: 'Classical liberalism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['green-politics']],
    explanation: 'Green political thought places ecological limits and sustainability near the center and commonly links them to grassroots democracy, decentralization and social justice.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  },
  {
    id: 'C7', section: 'classify',
    prompt: 'In its Marxian ideal form, a movement seeks a classless and ultimately stateless society with collective appropriation and no private ownership of the means of production. Which tradition is described?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'communism', label: 'Communism' },
    ],
    acceptedAnswerSets: [['communism']],
    explanation: 'The Marxian communist ideal is classless and stateless and rejects private ownership of the means of production; this should not be collapsed into modern social democracy.',
    evidenceIds: ['OXFORD-COMMUNISM', 'SEP-SOCIALISM'],
  },
  {
    id: 'C8', section: 'classify',
    prompt: 'A movement is ultranationalist and authoritarian, rejects political pluralism and individual rights, and opposes representative liberal democracy. Which ideology fits best?',
    options: [
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['fascism']],
    explanation: 'Fascism combines ultranationalism and authoritarianism with rejection of pluralist liberal democracy; nationalism or conservatism alone does not amount to fascism.',
    evidenceIds: ['USHMM-FASCISM'],
  },
  {
    id: 'C9', section: 'classify',
    prompt: 'A movement says the nation has special political value and should possess substantial collective self-determination, without specifying a fixed position on markets or welfare. Which concept fits best?',
    options: [
      { id: 'populism', label: 'Populism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'social-democracy', label: 'Social democracy' },
    ],
    acceptedAnswerSets: [['nationalism']],
    explanation: 'Nationalism gives political importance to nations and national self-determination but can combine with different economic and social ideologies.',
    evidenceIds: ['SEP-NATIONALISM'],
  },
  {
    id: 'C10', section: 'classify',
    prompt: 'A political family treats individual liberty as a central value but contains major internal disagreements about markets, social provision and what government should do to secure freedom. Which family fits best?',
    options: [
      { id: 'liberalism', label: 'Liberalism' },
      { id: 'communism', label: 'Communism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'populism', label: 'Populism' },
    ],
    acceptedAnswerSets: [['liberalism']],
    explanation: 'Liberalism is a diverse family united by the political importance of liberty while containing substantial disagreements about the meaning of freedom and the proper role of government.',
    evidenceIds: ['SEP-LIBERALISM'],
  },
  {
    id: 'C11', section: 'classify',
    prompt: 'A movement explicitly draws on Christian social teaching, supports a social-market economy and welfare institutions, and emphasizes subsidiarity rather than concentrating every responsibility in the state. Which tradition fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'christian-democracy', label: 'Christian democracy' },
    ],
    acceptedAnswerSets: [['christian-democracy']],
    explanation: 'Christian democracy is distinguished not only by social-market economics but also by Christian political inspiration and principles such as subsidiarity.',
    evidenceIds: ['CAMBRIDGE-CHRISTIAN-DEMOCRACY', 'CAMBRIDGE-CD-RELIGIOUS-INSPIRATION', 'CAMBRIDGE-CD-SUBSIDIARITY'],
  },
  {
    id: 'C12', section: 'classify',
    prompt: 'A movement frames politics as a struggle between ordinary people and a self-serving political establishment and says government should express the people’s common will. Which concept fits best?',
    options: [
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'populism', label: 'Populism' },
      { id: 'liberalism', label: 'Liberalism' },
      { id: 'green-politics', label: 'Green politics' },
    ],
    acceptedAnswerSets: [['populism']],
    explanation: 'A widely used definition of populism centers on a moral opposition between the people and an establishment and on the claim that politics should express the people’s general will.',
    evidenceIds: ['MUDDE-POPULISM'],
  },
  {
    id: 'C13', section: 'classify',
    prompt: 'A movement combines restrictive national membership, strong law-and-order authority and populist people-versus-establishment politics while still competing in elections. Which pattern fits best?',
    options: [
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'fascism', label: 'Fascism' },
      { id: 'populist-radical-right', label: 'Populist radical right' },
      { id: 'social-democracy', label: 'Social democracy' },
    ],
    acceptedAnswerSets: [['populist-radical-right']],
    explanation: 'Comparative scholarship commonly characterizes the populist radical right through the combination of nativism, authoritarianism and populism while distinguishing it from explicitly anti-democratic extreme-right politics.',
    evidenceIds: ['MUDDE-RADICAL-RIGHT', 'PIRRO-FAR-RIGHT'],
  },
  {
    id: 'C14', section: 'classify',
    prompt: 'A movement openly rejects democracy itself rather than merely criticizing liberal checks, while belonging to the broader family of far-right politics. Which label fits best?',
    options: [
      { id: 'extreme-right', label: 'Extreme right' },
      { id: 'radical-right', label: 'Radical right' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'populism', label: 'Populism' },
    ],
    acceptedAnswerSets: [['extreme-right']],
    explanation: 'A common scholarly distinction places radical and extreme right under the far-right umbrella and uses explicit anti-democracy as a key marker of the extreme right.',
    evidenceIds: ['PIRRO-FAR-RIGHT'],
  },
  {
    id: 'C15', section: 'classify',
    prompt: 'A political system combines competitive elections with civil liberties, rule of law and institutional checks that can constrain elected executives. Which system is described?',
    options: [
      { id: 'majoritarian-democracy', label: 'Unconstrained majoritarian democracy' },
      { id: 'one-party-rule', label: 'One-party rule' },
      { id: 'authoritarianism', label: 'Authoritarian government' },
      { id: 'liberal-democracy', label: 'Liberal democracy' },
    ],
    acceptedAnswerSets: [['liberal-democracy']],
    explanation: 'Liberal democracy adds civil liberties, rule of law and checks and balances to the electoral component of democracy.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'C16', section: 'classify',
    prompt: 'A movement wants capitalism regulated and inequality reduced through taxes, transfers and public services, but does not seek to replace predominantly private ownership of productive assets. Which tradition fits best?',
    options: [
      { id: 'socialism', label: 'Socialism' },
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'communism', label: 'Communism' },
    ],
    acceptedAnswerSets: [['social-democracy']],
    explanation: 'The clearest distinction here is ownership: modern social democracy generally regulates and redistributes within a predominantly capitalist ownership structure rather than replacing it.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'C17', section: 'classify',
    prompt: 'A democratic movement wants substantially more worker, cooperative or public ownership while retaining competitive elections, civil liberties and political pluralism. Which broad economic family fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'socialism', label: 'Socialism' },
      { id: 'fascism', label: 'Fascism' },
    ],
    acceptedAnswerSets: [['socialism']],
    explanation: 'Socialism can take democratic and pluralist forms; a commitment to substantially more social ownership does not by itself imply one-party or authoritarian rule.',
    evidenceIds: ['SEP-SOCIALISM', 'VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'C18', section: 'classify',
    prompt: 'A movement argues that wealthy societies may sometimes need lower material growth or consumption because ecological limits cannot always be solved by cleaner technology alone. Which tradition fits best?',
    options: [
      { id: 'green-politics', label: 'Green politics' },
      { id: 'libertarianism', label: 'Libertarianism' },
      { id: 'nationalism', label: 'Nationalism' },
      { id: 'conservatism', label: 'Conservatism' },
    ],
    acceptedAnswerSets: [['green-politics']],
    explanation: 'Green political thought gives distinctive weight to ecological limits and can support deeper changes to production and consumption rather than relying only on incremental technological adjustment.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  },
  {
    id: 'C19', section: 'classify',
    prompt: 'A movement wants government to protect basic rights and contracts but otherwise leave adults, markets and voluntary associations as free as possible from coercive intervention. Which tradition fits best?',
    options: [
      { id: 'social-democracy', label: 'Social democracy' },
      { id: 'christian-democracy', label: 'Christian democracy' },
      { id: 'socialism', label: 'Socialism' },
      { id: 'libertarianism', label: 'Libertarianism' },
    ],
    acceptedAnswerSets: [['libertarianism']],
    explanation: 'Libertarianism gives unusually strong priority to individual liberty and voluntary exchange and generally seeks a narrower domain for coercive government action.',
    evidenceIds: ['SEP-LIBERTARIANISM'],
  },
  {
    id: 'C20', section: 'classify',
    prompt: 'A movement stresses continuity, social order and inherited institutions, but does not reject elections, pluralism or constitutional government. Which broad tradition fits best?',
    options: [
      { id: 'fascism', label: 'Fascism' },
      { id: 'conservatism', label: 'Conservatism' },
      { id: 'communism', label: 'Communism' },
      { id: 'populist-radical-right', label: 'Populist radical right' },
    ],
    acceptedAnswerSets: [['conservatism']],
    explanation: 'Conservatism can emphasize order, continuity and inherited institutions while remaining fully compatible with constitutional and competitive democratic politics.',
    evidenceIds: ['SEP-CONSERVATISM', 'VDEM-LIBERAL-DEMOCRACY'],
  },

  {
    id: 'U1', section: 'understand',
    prompt: 'Which statement about populism is most accurate?',
    options: [
      { id: 'u1-a', label: 'Populism is a complete right-wing ideology with a fixed economic and social program.' },
      { id: 'u1-b', label: 'Populism is a complete left-wing ideology with a fixed economic and social program.' },
      { id: 'u1-c', label: 'Populism is usually treated as a thin-centered ideology that can attach to different host ideologies.' },
      { id: 'u1-d', label: 'Populism is only a campaign style and has no recurring ideological claims about political conflict.' },
    ],
    acceptedAnswerSets: [['u1-c']],
    explanation: 'A widely used academic definition treats populism as thin-centered, meaning it can combine with more complete left- or right-wing host ideologies.',
    evidenceIds: ['MUDDE-POPULISM'],
  },
  {
    id: 'U2', section: 'understand',
    prompt: 'Which statement about nationalism is best supported?',
    options: [
      { id: 'u2-a', label: 'Nationalism is simply another name for fascism and therefore rejects representative democracy by definition.' },
      { id: 'u2-b', label: 'Nationalism can combine with several political traditions, so other beliefs are needed to place it left or right.' },
      { id: 'u2-c', label: 'Nationalism is inherently right-wing because national self-determination always requires conservative economic and social policy.' },
      { id: 'u2-d', label: 'Nationalism has no ideological content because support for national self-determination is politically neutral in every context.' },
    ],
    acceptedAnswerSets: [['u2-b']],
    explanation: 'Nationalism gives political significance to nations and self-determination but has appeared in conservative, liberal, socialist and other forms.',
    evidenceIds: ['SEP-NATIONALISM'],
  },
  {
    id: 'U3', section: 'understand',
    prompt: 'What distinguishes liberal democracy from the minimal idea that elections are held?',
    options: [
      { id: 'u3-a', label: 'Competitive elections are sufficient, so courts, civil liberties and limits on executive power are optional additions.' },
      { id: 'u3-b', label: 'Private ownership of every major industry is required in addition to elections for a system to qualify.' },
      { id: 'u3-c', label: 'A single elected majority must be able to govern without institutional obstruction for democracy to remain meaningful.' },
      { id: 'u3-d', label: 'Civil liberties, rule of law and institutional checks on executive power are central alongside competitive elections.' },
    ],
    acceptedAnswerSets: [['u3-d']],
    explanation: 'Liberal-democracy measures include civil liberties, rule of law and checks and balances in addition to the electoral component of democracy.',
    evidenceIds: ['VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'U4', section: 'understand',
    prompt: 'In comparative far-right scholarship, what most clearly distinguishes the extreme right from the radical right?',
    options: [
      { id: 'u4-a', label: 'The extreme right is defined mainly by higher taxes, while the radical right is defined mainly by lower taxes.' },
      { id: 'u4-b', label: 'The radical right rejects elections entirely, while the extreme right normally accepts competitive procedural democracy.' },
      { id: 'u4-c', label: 'The extreme right is explicitly anti-democratic, while the radical right can accept elections despite illiberal positions.' },
      { id: 'u4-d', label: 'The difference is mainly environmental policy, with the radical right consistently prioritizing ecological protection over growth.' },
    ],
    acceptedAnswerSets: [['u4-c']],
    explanation: 'A common distinction places both under the far-right umbrella but uses explicit anti-democracy as a key marker of the extreme right.',
    evidenceIds: ['PIRRO-FAR-RIGHT', 'MUDDE-RADICAL-RIGHT'],
  },
  {
    id: 'U5', section: 'understand',
    prompt: 'Which statement about liberalism is most accurate?',
    options: [
      { id: 'u5-a', label: 'Liberalism has one fixed economic program, and all liberal traditions prescribe essentially the same role for government.' },
      { id: 'u5-b', label: 'Liberalism treats individual liberty as politically secondary and gives inherited social hierarchy priority over personal freedom.' },
      { id: 'u5-c', label: 'Liberalism and socialism are interchangeable labels because both traditions ultimately require the same model of ownership.' },
      { id: 'u5-d', label: 'Liberalism is a diverse family centered on liberty, with important disagreements about freedom and government’s proper role.' },
    ],
    acceptedAnswerSets: [['u5-d']],
    explanation: 'Liberalism is a family of views united by the importance of liberty but divided over what liberty requires and how government should support it.',
    evidenceIds: ['SEP-LIBERALISM'],
  },
  {
    id: 'U6', section: 'understand',
    prompt: 'Which statement about socialism is most accurate?',
    options: [
      { id: 'u6-a', label: 'Socialism necessarily requires a one-party state and therefore excludes competitive democracy in every institutional form.' },
      { id: 'u6-b', label: 'Socialism is a broad family with several models of social ownership and both democratic and non-democratic historical forms.' },
      { id: 'u6-c', label: 'Every welfare state is socialist because public spending alone determines whether productive assets are socially owned.' },
      { id: 'u6-d', label: 'Socialism requires productive assets to remain predominantly privately owned while government limits itself to market regulation.' },
    ],
    acceptedAnswerSets: [['u6-b']],
    explanation: 'Socialism is a broad family with multiple institutional designs and models of social ownership; it cannot be reduced to one historical regime type.',
    evidenceIds: ['SEP-SOCIALISM'],
  },
  {
    id: 'U7', section: 'understand',
    prompt: 'What is the clearest general distinction between modern social democracy and socialism in this quiz?',
    options: [
      { id: 'u7-a', label: 'Social democracy generally keeps predominantly private ownership, while socialism gives social ownership a more central role.' },
      { id: 'u7-b', label: 'Social democracy rejects welfare provision, while socialism is defined mainly by supporting public schools and health services.' },
      { id: 'u7-c', label: 'Social democracy rejects elections, while socialism is defined by accepting competitive multiparty democracy and constitutional rights.' },
      { id: 'u7-d', label: 'Social democracy is inherently nationalist, while socialism is inherently internationalist regardless of other political commitments.' },
    ],
    acceptedAnswerSets: [['u7-a']],
    explanation: 'Modern social democracy usually regulates and redistributes within a predominantly capitalist ownership structure, whereas social ownership is more central to socialism.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'U8', section: 'understand',
    prompt: 'Which statement about conservatism and the welfare state is best supported?',
    options: [
      { id: 'u8-a', label: 'Any support for welfare programs automatically places a movement outside conservatism and inside social democracy.' },
      { id: 'u8-b', label: 'Conservatism requires abolishing public social provision because private responsibility is its defining principle in every form.' },
      { id: 'u8-c', label: 'Conservative traditions can accept welfare or regulation when these are justified by order, obligation, continuity or social cohesion.' },
      { id: 'u8-d', label: 'A conservative movement must adopt socialist ownership whenever it accepts public spending on social insurance or health care.' },
    ],
    acceptedAnswerSets: [['u8-c']],
    explanation: 'Conservatism is not defined by a single welfare-state position; traditions centered on continuity and social obligation can accommodate substantial social provision.',
    evidenceIds: ['SEP-CONSERVATISM', 'CHES-ECON-GALTAN'],
  },
  {
    id: 'U9', section: 'understand',
    prompt: 'What makes Christian democracy more than a generic label for market economics plus welfare?',
    options: [
      { id: 'u9-a', label: 'It requires eliminating private property and replacing markets with collective ownership of productive assets throughout the economy.' },
      { id: 'u9-b', label: 'It is distinguished by Christian political inspiration together with social-market ideas and principles such as subsidiarity.' },
      { id: 'u9-c', label: 'It is simply another name for libertarianism because both traditions reject compulsory welfare and distributive social obligations.' },
      { id: 'u9-d', label: 'It is defined by nationalism alone, regardless of religious inspiration, economic organization or the distribution of public authority.' },
    ],
    acceptedAnswerSets: [['u9-b']],
    explanation: 'Christian democracy cannot be identified from welfare and markets alone; Christian inspiration and subsidiarity are important distinguishing features of the tradition.',
    evidenceIds: ['CAMBRIDGE-CHRISTIAN-DEMOCRACY', 'CAMBRIDGE-CD-RELIGIOUS-INSPIRATION', 'CAMBRIDGE-CD-SUBSIDIARITY'],
  },
  {
    id: 'U10', section: 'understand',
    prompt: 'Which statement best distinguishes fascism from ordinary conservatism or nationalism?',
    options: [
      { id: 'u10-a', label: 'Fascism is simply strong patriotism, so any movement that values national identity belongs in the fascist family.' },
      { id: 'u10-b', label: 'Fascism is mainly a tax policy, distinguished from conservatism by favoring a larger welfare state and more redistribution.' },
      { id: 'u10-c', label: 'Fascism combines ultranationalism and authoritarianism with rejection of pluralism, individual rights and liberal representative democracy.' },
      { id: 'u10-d', label: 'Fascism is another name for gradual conservatism because both place continuity and inherited institutions above rapid social reform.' },
    ],
    acceptedAnswerSets: [['u10-c']],
    explanation: 'Fascism is not a synonym for conservatism or nationalism; its defining pattern includes ultranationalism, authoritarianism and rejection of liberal-democratic pluralism.',
    evidenceIds: ['USHMM-FASCISM'],
  },
  {
    id: 'U11', section: 'understand',
    prompt: 'Which statement best describes the Marxian communist ideal?',
    options: [
      { id: 'u11-a', label: 'It ultimately envisions a classless and stateless society without private ownership of the means of production.' },
      { id: 'u11-b', label: 'It ultimately envisions a regulated capitalist welfare state in which most productive assets remain privately owned.' },
      { id: 'u11-c', label: 'It ultimately envisions a constitutional monarchy that preserves inherited hierarchy while gradually expanding social insurance.' },
      { id: 'u11-d', label: 'It ultimately envisions a minimal state whose main role is protecting voluntary exchange and strong private property rights.' },
    ],
    acceptedAnswerSets: [['u11-a']],
    explanation: 'In the Marxian ideal, communism is classless and ultimately stateless, with collective appropriation and no private ownership of the means of production.',
    evidenceIds: ['OXFORD-COMMUNISM'],
  },
  {
    id: 'U12', section: 'understand',
    prompt: 'Why should public provision and public ownership be treated as different political questions?',
    options: [
      { id: 'u12-a', label: 'They are identical because any publicly funded service necessarily requires the state to own every organization that delivers it.' },
      { id: 'u12-b', label: 'They differ because services can be publicly funded or guaranteed while productive organizations remain private, cooperative or mixed.' },
      { id: 'u12-c', label: 'They differ because public ownership concerns only taxation, while public provision concerns only the legal status of private companies.' },
      { id: 'u12-d', label: 'They are identical because regulation, funding and ownership always move together and therefore cannot be measured separately.' },
    ],
    acceptedAnswerSets: [['u12-b']],
    explanation: 'Public provision, redistribution and ownership are separable dimensions: governments can finance or guarantee services without owning all productive organizations that provide them.',
    evidenceIds: ['WVS-W7-DOCUMENTATION', 'ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM'],
  },
  {
    id: 'U13', section: 'understand',
    prompt: 'Which statement best captures the relationship between populism and democratic erosion?',
    options: [
      { id: 'u13-a', label: 'Every populist movement is authoritarian by definition, so no further evidence about pluralism or democratic behavior is needed.' },
      { id: 'u13-b', label: 'Populism is always harmless to democracy because electoral popularity guarantees protection of rights, opposition and institutional checks.' },
      { id: 'u13-c', label: 'Populism can coexist with democracy, but anti-pluralism and weak democratic commitments are stronger warning signs of erosion.' },
      { id: 'u13-d', label: 'Populism and democracy are unrelated concepts, so research cannot compare populist governments with changes in democratic institutions.' },
    ],
    acceptedAnswerSets: [['u13-c']],
    explanation: 'Research does not define every populist as authoritarian; anti-pluralism and weak commitment to democratic norms are more direct indicators of autocratizing risk.',
    evidenceIds: ['VDEM-POPULISM-AUTOCRATIZATION', 'IDEA-POPULISM-DEMOCRACY'],
  },
  {
    id: 'U14', section: 'understand',
    prompt: 'What can a nationalism score tell you on its own?',
    options: [
      { id: 'u14-a', label: 'It can determine a person’s entire left-right position because nationalism fixes economic, social and institutional beliefs at once.' },
      { id: 'u14-b', label: 'It can show how much political weight someone gives nationhood, but not their full economic or social ideology.' },
      { id: 'u14-c', label: 'It can prove support for fascism because nationalism and fascism are interchangeable categories in comparative political research.' },
      { id: 'u14-d', label: 'It can determine welfare preferences because national self-determination necessarily implies either high or low redistribution.' },
    ],
    acceptedAnswerSets: [['u14-b']],
    explanation: 'Nationalism concerns the political significance and self-determination of nations but can combine with multiple economic and social traditions.',
    evidenceIds: ['SEP-NATIONALISM'],
  },
  {
    id: 'U15', section: 'understand',
    prompt: 'Which statement best distinguishes green political thought from ordinary environmental regulation?',
    options: [
      { id: 'u15-a', label: 'Green politics is defined only by supporting any pollution rule, regardless of views about sustainability, growth or political organization.' },
      { id: 'u15-b', label: 'Green politics centers ecological limits and sustainability and often links them to deeper questions about economy, democracy and justice.' },
      { id: 'u15-c', label: 'Green politics requires rejecting every market mechanism because environmental policy and market incentives can never appear together.' },
      { id: 'u15-d', label: 'Green politics is mainly a nationalist tradition because ecological protection necessarily depends on reducing international cooperation and institutions.' },
    ],
    acceptedAnswerSets: [['u15-b']],
    explanation: 'Green political thought is broader than support for individual environmental rules; it treats ecological limits and sustainability as organizing political concerns.',
    evidenceIds: ['CAMBRIDGE-GREEN-POLITICS'],
  },
  {
    id: 'U16', section: 'understand',
    prompt: 'How is libertarianism best understood in relation to the broader liberal family?',
    options: [
      { id: 'u16-a', label: 'Libertarianism gives especially strong priority to individual freedom, property and voluntary exchange within the wider politics of liberty.' },
      { id: 'u16-b', label: 'Libertarianism rejects individual liberty as a political value and therefore sits outside every philosophical tradition associated with freedom.' },
      { id: 'u16-c', label: 'Libertarianism is identical to social democracy because both assign the same role to redistribution, regulation and public ownership.' },
      { id: 'u16-d', label: 'Libertarianism is defined primarily by inherited tradition and gradual social change rather than by limits on coercive political power.' },
    ],
    acceptedAnswerSets: [['u16-a']],
    explanation: 'Libertarianism belongs to the broader politics of liberty but gives unusually strong protection to personal freedom, property and voluntary exchange against coercion.',
    evidenceIds: ['SEP-LIBERTARIANISM', 'SEP-LIBERALISM'],
  },
  {
    id: 'U17', section: 'understand',
    prompt: 'Does support for redistribution by itself make someone socialist?',
    options: [
      { id: 'u17-a', label: 'Yes, because any attempt to reduce income inequality necessarily replaces private ownership with social ownership of production.' },
      { id: 'u17-b', label: 'Yes, because taxation and social ownership are the same political dimension and cannot vary independently in real systems.' },
      { id: 'u17-c', label: 'No, because redistribution can exist within social democracy, liberalism or other systems that retain predominantly private ownership.' },
      { id: 'u17-d', label: 'No, because socialism is defined only by cultural issues and has no historical connection to ownership or economic institutions.' },
    ],
    acceptedAnswerSets: [['u17-c']],
    explanation: 'Redistribution is not the same as social ownership. Modern social democracy, for example, can redistribute extensively while retaining predominantly private ownership.',
    evidenceIds: ['ROUTLEDGE-SOCIAL-DEMOCRACY', 'SEP-SOCIALISM', 'WVS-W7-DOCUMENTATION'],
  },
  {
    id: 'U18', section: 'understand',
    prompt: 'A party supports a social-market economy, welfare and distributive justice. What else would strengthen a classification as Christian democracy?',
    options: [
      { id: 'u18-a', label: 'Evidence of Christian political inspiration and a commitment to subsidiarity would make the classification substantially more specific.' },
      { id: 'u18-b', label: 'Evidence that the party rejects all religious influence would make Christian democracy the uniquely appropriate classification.' },
      { id: 'u18-c', label: 'Evidence that the party seeks collective ownership of nearly all production would make Christian democracy the clearest fit.' },
      { id: 'u18-d', label: 'No additional evidence is useful because welfare plus markets alone uniquely identifies Christian democracy among political traditions.' },
    ],
    acceptedAnswerSets: [['u18-a']],
    explanation: 'The social-market policy mix is not unique to Christian democracy. Christian inspiration and subsidiarity provide more distinctive evidence for that classification.',
    evidenceIds: ['CAMBRIDGE-CHRISTIAN-DEMOCRACY', 'CAMBRIDGE-CD-RELIGIOUS-INSPIRATION', 'CAMBRIDGE-CD-SUBSIDIARITY'],
  },
  {
    id: 'U19', section: 'understand',
    prompt: 'Which statement best separates ordinary conservatism from authoritarian politics?',
    options: [
      { id: 'u19-a', label: 'Conservatism necessarily rejects courts and opposition because valuing social order always requires concentrated executive power.' },
      { id: 'u19-b', label: 'Conservatism can value order and continuity while remaining compatible with rights, pluralism, elections and constitutional limits.' },
      { id: 'u19-c', label: 'Authoritarian politics is defined mainly by support for traditional social customs rather than by the distribution of political power.' },
      { id: 'u19-d', label: 'Conservatism and authoritarianism are interchangeable labels whenever a movement prefers gradual change over rapid social reform.' },
    ],
    acceptedAnswerSets: [['u19-b']],
    explanation: 'Conservative commitments to order or continuity do not by themselves imply rejection of pluralism or constitutional democracy; those are separate institutional questions.',
    evidenceIds: ['SEP-CONSERVATISM', 'VDEM-LIBERAL-DEMOCRACY'],
  },
  {
    id: 'U20', section: 'understand',
    prompt: 'What is the safest way to infer a person’s broader political tradition from questionnaire answers?',
    options: [
      { id: 'u20-a', label: 'Use one highly visible issue, because a single answer normally determines economic, social and institutional beliefs together.' },
      { id: 'u20-b', label: 'Use several related dimensions and look for a pattern, because major traditions contain overlap and internal variation.' },
      { id: 'u20-c', label: 'Use nationality alone, because country of citizenship reliably determines a person’s underlying political philosophy and ideology.' },
      { id: 'u20-d', label: 'Use whichever answer sounds most intense, because response strength is more informative than the content of other positions.' },
    ],
    acceptedAnswerSets: [['u20-b']],
    explanation: 'Political traditions are bundles of ideas rather than single-issue identities. A multidimensional pattern is therefore more defensible than classification from one answer.',
    evidenceIds: ['AAPOR-BEST-PRACTICES', 'SEP-LIBERALISM', 'SEP-CONSERVATISM', 'SEP-SOCIALISM'],
  },
] as const;
