import type { LiteracyQuestion } from './deep-engine';

export type LiteracyLocale = 'en' | 'de' | 'es' | 'fr';

type LocalizedQuestion = {
  prompt: string;
  explanation: string;
  options?: Record<string, string>;
};

type SupportedTranslationLocale = Exclude<LiteracyLocale, 'en'>;

const termLabels: Record<SupportedTranslationLocale, Record<string, string>> = {
  de: {
    libertarianism: 'Libertarismus', 'social-democracy': 'Sozialdemokratie', communism: 'Kommunismus', conservatism: 'Konservatismus',
    socialism: 'Sozialismus', 'green-politics': 'Grüne Politik', 'christian-democracy': 'Christdemokratie', nationalism: 'Nationalismus',
    'classical-liberalism': 'Klassischer Liberalismus', fascism: 'Faschismus', liberalism: 'Liberalismus', populism: 'Populismus',
    'populist-radical-right': 'Populistische radikale Rechte', 'extreme-right': 'Extreme Rechte', 'radical-right': 'Radikale Rechte',
    'majoritarian-democracy': 'Unbegrenzte Mehrheitsdemokratie', 'one-party-rule': 'Einparteienherrschaft', authoritarianism: 'Autoritäre Regierung',
    'liberal-democracy': 'Liberale Demokratie',
  },
  es: {
    libertarianism: 'Libertarismo', 'social-democracy': 'Socialdemocracia', communism: 'Comunismo', conservatism: 'Conservadurismo',
    socialism: 'Socialismo', 'green-politics': 'Política verde', 'christian-democracy': 'Democracia cristiana', nationalism: 'Nacionalismo',
    'classical-liberalism': 'Liberalismo clásico', fascism: 'Fascismo', liberalism: 'Liberalismo', populism: 'Populismo',
    'populist-radical-right': 'Derecha radical populista', 'extreme-right': 'Extrema derecha', 'radical-right': 'Derecha radical',
    'majoritarian-democracy': 'Democracia mayoritaria sin límites', 'one-party-rule': 'Régimen de partido único', authoritarianism: 'Gobierno autoritario',
    'liberal-democracy': 'Democracia liberal',
  },
  fr: {
    libertarianism: 'Libertarianisme', 'social-democracy': 'Social-démocratie', communism: 'Communisme', conservatism: 'Conservatisme',
    socialism: 'Socialisme', 'green-politics': 'Écologie politique', 'christian-democracy': 'Démocratie chrétienne', nationalism: 'Nationalisme',
    'classical-liberalism': 'Libéralisme classique', fascism: 'Fascisme', liberalism: 'Libéralisme', populism: 'Populisme',
    'populist-radical-right': 'Droite radicale populiste', 'extreme-right': 'Extrême droite', 'radical-right': 'Droite radicale',
    'majoritarian-democracy': 'Démocratie majoritaire sans limites', 'one-party-rule': 'Régime à parti unique', authoritarianism: 'Gouvernement autoritaire',
    'liberal-democracy': 'Démocratie libérale',
  },
};

const de: Record<string, LocalizedQuestion> = {
  C1: { prompt: 'Die meisten Unternehmen bleiben privat. Der Staat bietet starke öffentliche Leistungen, Sozialversicherung und Arbeitnehmerschutz. Höhere Einkommen tragen über höhere Steuern stärker dazu bei.', explanation: 'Das passt zur modernen Sozialdemokratie: überwiegend private Unternehmen, kombiniert mit starken öffentlichen Leistungen, Regulierung und Umverteilung.' },
  C2: { prompt: 'Große Unternehmen sollen deutlich öfter der Öffentlichkeit, den Beschäftigten oder Genossenschaften gehören statt privaten Anteilseignern.', explanation: 'Sozialismus ist die breite politische Familie, in der gesellschaftliches, öffentliches, genossenschaftliches oder Arbeitnehmenden-Eigentum eine zentrale Rolle spielt.' },
  C3: { prompt: 'Individuelle Freiheit, Privateigentum und freiwilliger Austausch stehen an erster Stelle. Der Staat soll sich so wenig wie möglich in friedliche persönliche und wirtschaftliche Entscheidungen einmischen.', explanation: 'Libertarismus gibt persönlicher und wirtschaftlicher Freiheit sowie freiwilligem Austausch besonders hohes Gewicht und will staatlichen Zwang stark begrenzen.' },
  C4: { prompt: 'Lang bestehende Institutionen verdienen Respekt. Veränderungen sollten meist schrittweise erfolgen, und große gesellschaftliche Experimente sollten mit Vorsicht betrachtet werden.', explanation: 'Konservatismus betont häufig Kontinuität, gewachsene Institutionen und Vorsicht bei schnellen oder umfassenden Veränderungen.' },
  C5: { prompt: 'Märkte und Privateigentum sind wichtig. Sozialleistungen und Regulierung können aber sinnvoll sein, wenn sie Stabilität und gesellschaftlichen Zusammenhalt stärken.', explanation: 'Konservatismus verlangt keinen Minimalstaat; konservative Traditionen können Sozialstaat und Regulierung aus Gründen von Ordnung, Verantwortung und Zusammenhalt unterstützen.' },
  C6: { prompt: 'Ökologische Grenzen und langfristige Nachhaltigkeit sollen im Zentrum der Politik stehen, zusammen mit Bürgerbeteiligung, lokalen Entscheidungen und sozialer Gerechtigkeit.', explanation: 'Grüne Politik macht ökologische Grenzen und Nachhaltigkeit zu Kernfragen und verbindet sie oft mit Beteiligung, Dezentralisierung und sozialer Gerechtigkeit.' },
  C7: { prompt: 'Langfristiges Ziel ist eine klassenlose Gesellschaft ohne Privateigentum an großen Produktionsmitteln und schließlich ohne Staat.', explanation: 'Das ist das marxistische kommunistische Endziel: eine klassenlose und letztlich staatenlose Gesellschaft mit gemeinsamem Eigentum an den Produktionsmitteln.' },
  C8: { prompt: 'Die Nation soll unter starker autoritärer Führung grundlegend erneuert werden. Oppositionsparteien und liberale Demokratie werden abgelehnt, individuelle Rechte dem nationalen Projekt untergeordnet.', explanation: 'Faschismus verbindet ultranationalistische und autoritäre Politik mit der Ablehnung von pluralistischer liberaler Demokratie und politischen Rechten.' },
  C9: { prompt: 'Nationen haben einen besonderen politischen Wert und sollen sich selbst regieren können. Daraus folgt allein noch keine feste Position zu Märkten, Sozialstaat oder Steuern.', explanation: 'Nationalismus gibt Nationen und nationaler Selbstbestimmung besondere politische Bedeutung, kann aber mit unterschiedlichen Wirtschafts- und Sozialideen verbunden werden.' },
  C10: { prompt: 'Individuelle Freiheit und gleiche Rechte stehen im Mittelpunkt. Innerhalb dieser Richtung gibt es große Unterschiede bei Märkten, Sozialstaat und der Rolle des Staates.', explanation: 'Liberalismus ist eine breite Familie, die Freiheit zentral stellt, aber darüber streitet, was Freiheit für Märkte, Eigentum und staatliches Handeln bedeutet.' },
  C11: { prompt: 'Die Bewegung ist von christlichen sozialen Ideen geprägt. Sie unterstützt soziale Marktwirtschaft und Sozialstaat. Entscheidungen sollen möglichst nah bei den Betroffenen fallen; höhere Ebenen greifen ein, wenn es nötig ist.', explanation: 'Christdemokratie verbindet christliche Sozialideen mit sozialer Marktwirtschaft und häufig dem Prinzip, Aufgaben möglichst auf der niedrigsten geeigneten Ebene zu lösen.' },
  C12: { prompt: 'Politik wird als Konflikt zwischen normalen Bürgerinnen und Bürgern und einem korrupten Establishment verstanden. Die Regierung soll den gemeinsamen Willen des Volkes umsetzen.', explanation: 'Populismus stellt typischerweise ein tugendhaftes Volk einer korrupten Elite gegenüber und betont den allgemeinen Willen des Volkes.' },
  C13: { prompt: 'Die Bewegung fordert strenge Law-and-Order-Politik, gibt Menschen Vorrang, die sie als seit Langem zur Nation gehörend ansieht, und sagt, sie vertrete normale Leute gegen eine korrupte Elite. Sie nimmt weiterhin an Wahlen teil.', explanation: 'Die populistische radikale Rechte verbindet typischerweise ausschließende Vorstellungen nationaler Zugehörigkeit, Autoritarismus und Populismus innerhalb von Wahlpolitik.' },
  C14: { prompt: 'Die Bewegung lehnt Demokratie selbst ab und sagt, politische Gegner sollten nicht das gleiche Recht haben, um Macht zu konkurrieren.', explanation: 'Die ausdrückliche Ablehnung demokratischer Konkurrenz ist ein zentrales Merkmal, das die extreme Rechte von der radikalen Rechten unterscheidet.' },
  C15: { prompt: 'Es gibt freie Wahlen, Bürgerrechte, Rechtsstaatlichkeit und unabhängige Kontrollen der gewählten Regierung.', explanation: 'Liberale Demokratie verbindet echte Wahlkonkurrenz mit Bürgerrechten, Rechtsstaatlichkeit und unabhängigen Begrenzungen politischer Macht.' },
  C16: { prompt: 'Eine revolutionäre Bewegung will das kapitalistische Eigentum an großen Industrien beenden, es durch gemeinsames Eigentum ersetzen und schließlich eine klassenlose Gesellschaft schaffen.', explanation: 'Kommunismus entstand aus dem marxistischen Ziel, kapitalistisches Eigentum und Klassenteilungen durch gemeinsames Eigentum und schließlich eine klassenlose Gesellschaft zu ersetzen.' },
  C17: { prompt: 'Eine demokratische Bewegung will deutlich mehr Eigentum von Beschäftigten, Genossenschaften oder der öffentlichen Hand. Freie Wahlen, Bürgerrechte und Oppositionsparteien sollen bleiben.', explanation: 'Sozialismus kann demokratisch und pluralistisch sein; stärkeres gesellschaftliches Eigentum bedeutet nicht automatisch Einparteienherrschaft.' },
  C18: { prompt: 'Wohlhabende Gesellschaften müssen möglicherweise weniger konsumieren, weil ökologische Grenzen nicht immer allein durch sauberere Technik gelöst werden können.', explanation: 'Grüne politische Ansätze geben ökologischen Grenzen besonderes Gewicht und können deshalb tiefere Veränderungen von Produktion und Konsum befürworten.' },
  C19: { prompt: 'Der Staat soll Rechte und Verträge schützen, sich ansonsten aber so wenig wie möglich in friedliche Entscheidungen von Erwachsenen, Unternehmen und freiwilligen Gruppen einmischen.', explanation: 'Libertarismus priorisiert individuelle Freiheit und freiwilligen Austausch besonders stark und will den Bereich staatlichen Zwangs eng halten.' },
  C20: { prompt: 'Gesellschaftliche Ordnung, Kontinuität und lang bestehende Institutionen sind wichtig. Wahlen, Oppositionsparteien und verfassungsrechtliche Grenzen sollen erhalten bleiben.', explanation: 'Konservatismus kann Ordnung, Kontinuität und gewachsene Institutionen betonen und zugleich vollständig mit verfassungsmäßiger Demokratie vereinbar sein.' },

  U1: { prompt: 'Welche Aussage beschreibt Populismus am besten?', explanation: 'Populismus stellt Politik häufig als Konflikt zwischen normalen Menschen und einer korrupten Elite dar. Er kann sich mit sehr unterschiedlichen linken oder rechten Ideen verbinden.', options: { 'u1-a': 'Er ist hauptsächlich ein Kommunikationsstil und hat keine wiederkehrenden politischen Ideen.', 'u1-b': 'Er ist ein vollständiges Wirtschaftsprogramm, das immer Protektionismus, Umverteilung und Staatseigentum verlangt.', 'u1-c': 'Er teilt Politik meist in normale Menschen und eine korrupte Elite und kann sich mit unterschiedlichen linken oder rechten Ideen verbinden.', 'u1-d': 'Er ist dasselbe wie direkte Demokratie und lehnt immer gewählte Vertreter und Parteien ab.' } },
  U2: { prompt: 'Sagt Nationalismus automatisch, ob eine Bewegung links oder rechts ist?', explanation: 'Nationalismus gibt Nationen und nationaler Selbstbestimmung politische Bedeutung, ist aber historisch mit konservativen, liberalen, sozialistischen und anderen Ideen verbunden worden.', options: { 'u2-a': 'Ja. Nationalismus geht normalerweise mit rechter Wirtschaftspolitik einher.', 'u2-b': 'Nein. Nationalismus kann sich mit verschiedenen politischen Traditionen verbinden; man muss auch die übrigen Positionen kennen.', 'u2-c': 'Ja. Nationalismus betrifft im Wesentlichen nur Einwanderung und Grenzkontrollen.', 'u2-d': 'Ja. Nationalismus geht immer mit traditionellen gesellschaftlichen Werten einher.' } },
  U3: { prompt: 'Ein Land hat echte freie Wahlen. Was braucht es zusätzlich, um als liberale Demokratie zu gelten?', explanation: 'Liberale Demokratie umfasst mehr als Wahlen: Bürgerrechte, Rechtsstaatlichkeit und wirksame Kontrollen begrenzen die Macht der Regierung.', options: { 'u3-a': 'Nichts. Freie Wahlen reichen aus.', 'u3-b': 'Eine Marktwirtschaft und überwiegend private Unternehmen.', 'u3-c': 'Eine starke gewählte Führung, die ohne Gerichte oder andere Kontrollen handeln kann.', 'u3-d': 'Bürgerrechte, Rechtsstaatlichkeit und wirksame Begrenzungen staatlicher Macht.' } },
  U4: { prompt: 'Radikale Rechte und extreme Rechte werden oft zusammen genannt. Was ist ein zentraler Unterschied?', explanation: 'Ein wichtiger Unterschied betrifft Demokratie: Die radikale Rechte kann an Wahlen teilnehmen, während die extreme Rechte Demokratie selbst ablehnt.', options: { 'u4-a': 'Die extreme Rechte ist einfach nur nationalistischer.', 'u4-b': 'Die radikale Rechte will niedrigere Steuern, die extreme Rechte Staatseigentum.', 'u4-c': 'Die extreme Rechte lehnt Demokratie selbst ab, während die radikale Rechte Wahlen akzeptieren kann.', 'u4-d': 'Die radikale Rechte verwendet immer populistische Sprache, die extreme Rechte nie.' } },
  U5: { prompt: 'Unterstützen alle Liberalen dieselbe Wirtschaftspolitik?', explanation: 'Liberalismus ist eine breite politische Familie, die Freiheit zentral stellt. Liberale können sich stark über Eigentum, Märkte, Sozialstaat und die Rolle des Staates unterscheiden.', options: { 'u5-a': 'Ja. Alle Liberalen wollen einen Minimalstaat.', 'u5-b': 'Ja. Liberalismus betrifft hauptsächlich Wahlen, nicht wirtschaftliche oder persönliche Freiheit.', 'u5-c': 'Ja. Nur Liberale mit großem Sozialstaat zählen als moderne Liberale.', 'u5-d': 'Nein. Liberale teilen die Bedeutung von Freiheit, streiten aber über Märkte, Sozialstaat und staatliches Handeln.' } },
  U6: { prompt: 'Welche Aussage über Sozialismus ist am genauesten?', explanation: 'Sozialismus ist eine breite Ideenfamilie, in der gesellschaftliches Eigentum oder Kontrolle eine wichtige Rolle spielt. Es gibt unterschiedliche Wirtschaftsmodelle und demokratische wie nichtdemokratische historische Formen.', options: { 'u6-a': 'Jedes Land mit hohen Sozialausgaben ist sozialistisch, auch wenn die meisten Unternehmen privat bleiben.', 'u6-b': 'Sozialismus ist eine breite Familie, in der öffentliches, genossenschaftliches oder Arbeitnehmenden-Eigentum eine wichtige Rolle spielt.', 'u6-c': 'Sozialismus verlangt immer zentrale Planung und vollständiges Staatseigentum.', 'u6-d': 'Sozialismus verlangt immer Einparteienherrschaft.' } },
  U7: { prompt: 'Was ist ein wichtiger Unterschied zwischen moderner Sozialdemokratie und Sozialismus?', explanation: 'Moderne Sozialdemokratie arbeitet normalerweise innerhalb einer überwiegend kapitalistischen Eigentumsordnung mit Regulierung, öffentlichen Leistungen und Umverteilung; gesellschaftliches Eigentum ist im Sozialismus zentraler.', options: { 'u7-a': 'Moderne Sozialdemokratie lässt die meisten Unternehmen privat, während gesellschaftliches Eigentum im Sozialismus eine zentralere Rolle spielt.', 'u7-b': 'Sozialdemokratie steht für moderate Steuern, Sozialismus immer für sehr hohe Steuern.', 'u7-c': 'Sozialdemokratie akzeptiert Wahlen, Sozialismus lehnt sie immer ab.', 'u7-d': 'Sozialismus unterstützt öffentliche Leistungen, Sozialdemokratie hauptsächlich private.' } },
  U8: { prompt: 'Kann eine konservative Partei einen Sozialstaat unterstützen?', explanation: 'Konservatismus ist nicht durch eine einzige Sozialstaatsposition definiert. Manche konservativen Traditionen unterstützen soziale Sicherung aus Gründen von Verantwortung, Stabilität und Zusammenhalt.', options: { 'u8-a': 'Nur wenn jede Leistung von privaten Unternehmen erbracht wird.', 'u8-b': 'Nein. Konservatismus verlangt immer einen Minimalstaat.', 'u8-c': 'Ja. Manche konservativen Traditionen unterstützen Sozialstaat oder Regulierung, um Stabilität, Verantwortung oder Zusammenhalt zu stärken.', 'u8-d': 'Nur wenn der Staat zugleich die meisten großen Unternehmen besitzt.' } },
  U9: { prompt: 'Was unterscheidet Christdemokratie von anderen Parteien, die ebenfalls Märkte und Sozialstaat unterstützen?', explanation: 'Christdemokratie ist durch christliche Soziallehre geprägt und verbindet sie häufig mit sozialer Marktwirtschaft und Subsidiarität.', options: { 'u9-a': 'Märkte und großzügige Sozialleistungen allein reichen aus.', 'u9-b': 'Sie ist von christlichen sozialen Ideen geprägt und betont häufig, Entscheidungen möglichst lokal zu treffen.', 'u9-c': 'Starke Familienpolitik allein macht eine Partei christdemokratisch.', 'u9-d': 'Europäische Zusammenarbeit ist das einzige definierende Merkmal.' } },
  U10: { prompt: 'Was unterscheidet Faschismus am klarsten von gewöhnlichem Konservatismus oder Nationalismus?', explanation: 'Faschismus ist nicht einfach starker Patriotismus oder Nationalismus. Kennzeichnend ist die Verbindung autoritärer nationalistischer Politik mit der Ablehnung liberal-demokratischer Konkurrenz und Rechte.', options: { 'u10-a': 'Starker Patriotismus und strenge Law-and-Order-Politik.', 'u10-b': 'Eine bestimmte Organisation von Unternehmen und Arbeit, während Demokratie und Opposition geschützt bleiben.', 'u10-c': 'Autoritärer Nationalismus zusammen mit der Ablehnung politischer Opposition, individueller Rechte und liberaler Demokratie.', 'u10-d': 'Nationalismus in Verbindung mit einem größeren Sozialstaat.' } },
  U11: { prompt: 'Was ist in Marx’ Theorie das langfristige Ziel des Kommunismus?', explanation: 'Im marxistischen Ideal ist Kommunismus klassenlos und letztlich staatenlos; große Produktionsmittel befinden sich nicht in privatem Eigentum.', options: { 'u11-a': 'Eine klassenlose Gesellschaft ohne Privateigentum an großen Produktionsmitteln und schließlich ohne Staat.', 'u11-b': 'Ein dauerhafter Einparteienstaat mit zentraler Planung.', 'u11-c': 'Eine arbeitnehmergeführte Marktwirtschaft, die privates Kapital beibehält.', 'u11-d': 'Ein regulierter kapitalistischer Sozialstaat mit privaten Unternehmen.' } },
  U12: { prompt: 'Wie hängen Kommunismus und Sozialismus zusammen?', explanation: 'Sozialismus ist eine breite Ideenfamilie über gesellschaftliches Eigentum und wirtschaftliche Macht. Kommunismus entwickelte sich innerhalb dieser Familie und zielt in marxistischer Theorie auf gemeinsames Eigentum und eine klassenlose Gesellschaft.', options: { 'u12-a': 'Sie sind exakte Synonyme und beschreiben immer dasselbe politische Programm.', 'u12-b': 'Kommunismus ist eine Richtung innerhalb der breiteren sozialistischen Tradition mit dem langfristigen Ziel gemeinsamen Eigentums und einer klassenlosen Gesellschaft.', 'u12-c': 'Kommunismus ist hauptsächlich ein Sozialstaatsmodell mit überwiegend privaten Unternehmen.', 'u12-d': 'Sozialismus bedeutet zwingend Einparteienherrschaft, Kommunismus zwingend Mehrparteiendemokratie.' } },
  U13: { prompt: 'Bedeutet die Bezeichnung „populistisch“ automatisch, dass eine Bewegung autoritär ist?', explanation: 'Populismus allein beweist keinen Autoritarismus. Angriffe auf politische Konkurrenz, Kontrollen und demokratische Regeln sind direktere Warnzeichen.', options: { 'u13-a': 'Ja. Populismus ist per Definition autoritär.', 'u13-b': 'Nein. Wer Wahlen gewinnt, kann keine Gefahr für Demokratie mehr darstellen.', 'u13-c': 'Nein. Populismus kann in Demokratien vorkommen; die Ablehnung politischer Konkurrenz und demokratischer Regeln ist ein stärkeres Warnzeichen.', 'u13-d': 'Nur Wirtschaftspolitik zeigt, ob populistische Bewegungen Demokratie bedrohen.' } },
  U14: { prompt: 'Warum sind nationale Souveränität und die Frage, wer vollständig zur Nation gehört, unterschiedliche Themen?', explanation: 'Souveränität fragt, wer die letzte politische Entscheidungsgewalt hat. Nationale Zugehörigkeit fragt, wer als voll zugehörig behandelt wird.', options: { 'u14-a': 'Sie sind nicht verschieden. Wer nationale Selbstbestimmung will, will normalerweise weniger Rechte für Eingebürgerte.', 'u14-b': 'Man kann starke nationale Selbstbestimmung unterstützen und Eingebürgerte trotzdem als vollwertige Mitglieder der Nation ansehen.', 'u14-c': 'Souveränität betrifft nur Einwanderung, nationale Zugehörigkeit nur Handel.', 'u14-d': 'Beides misst lediglich Patriotismus.' } },
  U15: { prompt: 'Warum ist grüne Politik mehr als nur Umweltschutzregeln?', explanation: 'Grüne Politik behandelt ökologische Grenzen und langfristige Nachhaltigkeit als zentrale politische Fragen und verbindet sie häufig mit Demokratie und sozialer Gerechtigkeit.', options: { 'u15-a': 'Jede starke Umweltregel macht ein Programm grün, auch wenn unbegrenztes Wachstum oberstes Ziel bleibt.', 'u15-b': 'Grüne Politik stellt ökologische Grenzen und Nachhaltigkeit ins Zentrum und verbindet sie häufig mit Demokratie und sozialer Gerechtigkeit.', 'u15-c': 'Grüne Politik verlangt immer die vollständige Abschaffung von Märkten.', 'u15-d': 'Grüne Politik betrifft nur Naturschutz und nicht Wirtschaft oder Demokratie.' } },
  U16: { prompt: 'Was ist am Libertarismus besonders?', explanation: 'Libertarismus schützt persönliche und wirtschaftliche Freiheit, Privateigentum und freiwilligen Austausch besonders stark und will staatliche Eingriffe eng begrenzen.', options: { 'u16-a': 'Er gibt individueller Freiheit, Privateigentum, freiwilligem Austausch und der Begrenzung staatlicher Eingriffe besonders hohes Gewicht.', 'u16-b': 'Er betrifft hauptsächlich persönliche Lebensführung; Eigentum und Wirtschaftspolitik sind zweitrangig.', 'u16-c': 'Er nutzt Umverteilung und einen großen Sozialstaat als Hauptweg zu mehr Freiheit.', 'u16-d': 'Er stellt gewachsene Institutionen grundsätzlich über individuelle Wahlfreiheit.' } },
  U17: { prompt: 'Macht staatliches Eigentum an einigen großen Unternehmen ein Land automatisch kommunistisch?', explanation: 'Öffentliches Eigentum allein definiert keinen Kommunismus. Mischwirtschaften, Sozialdemokratien und andere Systeme können große Unternehmen öffentlich besitzen und gleichzeitig umfangreiches Privateigentum und Märkte behalten.', options: { 'u17-a': 'Ja. Jedes öffentliche Eigentum reicht aus, damit eine Wirtschaft kommunistisch ist.', 'u17-b': 'Ja, solange der Staat zusätzlich einen großen Sozialstaat hat.', 'u17-c': 'Nein. Öffentliches Eigentum gibt es in vielen Systemen; Kommunismus zielt auf eine viel umfassendere Veränderung von Eigentum und Klassenverhältnissen.', 'u17-d': 'Nein, weil Kommunismus vollständiges Privateigentum an wirtschaftlicher Tätigkeit verlangt.' } },
  U18: { prompt: 'Eine politische Idee sagt: Entscheidungen sollen so lokal wie praktisch möglich getroffen werden, höhere Ebenen greifen ein, wenn nötig. Wie heißt dieses Prinzip?', explanation: 'Das ist Subsidiarität: Verantwortung bleibt bei der niedrigsten Ebene, die eine Aufgabe gut lösen kann; höhere Ebenen helfen, wenn nötig.', options: { 'u18-a': 'Zentralisierung', 'u18-b': 'Subsidiarität', 'u18-c': 'Privatisierung', 'u18-d': 'Regionale Vorherrschaft' } },
  U19: { prompt: 'Welche Aussage beschreibt den Unterschied zwischen Konservatismus und autoritärer Politik am besten?', explanation: 'Konservative Werte wie Ordnung, Tradition oder schrittweiser Wandel bedeuten nicht automatisch die Ablehnung von Rechten, politischem Wettbewerb oder Verfassungsgrenzen.', options: { 'u19-a': 'Law-and-Order bedeutet automatisch weniger Grenzen für Regierungsmacht.', 'u19-b': 'Konservative können Ordnung und Kontinuität schätzen und zugleich Rechte, Opposition, Wahlen und Begrenzungen staatlicher Macht unterstützen.', 'u19-c': 'Traditionelle gesellschaftliche Werte reichen aus, um eine Bewegung autoritär zu machen.', 'u19-d': 'Autoritarismus ist einfach eine stärkere Form des Konservatismus.' } },
  U20: { prompt: 'Warum kann „Kommunismus“ etwas Unterschiedliches meinen, wenn man über Theorie und Geschichte spricht?', explanation: 'Man sollte das theoretische Endziel von historischen Regierungen kommunistischer Parteien unterscheiden. Marxistischer Kommunismus ist klassenlos und letztlich staatenlos; historische kommunistische Staaten beschrieben sich meist als Übergangsstufen auf dem Weg dorthin.', options: { 'u20-a': 'Weil Marx Kommunismus als dauerhaften Einparteienstaat definierte und spätere Regierungen diese Idee ablehnten.', 'u20-b': 'Weil marxistischer Kommunismus ein klassenloses, letztlich staatenloses Endziel beschreibt, während historische kommunistische Parteien oft zentralisierte Einparteienstaaten als Übergang regierten.', 'u20-c': 'Weil kommunistische Theorie hauptsächlich Nationalismus bedeutet, historische kommunistische Regierungen dagegen Libertarismus.', 'u20-d': 'Es gibt keinen Unterschied: Jede Regierung einer kommunistischen Partei entsprach bereits dem endgültigen kommunistischen Ideal.' } },
};

const es: Record<string, LocalizedQuestion> = {
  C1: { prompt: 'La mayoría de las empresas siguen siendo privadas. El Estado ofrece buenos servicios públicos, seguridad social y protección laboral, financiados en parte con impuestos más altos a las rentas altas.', explanation: 'Esto encaja con la socialdemocracia moderna: una economía principalmente privada combinada con servicios públicos, regulación y redistribución.' },
  C2: { prompt: 'Las grandes empresas deberían pertenecer mucho más al sector público, a sus trabajadores o a cooperativas, y menos a accionistas privados.', explanation: 'El socialismo es la familia amplia en la que la propiedad social, pública, cooperativa o de los trabajadores tiene un papel central.' },
  C3: { prompt: 'La libertad individual, la propiedad privada y el intercambio voluntario son prioritarios. El gobierno debería intervenir lo mínimo posible en decisiones personales y económicas pacíficas.', explanation: 'El libertarismo da una prioridad especialmente alta a la libertad personal y económica, la propiedad privada y el intercambio voluntario.' },
  C4: { prompt: 'Las instituciones de larga tradición merecen respeto. El cambio debería ser gradual y los grandes experimentos sociales deberían tratarse con cautela.', explanation: 'El conservadurismo suele destacar la continuidad, las instituciones heredadas y la cautela ante cambios rápidos o diseñados desde cero.' },
  C5: { prompt: 'Los mercados y la propiedad privada son importantes, pero el bienestar social y la regulación pueden ser útiles si ayudan a mantener la estabilidad y la cohesión social.', explanation: 'El conservadurismo no exige un Estado mínimo; algunas corrientes aceptan bienestar y regulación por razones de responsabilidad, estabilidad y cohesión.' },
  C6: { prompt: 'Los límites ecológicos y la sostenibilidad a largo plazo deberían estar en el centro de la política, junto con la participación ciudadana, las decisiones locales y la justicia social.', explanation: 'La política verde convierte los límites ecológicos y la sostenibilidad en asuntos centrales y suele relacionarlos con participación, descentralización y justicia social.' },
  C7: { prompt: 'El objetivo final es una sociedad sin clases, sin propiedad privada de los principales medios de producción y, finalmente, sin Estado.', explanation: 'Ese es el ideal comunista marxista: una sociedad sin clases y, en última instancia, sin Estado, basada en la propiedad común de los medios de producción.' },
  C8: { prompt: 'La nación debe ser transformada bajo un líder autoritario fuerte. Se rechazan los partidos de oposición y la democracia liberal, y los derechos individuales quedan subordinados al proyecto nacional.', explanation: 'El fascismo combina ultranacionalismo y autoritarismo con rechazo de la democracia liberal pluralista y de derechos políticos fundamentales.' },
  C9: { prompt: 'Las naciones tienen un valor político especial y deberían poder gobernarse a sí mismas. Esta idea no determina por sí sola una posición sobre mercados, bienestar o impuestos.', explanation: 'El nacionalismo da importancia política a las naciones y a la autodeterminación nacional, pero puede combinarse con ideas económicas y sociales muy diferentes.' },
  C10: { prompt: 'La libertad individual y la igualdad jurídica son centrales. Dentro de esta tradición existen grandes desacuerdos sobre mercados, bienestar y el papel del Estado.', explanation: 'El liberalismo es una familia amplia centrada en la libertad, pero con desacuerdos reales sobre propiedad, mercados, bienestar y acción estatal.' },
  C11: { prompt: 'El movimiento está influido por ideas sociales cristianas. Apoya una economía social de mercado y el bienestar, y prefiere que las decisiones se tomen tan cerca de la ciudadanía como sea práctico.', explanation: 'La democracia cristiana combina inspiración social cristiana, economía social de mercado y a menudo el principio de subsidiariedad.' },
  C12: { prompt: 'La política se entiende como una lucha entre la gente común y una élite corrupta. El gobierno debería aplicar la voluntad común del pueblo.', explanation: 'El populismo suele contraponer un pueblo virtuoso a una élite corrupta y da un peso especial a la voluntad general del pueblo.' },
  C13: { prompt: 'El movimiento exige mano dura, da preferencia a quienes considera miembros tradicionales de la nación y dice representar a la gente común contra una élite corrupta. Sigue compitiendo en elecciones.', explanation: 'La derecha radical populista suele combinar ideas excluyentes de pertenencia nacional, autoritarismo y populismo dentro de la política electoral.' },
  C14: { prompt: 'El movimiento rechaza la democracia misma y afirma que sus adversarios políticos no deberían tener el mismo derecho a competir por el poder.', explanation: 'El rechazo explícito de la competencia democrática es un rasgo clave que diferencia a la extrema derecha de la derecha radical.' },
  C15: { prompt: 'Hay elecciones competitivas, derechos civiles, Estado de derecho y controles independientes sobre los líderes elegidos.', explanation: 'La democracia liberal combina competencia electoral con libertades civiles, Estado de derecho y controles independientes del poder político.' },
  C16: { prompt: 'Un movimiento revolucionario quiere acabar con la propiedad capitalista de las grandes industrias, sustituirla por propiedad común y construir finalmente una sociedad sin clases.', explanation: 'El comunismo surgió del objetivo marxista de sustituir la propiedad capitalista y las divisiones de clase por propiedad común y, finalmente, una sociedad sin clases.' },
  C17: { prompt: 'Un movimiento democrático quiere mucha más propiedad de trabajadores, cooperativas o del sector público, manteniendo elecciones libres, derechos civiles y partidos de oposición.', explanation: 'El socialismo puede adoptar formas democráticas y pluralistas; una mayor propiedad social no implica por sí sola un régimen de partido único.' },
  C18: { prompt: 'Las sociedades ricas quizá deban consumir menos en algunos casos porque los límites ecológicos no siempre pueden resolverse solo con tecnología más limpia.', explanation: 'La política verde da un peso especial a los límites ecológicos y puede defender cambios más profundos en producción y consumo.' },
  C19: { prompt: 'El gobierno debería proteger derechos y contratos, pero por lo demás intervenir lo mínimo posible en las decisiones pacíficas de adultos, empresas y asociaciones voluntarias.', explanation: 'El libertarismo prioriza fuertemente la libertad individual y el intercambio voluntario y busca limitar el ámbito de la coerción estatal.' },
  C20: { prompt: 'El orden social, la continuidad y las instituciones de larga tradición son importantes, mientras deben mantenerse elecciones, partidos de oposición y límites constitucionales.', explanation: 'El conservadurismo puede valorar el orden, la continuidad y las instituciones heredadas y seguir siendo plenamente compatible con la democracia constitucional.' },

  U1: { prompt: '¿Qué afirmación describe mejor el populismo?', explanation: 'El populismo suele presentar la política como una lucha entre la gente común y una élite corrupta. Puede combinarse con ideas muy distintas de izquierda o derecha.', options: { 'u1-a': 'Es principalmente una forma de hablar y no tiene ideas políticas recurrentes.', 'u1-b': 'Es un programa económico completo que siempre exige proteccionismo, redistribución y propiedad estatal.', 'u1-c': 'Suele dividir la política entre la gente común y una élite corrupta y puede combinarse con distintas ideas de izquierda o derecha.', 'u1-d': 'Es lo mismo que democracia directa y siempre rechaza representantes elegidos y partidos.' } },
  U2: { prompt: '¿El nacionalismo indica automáticamente si un movimiento es de izquierda o de derecha?', explanation: 'El nacionalismo da importancia política a las naciones y a la autodeterminación, pero históricamente se ha combinado con ideas conservadoras, liberales, socialistas y otras.', options: { 'u2-a': 'Sí. Normalmente va unido a políticas económicas de derechas.', 'u2-b': 'No. Puede combinarse con distintas tradiciones políticas, así que hay que conocer también sus otras ideas.', 'u2-c': 'Sí. Se refiere principalmente a inmigración y fronteras.', 'u2-d': 'Sí. Siempre va unido a valores sociales tradicionales.' } },
  U3: { prompt: 'Un país tiene elecciones competitivas reales. ¿Qué necesita además para ser una democracia liberal?', explanation: 'La democracia liberal exige más que elecciones: también derechos civiles, Estado de derecho y controles significativos sobre el poder del gobierno.', options: { 'u3-a': 'Nada más. Las elecciones competitivas bastan.', 'u3-b': 'Una economía de mercado y propiedad privada de la mayoría de las empresas.', 'u3-c': 'Un líder elegido fuerte que pueda actuar sin que tribunales u otras instituciones lo frenen.', 'u3-d': 'Derechos civiles, Estado de derecho y controles significativos sobre el poder del gobierno.' } },
  U4: { prompt: 'La derecha radical y la extrema derecha suelen agruparse. ¿Cuál es una diferencia principal?', explanation: 'Una diferencia importante es la democracia: la derecha radical puede competir en elecciones, mientras que la extrema derecha rechaza la democracia misma.', options: { 'u4-a': 'La extrema derecha es simplemente más nacionalista.', 'u4-b': 'La derecha radical quiere impuestos más bajos y la extrema derecha propiedad estatal.', 'u4-c': 'La extrema derecha rechaza la democracia misma, mientras la derecha radical puede aceptar elecciones.', 'u4-d': 'La derecha radical siempre usa lenguaje populista y la extrema derecha nunca.' } },
  U5: { prompt: '¿Todos los liberales apoyan las mismas políticas económicas?', explanation: 'El liberalismo es una familia amplia centrada en la libertad. Los liberales pueden discrepar mucho sobre propiedad, mercados, bienestar y el papel del Estado.', options: { 'u5-a': 'Sí. Todos quieren un Estado mínimo.', 'u5-b': 'Sí. El liberalismo trata sobre elecciones, no sobre libertad económica o personal.', 'u5-c': 'Sí. Solo quienes apoyan un gran Estado de bienestar son liberales modernos.', 'u5-d': 'No. Comparten una fuerte preocupación por la libertad, pero discrepan sobre mercados, bienestar y el papel del Estado.' } },
  U6: { prompt: '¿Qué afirmación sobre el socialismo es más precisa?', explanation: 'El socialismo es una familia amplia en la que la propiedad o el control social tienen un papel importante. Incluye distintos modelos económicos y formas históricas democráticas y no democráticas.', options: { 'u6-a': 'Cualquier país con mucho gasto social es socialista aunque la mayoría de las empresas sean privadas.', 'u6-b': 'Es una familia amplia que da un papel importante a la propiedad social, pública, cooperativa o de los trabajadores.', 'u6-c': 'Siempre exige planificación central y propiedad estatal total.', 'u6-d': 'Siempre exige un régimen de partido único.' } },
  U7: { prompt: '¿Cuál es una diferencia importante entre la socialdemocracia moderna y el socialismo?', explanation: 'La socialdemocracia moderna suele mantener una estructura de propiedad principalmente capitalista y usar regulación, servicios públicos y redistribución; la propiedad social es más central en el socialismo.', options: { 'u7-a': 'La socialdemocracia moderna mantiene normalmente la mayoría de las empresas privadas, mientras la propiedad social es más central en el socialismo.', 'u7-b': 'La socialdemocracia apoya impuestos moderados y el socialismo siempre impuestos muy altos.', 'u7-c': 'La socialdemocracia acepta elecciones y el socialismo siempre las rechaza.', 'u7-d': 'El socialismo apoya servicios públicos y la socialdemocracia principalmente servicios privados.' } },
  U8: { prompt: '¿Puede un partido conservador apoyar un Estado de bienestar?', explanation: 'El conservadurismo no está definido por una sola posición sobre bienestar. Algunas corrientes apoyan protección social por responsabilidad, estabilidad o cohesión.', options: { 'u8-a': 'Solo si todas las prestaciones las ofrecen empresas privadas.', 'u8-b': 'No. El conservadurismo siempre exige un Estado mínimo.', 'u8-c': 'Sí. Algunas corrientes apoyan bienestar o regulación para reforzar estabilidad, responsabilidad o cohesión social.', 'u8-d': 'Solo si el gobierno también posee la mayoría de las grandes industrias.' } },
  U9: { prompt: '¿Qué distingue a la democracia cristiana de otros partidos que también apoyan mercados y bienestar?', explanation: 'La democracia cristiana está influida por el pensamiento social cristiano y suele combinarlo con economía social de mercado y subsidiariedad.', options: { 'u9-a': 'Mercados y bienestar generoso bastan para definirla.', 'u9-b': 'Está influida por ideas sociales cristianas y suele defender que las decisiones se tomen tan localmente como sea práctico.', 'u9-c': 'Una política familiar fuerte basta para definirla.', 'u9-d': 'El apoyo a la cooperación europea es su único rasgo definitorio.' } },
  U10: { prompt: '¿Qué separa más claramente al fascismo del conservadurismo o nacionalismo ordinarios?', explanation: 'El fascismo no es simplemente patriotismo fuerte o nacionalismo. Su patrón definitorio combina nacionalismo autoritario con rechazo de la competencia y los derechos liberal-democráticos.', options: { 'u10-a': 'Patriotismo fuerte y políticas estrictas de ley y orden.', 'u10-b': 'Una forma particular de organizar empresas y trabajo, manteniendo democracia y oposición protegidas.', 'u10-c': 'Nacionalismo autoritario junto con rechazo de la oposición política, los derechos individuales y la democracia liberal.', 'u10-d': 'Nacionalismo combinado con un Estado de bienestar mayor.' } },
  U11: { prompt: 'En la teoría de Marx, ¿cuál es el objetivo final del comunismo?', explanation: 'En el ideal marxista, el comunismo es una sociedad sin clases y, finalmente, sin Estado, sin propiedad privada de los principales medios de producción.', options: { 'u11-a': 'Una sociedad sin clases, sin propiedad privada de los principales medios de producción y, finalmente, sin Estado.', 'u11-b': 'Un Estado permanente de partido único con planificación central.', 'u11-c': 'Una economía de mercado propiedad de trabajadores que mantiene capital privado.', 'u11-d': 'Un Estado de bienestar capitalista regulado con empresas privadas.' } },
  U12: { prompt: '¿Cómo se relaciona el comunismo con el socialismo?', explanation: 'El socialismo es una familia amplia sobre propiedad social y poder económico. El comunismo se desarrolló dentro de esa familia y, en la teoría marxista, apunta hacia propiedad común y una sociedad sin clases.', options: { 'u12-a': 'Son sinónimos exactos y siempre describen el mismo programa.', 'u12-b': 'El comunismo es una corriente dentro de la tradición socialista más amplia, con el objetivo a largo plazo de propiedad común y una sociedad sin clases.', 'u12-c': 'El comunismo es principalmente un modelo de bienestar que mantiene la mayoría de las empresas privadas.', 'u12-d': 'El socialismo exige partido único y el comunismo exige necesariamente democracia multipartidista.' } },
  U13: { prompt: '¿Llamar populista a un movimiento significa automáticamente que es autoritario?', explanation: 'El populismo por sí solo no demuestra autoritarismo. Rechazar la competencia política, los controles al poder y las reglas democráticas es una señal más directa.', options: { 'u13-a': 'Sí. El populismo es autoritario por definición.', 'u13-b': 'No. Ganar elecciones significa que ya no puede haber riesgo para la democracia.', 'u13-c': 'No. El populismo puede existir en democracia; rechazar la competencia política y las reglas democráticas es una señal más fuerte.', 'u13-d': 'Solo la regulación económica indica si un movimiento populista amenaza la democracia.' } },
  U14: { prompt: '¿Por qué la soberanía nacional y quién cuenta como miembro pleno de la nación son cuestiones distintas?', explanation: 'La soberanía pregunta quién tiene la autoridad política final. La pertenencia nacional pregunta quién es tratado como miembro pleno de la nación.', options: { 'u14-a': 'No son distintas. Quien apoya autogobierno nacional suele querer menos derechos para ciudadanos naturalizados.', 'u14-b': 'Una persona puede apoyar fuertemente el autogobierno nacional y considerar a los ciudadanos naturalizados miembros plenos de la nación.', 'u14-c': 'La soberanía trata solo de inmigración y la pertenencia solo de comercio.', 'u14-d': 'Ambas ideas solo miden patriotismo.' } },
  U15: { prompt: '¿Por qué la política verde es más amplia que simplemente tener normas ambientales?', explanation: 'La política verde hace de los límites ecológicos y la sostenibilidad preocupaciones centrales y suele relacionarlos con democracia y justicia social.', options: { 'u15-a': 'Cualquier norma ambiental fuerte hace verde un programa aunque el crecimiento ilimitado siga siendo su meta principal.', 'u15-b': 'Sitúa los límites ecológicos y la sostenibilidad en el centro y suele vincularlos con democracia y justicia social.', 'u15-c': 'Siempre exige eliminar completamente los mercados.', 'u15-d': 'Solo trata de conservación y no de economía o democracia.' } },
  U16: { prompt: '¿Qué distingue al libertarismo?', explanation: 'El libertarismo protege especialmente la libertad personal y económica, la propiedad privada y el intercambio voluntario, y busca límites estrictos a la intervención estatal.', options: { 'u16-a': 'Da una prioridad especialmente alta a la libertad individual, la propiedad privada, el intercambio voluntario y limitar la intervención del gobierno.', 'u16-b': 'Trata principalmente de libertad de estilo de vida; la regulación económica y la propiedad son secundarias.', 'u16-c': 'Usa redistribución y un gran Estado de bienestar como vía principal para ampliar la libertad.', 'u16-d': 'Pone las instituciones tradicionales por encima de la elección individual.' } },
  U17: { prompt: '¿Que el Estado posea algunas grandes industrias convierte automáticamente a un país en comunista?', explanation: 'La propiedad pública por sí sola no define el comunismo. Economías mixtas, socialdemocracias y otros sistemas pueden tener empresas públicas y mantener amplia propiedad privada y mercados.', options: { 'u17-a': 'Sí. Cualquier propiedad pública basta para que una economía sea comunista.', 'u17-b': 'Sí, siempre que el gobierno también tenga un gran Estado de bienestar.', 'u17-c': 'No. La propiedad pública existe en muchos sistemas; el comunismo implica una transformación mucho más amplia de la propiedad y las relaciones de clase.', 'u17-d': 'No, porque el comunismo exige que toda actividad económica sea de propiedad privada.' } },
  U18: { prompt: 'Una idea política dice que las decisiones deben tomarse tan localmente como sea práctico y que niveles superiores intervengan cuando haga falta. ¿Cómo se llama?', explanation: 'Es la subsidiariedad: la responsabilidad debe quedarse en el nivel más bajo capaz de cumplir bien la tarea, con apoyo superior cuando sea necesario.', options: { 'u18-a': 'Centralización', 'u18-b': 'Subsidiariedad', 'u18-c': 'Privatización', 'u18-d': 'Supremacía regional' } },
  U19: { prompt: '¿Qué afirmación explica mejor la diferencia entre conservadurismo y política autoritaria?', explanation: 'Valorar orden, tradición o cambio gradual no implica por sí mismo rechazar derechos, competencia política o límites constitucionales.', options: { 'u19-a': 'Querer ley y orden significa automáticamente querer menos límites al poder del gobierno.', 'u19-b': 'Los conservadores pueden valorar orden y continuidad y seguir apoyando derechos, oposición, elecciones y límites al poder del gobierno.', 'u19-c': 'Los valores sociales tradicionales bastan para hacer autoritario un movimiento.', 'u19-d': 'El autoritarismo es simplemente una forma más fuerte de conservadurismo.' } },
  U20: { prompt: '¿Por qué “comunismo” puede significar cosas distintas al hablar de teoría y de historia?', explanation: 'Conviene separar el objetivo teórico de los gobiernos históricos dirigidos por partidos comunistas. El comunismo marxista es una meta sin clases y finalmente sin Estado; los Estados comunistas históricos solían presentarse como etapas de transición hacia esa meta.', options: { 'u20-a': 'Porque Marx definió el comunismo como un Estado permanente de partido único y los gobiernos posteriores rechazaron esa idea.', 'u20-b': 'Porque el comunismo marxista describe una meta sin clases y finalmente sin Estado, mientras partidos comunistas históricos gobernaron a menudo Estados centralizados de partido único que describían como transitorios.', 'u20-c': 'Porque la teoría comunista trata principalmente de nacionalismo y los gobiernos comunistas históricos fueron principalmente libertarios.', 'u20-d': 'No hay diferencia: todo gobierno dirigido por un partido comunista ya alcanzó el ideal comunista final.' } },
};

const fr: Record<string, LocalizedQuestion> = {
  C1: { prompt: 'La plupart des entreprises restent privées. L’État fournit de solides services publics, une protection sociale et des droits pour les travailleurs, financés en partie par une contribution plus élevée des hauts revenus.', explanation: 'Cela correspond à la social-démocratie moderne : une économie surtout privée, combinée à des services publics, de la régulation et de la redistribution.' },
  C2: { prompt: 'Les grandes entreprises devraient appartenir beaucoup plus au public, aux travailleurs ou à des coopératives, plutôt qu’aux seuls actionnaires privés.', explanation: 'Le socialisme est la grande famille dans laquelle la propriété sociale, publique, coopérative ou des travailleurs joue un rôle central.' },
  C3: { prompt: 'La liberté individuelle, la propriété privée et l’échange volontaire passent d’abord. L’État devrait intervenir le moins possible dans les choix personnels et économiques pacifiques.', explanation: 'Le libertarianisme accorde une priorité particulièrement forte à la liberté personnelle et économique, à la propriété privée et aux échanges volontaires.' },
  C4: { prompt: 'Les institutions anciennes méritent le respect. Le changement devrait généralement être progressif et les grandes expériences sociales abordées avec prudence.', explanation: 'Le conservatisme met souvent l’accent sur la continuité, les institutions héritées et la prudence face aux transformations rapides.' },
  C5: { prompt: 'Les marchés et la propriété privée sont importants, mais la protection sociale et la régulation peuvent être utiles lorsqu’elles renforcent la stabilité et la cohésion sociale.', explanation: 'Le conservatisme n’exige pas un État minimal ; certaines traditions conservatrices acceptent protection sociale et régulation au nom de la stabilité, de la responsabilité et de la cohésion.' },
  C6: { prompt: 'Les limites écologiques et la durabilité à long terme devraient être au cœur de la politique, avec participation citoyenne, décisions locales et justice sociale.', explanation: 'L’écologie politique place les limites écologiques et la durabilité au centre et les relie souvent à la participation, à la décentralisation et à la justice sociale.' },
  C7: { prompt: 'L’objectif final est une société sans classes, sans propriété privée des principaux moyens de production et, à terme, sans État.', explanation: 'C’est l’idéal communiste marxiste : une société sans classes et finalement sans État, fondée sur la propriété commune des moyens de production.' },
  C8: { prompt: 'La nation doit être refondée sous un dirigeant autoritaire fort. Les partis d’opposition et la démocratie libérale sont rejetés et les droits individuels passent après le projet national.', explanation: 'Le fascisme combine ultranationalisme et autoritarisme avec le rejet de la démocratie libérale pluraliste et de droits politiques fondamentaux.' },
  C9: { prompt: 'Les nations ont une valeur politique particulière et devraient pouvoir se gouverner elles-mêmes. Cette idée ne fixe pas à elle seule une position sur les marchés, la protection sociale ou les impôts.', explanation: 'Le nationalisme donne une importance politique aux nations et à l’autodétermination nationale, mais peut se combiner avec des idées économiques et sociales très différentes.' },
  C10: { prompt: 'La liberté individuelle et l’égalité juridique sont centrales. Au sein de cette tradition, les désaccords sont importants sur les marchés, la protection sociale et le rôle de l’État.', explanation: 'Le libéralisme est une famille large centrée sur la liberté, mais divisée sur la propriété, les marchés, la protection sociale et l’action de l’État.' },
  C11: { prompt: 'Le mouvement s’inspire d’idées sociales chrétiennes. Il soutient une économie sociale de marché et la protection sociale, et préfère que les décisions soient prises aussi localement que possible.', explanation: 'La démocratie chrétienne associe inspiration sociale chrétienne, économie sociale de marché et souvent le principe de subsidiarité.' },
  C12: { prompt: 'La politique est vue comme une lutte entre les gens ordinaires et une élite corrompue. Le gouvernement devrait appliquer la volonté commune du peuple.', explanation: 'Le populisme oppose généralement un peuple vertueux à une élite corrompue et accorde un poids particulier à la volonté générale du peuple.' },
  C13: { prompt: 'Le mouvement veut un ordre public strict, privilégie ceux qu’il considère comme membres historiques de la nation et affirme représenter les gens ordinaires contre une élite corrompue. Il participe toujours aux élections.', explanation: 'La droite radicale populiste combine généralement des conceptions exclusives de l’appartenance nationale, l’autoritarisme et le populisme dans le cadre électoral.' },
  C14: { prompt: 'Le mouvement rejette la démocratie elle-même et affirme que ses adversaires politiques ne devraient pas avoir le même droit de concourir pour le pouvoir.', explanation: 'Le rejet explicite de la compétition démocratique est un marqueur important qui distingue l’extrême droite de la droite radicale.' },
  C15: { prompt: 'Il existe des élections compétitives, des droits civils, l’État de droit et des contrôles indépendants sur les dirigeants élus.', explanation: 'La démocratie libérale associe compétition électorale, libertés civiles, État de droit et contrôles indépendants du pouvoir politique.' },
  C16: { prompt: 'Un mouvement révolutionnaire veut mettre fin à la propriété capitaliste des grandes industries, la remplacer par une propriété commune et construire finalement une société sans classes.', explanation: 'Le communisme est issu du projet marxiste de remplacer la propriété capitaliste et les divisions de classe par la propriété commune et, à terme, une société sans classes.' },
  C17: { prompt: 'Un mouvement démocratique veut beaucoup plus de propriété par les travailleurs, les coopératives ou le secteur public, tout en maintenant élections libres, droits civils et partis d’opposition.', explanation: 'Le socialisme peut être démocratique et pluraliste ; davantage de propriété sociale n’implique pas à lui seul un régime à parti unique.' },
  C18: { prompt: 'Les sociétés riches pourraient parfois devoir consommer moins car les limites écologiques ne peuvent pas toujours être résolues uniquement par des technologies plus propres.', explanation: 'L’écologie politique accorde un poids particulier aux limites écologiques et peut soutenir des changements plus profonds de production et de consommation.' },
  C19: { prompt: 'L’État devrait protéger les droits et les contrats mais, autrement, intervenir le moins possible dans les choix pacifiques des adultes, des entreprises et des associations volontaires.', explanation: 'Le libertarianisme donne une très forte priorité à la liberté individuelle et aux échanges volontaires et cherche à limiter fortement la coercition de l’État.' },
  C20: { prompt: 'L’ordre social, la continuité et les institutions anciennes sont importants, tout en maintenant élections, partis d’opposition et limites constitutionnelles.', explanation: 'Le conservatisme peut valoriser ordre, continuité et institutions héritées tout en restant pleinement compatible avec la démocratie constitutionnelle.' },

  U1: { prompt: 'Quelle affirmation décrit le mieux le populisme ?', explanation: 'Le populisme présente souvent la politique comme un conflit entre les gens ordinaires et une élite corrompue. Il peut se combiner avec des idées de gauche ou de droite très différentes.', options: { 'u1-a': 'C’est surtout une manière de parler sans idées politiques récurrentes.', 'u1-b': 'C’est un programme économique complet qui exige toujours protectionnisme, redistribution et propriété publique.', 'u1-c': 'Il divise souvent la politique entre les gens ordinaires et une élite corrompue et peut se combiner avec différentes idées de gauche ou de droite.', 'u1-d': 'C’est la même chose que la démocratie directe et il rejette toujours représentants élus et partis.' } },
  U2: { prompt: 'Le nationalisme indique-t-il automatiquement si un mouvement est de gauche ou de droite ?', explanation: 'Le nationalisme donne une importance politique aux nations et à l’autodétermination, mais il s’est historiquement combiné avec des idées conservatrices, libérales, socialistes et autres.', options: { 'u2-a': 'Oui. Il va normalement avec une politique économique de droite.', 'u2-b': 'Non. Il peut se combiner avec différentes traditions politiques ; il faut aussi connaître les autres positions du mouvement.', 'u2-c': 'Oui. Il concerne surtout l’immigration et le contrôle des frontières.', 'u2-d': 'Oui. Il va toujours avec des valeurs sociales traditionnelles.' } },
  U3: { prompt: 'Un pays a de vraies élections compétitives. Que lui faut-il en plus pour être une démocratie libérale ?', explanation: 'La démocratie libérale exige davantage que des élections : droits civils, État de droit et contrôles significatifs limitant le pouvoir du gouvernement.', options: { 'u3-a': 'Rien de plus. Des élections compétitives suffisent.', 'u3-b': 'Une économie de marché et la propriété privée de la plupart des entreprises.', 'u3-c': 'Un dirigeant élu fort pouvant agir sans être bloqué par les tribunaux ou d’autres institutions.', 'u3-d': 'Des droits civils, l’État de droit et des contrôles significatifs sur le pouvoir du gouvernement.' } },
  U4: { prompt: 'La droite radicale et l’extrême droite sont souvent regroupées. Quelle est une différence principale ?', explanation: 'Une différence importante concerne la démocratie : la droite radicale peut participer aux élections, tandis que l’extrême droite rejette la démocratie elle-même.', options: { 'u4-a': 'L’extrême droite est simplement plus nationaliste.', 'u4-b': 'La droite radicale veut moins d’impôts, l’extrême droite plus de propriété publique.', 'u4-c': 'L’extrême droite rejette la démocratie elle-même, tandis que la droite radicale peut accepter les élections.', 'u4-d': 'La droite radicale utilise toujours un langage populiste, l’extrême droite jamais.' } },
  U5: { prompt: 'Tous les libéraux soutiennent-ils les mêmes politiques économiques ?', explanation: 'Le libéralisme est une famille large centrée sur la liberté. Les libéraux peuvent beaucoup diverger sur la propriété, les marchés, la protection sociale et le rôle de l’État.', options: { 'u5-a': 'Oui. Tous veulent un État minimal.', 'u5-b': 'Oui. Le libéralisme concerne surtout les élections, pas les libertés économiques ou personnelles.', 'u5-c': 'Oui. Seuls ceux qui soutiennent un grand État-providence sont des libéraux modernes.', 'u5-d': 'Non. Ils partagent une forte préoccupation pour la liberté mais divergent sur les marchés, la protection sociale et le rôle de l’État.' } },
  U6: { prompt: 'Quelle affirmation sur le socialisme est la plus exacte ?', explanation: 'Le socialisme est une famille large dans laquelle la propriété ou le contrôle social joue un rôle important. Elle comprend différents modèles économiques ainsi que des formes historiques démocratiques et non démocratiques.', options: { 'u6-a': 'Tout pays avec de fortes dépenses sociales est socialiste même si la plupart des entreprises restent privées.', 'u6-b': 'C’est une famille large qui donne un rôle important à la propriété sociale, publique, coopérative ou des travailleurs.', 'u6-c': 'Il exige toujours la planification centrale et une propriété publique totale.', 'u6-d': 'Il exige toujours un régime à parti unique.' } },
  U7: { prompt: 'Quelle est une différence importante entre la social-démocratie moderne et le socialisme ?', explanation: 'La social-démocratie moderne conserve généralement une structure de propriété surtout capitaliste et utilise régulation, services publics et redistribution ; la propriété sociale est plus centrale dans le socialisme.', options: { 'u7-a': 'La social-démocratie moderne garde généralement la plupart des entreprises privées, tandis que la propriété sociale est plus centrale dans le socialisme.', 'u7-b': 'La social-démocratie soutient des impôts modérés, le socialisme toujours des impôts très élevés.', 'u7-c': 'La social-démocratie accepte les élections, le socialisme les rejette toujours.', 'u7-d': 'Le socialisme soutient les services publics, la social-démocratie surtout les services privés.' } },
  U8: { prompt: 'Un parti conservateur peut-il soutenir un État-providence ?', explanation: 'Le conservatisme n’est pas défini par une seule position sur la protection sociale. Certaines traditions soutiennent des politiques sociales au nom de la responsabilité, de la stabilité ou de la cohésion.', options: { 'u8-a': 'Seulement si toutes les prestations sont fournies par des entreprises privées.', 'u8-b': 'Non. Le conservatisme exige toujours un État minimal.', 'u8-c': 'Oui. Certaines traditions conservatrices soutiennent protection sociale ou régulation pour renforcer stabilité, responsabilité ou cohésion.', 'u8-d': 'Seulement si l’État possède aussi la plupart des grandes industries.' } },
  U9: { prompt: 'Qu’est-ce qui distingue la démocratie chrétienne d’autres partis qui soutiennent aussi les marchés et la protection sociale ?', explanation: 'La démocratie chrétienne s’inspire de la pensée sociale chrétienne et l’associe souvent à l’économie sociale de marché et à la subsidiarité.', options: { 'u9-a': 'Les marchés et une protection sociale généreuse suffisent à la définir.', 'u9-b': 'Elle est façonnée par des idées sociales chrétiennes et défend souvent des décisions prises aussi localement que possible.', 'u9-c': 'Une politique familiale forte suffit à la définir.', 'u9-d': 'Le soutien à la coopération européenne est son seul trait distinctif.' } },
  U10: { prompt: 'Qu’est-ce qui sépare le plus clairement le fascisme du conservatisme ou du nationalisme ordinaires ?', explanation: 'Le fascisme n’est pas simplement un patriotisme fort ou du nationalisme. Son schéma distinctif associe nationalisme autoritaire et rejet de la compétition et des droits libéraux-démocratiques.', options: { 'u10-a': 'Un patriotisme fort et des politiques strictes d’ordre public.', 'u10-b': 'Une certaine organisation du travail et des entreprises tout en protégeant démocratie et opposition.', 'u10-c': 'Un nationalisme autoritaire avec rejet de l’opposition politique, des droits individuels et de la démocratie libérale.', 'u10-d': 'Du nationalisme combiné à un État-providence plus large.' } },
  U11: { prompt: 'Dans la théorie de Marx, quel est l’objectif final du communisme ?', explanation: 'Dans l’idéal marxiste, le communisme est sans classes et finalement sans État, sans propriété privée des principaux moyens de production.', options: { 'u11-a': 'Une société sans classes, sans propriété privée des principaux moyens de production et, finalement, sans État.', 'u11-b': 'Un État permanent à parti unique avec planification centrale.', 'u11-c': 'Une économie de marché détenue par les travailleurs tout en conservant du capital privé.', 'u11-d': 'Un État-providence capitaliste réglementé avec des entreprises privées.' } },
  U12: { prompt: 'Quel est le lien entre communisme et socialisme ?', explanation: 'Le socialisme est une famille large portant sur la propriété sociale et le pouvoir économique. Le communisme s’est développé au sein de cette famille et vise, dans la théorie marxiste, une propriété commune et une société sans classes.', options: { 'u12-a': 'Ce sont des synonymes exacts qui décrivent toujours le même programme.', 'u12-b': 'Le communisme est un courant de la tradition socialiste plus large, avec pour objectif à long terme une propriété commune et une société sans classes.', 'u12-c': 'Le communisme est surtout un modèle d’État-providence qui garde la plupart des grandes entreprises privées.', 'u12-d': 'Le socialisme exige forcément le parti unique, tandis que le communisme exige forcément une démocratie multipartite.' } },
  U13: { prompt: 'Qualifier un mouvement de populiste signifie-t-il automatiquement qu’il est autoritaire ?', explanation: 'Le populisme seul ne prouve pas l’autoritarisme. Le rejet de la compétition politique, des contrôles du pouvoir et des règles démocratiques est un signal plus direct.', options: { 'u13-a': 'Oui. Le populisme est autoritaire par définition.', 'u13-b': 'Non. Gagner une élection signifie qu’il n’y a plus de risque pour la démocratie.', 'u13-c': 'Non. Le populisme peut exister en démocratie ; rejeter la compétition politique et les règles démocratiques est un signal plus fort.', 'u13-d': 'Seule la régulation économique indique si un mouvement populiste menace la démocratie.' } },
  U14: { prompt: 'Pourquoi la souveraineté nationale et la question de savoir qui appartient pleinement à la nation sont-elles différentes ?', explanation: 'La souveraineté demande qui détient l’autorité politique finale. L’appartenance nationale demande qui est considéré comme membre à part entière.', options: { 'u14-a': 'Elles ne sont pas différentes. Soutenir l’autogouvernement national signifie généralement vouloir moins de droits pour les citoyens naturalisés.', 'u14-b': 'On peut soutenir fortement l’autogouvernement national tout en considérant les citoyens naturalisés comme des membres à part entière.', 'u14-c': 'La souveraineté concerne seulement l’immigration, l’appartenance seulement le commerce.', 'u14-d': 'Les deux idées mesurent simplement le patriotisme.' } },
  U15: { prompt: 'Pourquoi l’écologie politique va-t-elle au-delà de simples règles environnementales ?', explanation: 'L’écologie politique fait des limites écologiques et de la durabilité des préoccupations politiques centrales et les relie souvent à la démocratie et à la justice sociale.', options: { 'u15-a': 'Toute règle environnementale forte rend un programme écologiste même si la croissance illimitée reste son objectif principal.', 'u15-b': 'Elle place les limites écologiques et la durabilité au centre et les relie souvent à la démocratie et à la justice sociale.', 'u15-c': 'Elle exige toujours la fin complète des marchés.', 'u15-d': 'Elle concerne seulement la conservation de la nature, pas l’économie ou la démocratie.' } },
  U16: { prompt: 'Qu’est-ce qui distingue le libertarianisme ?', explanation: 'Le libertarianisme protège particulièrement la liberté personnelle et économique, la propriété privée et l’échange volontaire, et cherche à limiter fortement l’intervention de l’État.', options: { 'u16-a': 'Il accorde une priorité particulièrement forte à la liberté individuelle, à la propriété privée, à l’échange volontaire et à la limitation de l’intervention publique.', 'u16-b': 'Il concerne surtout la liberté de mode de vie ; la régulation économique et la propriété sont secondaires.', 'u16-c': 'Il utilise la redistribution et un grand État-providence comme principal moyen d’accroître la liberté.', 'u16-d': 'Il place les institutions anciennes au-dessus du choix individuel.' } },
  U17: { prompt: 'La propriété publique de certaines grandes industries rend-elle automatiquement un pays communiste ?', explanation: 'La propriété publique ne définit pas à elle seule le communisme. Des économies mixtes, des social-démocraties et d’autres systèmes peuvent avoir de grandes entreprises publiques tout en conservant une large propriété privée et des marchés.', options: { 'u17-a': 'Oui. Toute propriété publique suffit pour rendre une économie communiste.', 'u17-b': 'Oui, du moment que l’État a aussi un grand système de protection sociale.', 'u17-c': 'Non. La propriété publique existe dans de nombreux systèmes ; le communisme implique une transformation beaucoup plus large de la propriété et des rapports de classe.', 'u17-d': 'Non, car le communisme exige que toute activité économique soit privée.' } },
  U18: { prompt: 'Une idée politique dit que les décisions doivent être prises aussi localement que possible, avec intervention des niveaux supérieurs lorsque nécessaire. Comment s’appelle-t-elle ?', explanation: 'C’est la subsidiarité : la responsabilité reste au niveau le plus bas capable de bien accomplir la tâche, les niveaux supérieurs intervenant si nécessaire.', options: { 'u18-a': 'Centralisation', 'u18-b': 'Subsidiarité', 'u18-c': 'Privatisation', 'u18-d': 'Suprématie régionale' } },
  U19: { prompt: 'Quelle affirmation explique le mieux la différence entre conservatisme et politique autoritaire ?', explanation: 'Valoriser l’ordre, la tradition ou le changement progressif n’implique pas à lui seul le rejet des droits, de la compétition politique ou des limites constitutionnelles.', options: { 'u19-a': 'Vouloir l’ordre signifie automatiquement vouloir moins de limites au pouvoir du gouvernement.', 'u19-b': 'Les conservateurs peuvent valoriser ordre et continuité tout en soutenant droits, opposition, élections et limites du pouvoir.', 'u19-c': 'Des valeurs sociales traditionnelles suffisent pour rendre un mouvement autoritaire.', 'u19-d': 'L’autoritarisme est simplement une forme plus forte de conservatisme.' } },
  U20: { prompt: 'Pourquoi le mot « communisme » peut-il désigner des choses différentes lorsqu’on parle de théorie et d’histoire ?', explanation: 'Il est utile de distinguer l’objectif théorique des gouvernements historiques dirigés par des partis communistes. Le communisme marxiste vise une société sans classes et finalement sans État ; les États communistes historiques se présentaient généralement comme des étapes de transition vers cet objectif.', options: { 'u20-a': 'Parce que Marx définissait le communisme comme un État permanent à parti unique et que les gouvernements ultérieurs ont rejeté cette idée.', 'u20-b': 'Parce que le communisme marxiste décrit un objectif sans classes et finalement sans État, tandis que des partis communistes historiques ont souvent gouverné des États centralisés à parti unique présentés comme transitoires.', 'u20-c': 'Parce que la théorie communiste concerne surtout le nationalisme, alors que les gouvernements communistes historiques étaient surtout libertariens.', 'u20-d': 'Il n’y a aucune différence : tout gouvernement dirigé par un parti communiste correspondait déjà à l’idéal communiste final.' } },
};

const translations: Record<SupportedTranslationLocale, Record<string, LocalizedQuestion>> = { de, es, fr };

export function publicLiteracyPrompt(locale: LiteracyLocale, question: LiteracyQuestion) {
  if (locale === 'en') return question.prompt;
  return translations[locale][question.id]?.prompt ?? question.prompt;
}

export function publicLiteracyExplanation(locale: LiteracyLocale, question: LiteracyQuestion) {
  if (locale === 'en') return question.explanation;
  return translations[locale][question.id]?.explanation ?? question.explanation;
}

export function publicLiteracyOption(locale: LiteracyLocale, question: LiteracyQuestion, optionId: string) {
  const option = question.options.find((candidate) => candidate.id === optionId);
  if (!option) return optionId;
  if (locale === 'en') return option.label;
  const direct = translations[locale][question.id]?.options?.[optionId];
  if (direct) return direct;
  return termLabels[locale][optionId] ?? option.label;
}
